### ISSUE TITLE
[BUG] PropLexInt.update() crashing if called "too soon"

### ISSUE THREAD

**Issue by Holt59** [chocoteam/choco-solver#1001]
**Describe the bug**

I am using `PropLexInt` in a multi-threaded environment using a portfolio (not the one from this repository, but something very close). My loop is similar to the code below:

```java
while (portfolio.solve()) {
    final Model bestModel = /* find the model the best solution */;

    for (final Model model : models) {
        if (model != bestModel) {
            model.getSolver().restart();
        }

        // retrieve the propLexInt for the model
        final PropLexInt propLexInt = propLexInts.get(model);
        propLexInt.update(bestFound, true);
    }
}
```

On very rare occasion, the `update()` call can crash with an out-of-bound exception in `propagateOnBacktrack` because `PropagationEngine.propagators` is empty. As-far-as I can tell, this can occur if one of the model finds a solution before the other model is fully initialized (`propLexInt`'s state is NEW apparently).

**Expected behavior**

Not really sure if that's a bug, but that's certainly hard to debug/find, so maybe add an extra case in `forcePropagationOnBacktrack` that checks if the propagator `isStateLess()` and does nothing in this case.

**Possible solution**

See above, in my code I replaced `true` with `!isStateLess()` and that seems to fix the issue.

**Screenshots**

**Environment (please complete the following information):**
- Choco-solver version: 4.10.10
- JRE : 8

**Comment by cprudhom** [comment]
Hi

Thank you for sharing, but since this part of code is not in the distribution, there is nothing I can do :/
Plus, you probably find the right thing to do.
Eventually, you could propagate all models sequentially once before running the // solving.

**Comment by Holt59** [comment]
What I am proposing is to add an extra check in `forcePropagationOnBacktrack` to skip propagation if `isStateLess()` is `true` (similar to the `isPassive()` check).
