### ISSUE TITLE
[BUG] fzn-choco, table, wrong answer

### ISSUE THREAD

**Issue by matsc-at-sics-se** [chocoteam/choco-solver#1045]
Choco 4.10.13.

Choco reports three solutions on this one: `A=1, A=7, A=18`. `A=1` is wrong.
```
include "globals.mzn";
var {1,2,4,7,18}: A;
constraint table([A,A,], [| 1, 4, | 2, 1, | 4, 7, | 7, 2, | 7, 7, | 18, 18, |]);
solve :: int_search([A], largest, indomain_interval, complete) satisfy;
```

**Comment by cprudhom** [comment]
When multiple occurrences of variables are in the scope of table constraint, some algorithms does not work as expected.
The solution is to replace such occurrences by views.

**Comment by matsc-at-sics-se** [comment]
I pulled and recompiled yesterday. The wrong solution is still there. Just letting you know.

**Comment by cprudhom** [comment]
Thank you, I had partly done the work.
