### ISSUE TITLE
[Question] Excuse me, I want to quickly get the intersection of all variable solutions, how to do？

### ISSUE THREAD

**Issue by oriming** [chocoteam/choco-solver#1060]
I model a complex expression that has more than 600 solutions. In fact, there are only 14 variables. I just want to access the variables of the final solution into the structure of `Map <String, Set<Integer>`, but it takes a long time to get the solution.

I want to get all the solutions quickly, how to model, or how to set the search strategy?🥺😩

**Comment by cprudhom** [comment]
Hi

Please use the Discord channel (https://discord.gg/TARfcBQb) for the questions.
CP
