### ISSUE TITLE
[BUG] IntQuickSort.sort may behave incorrectly if left > 0

### ISSUE THREAD

**Issue by niemisto** [chocoteam/choco-solver#1111]
**Describe the bug**
IntQuickSort.sort might move some elements from the range [left,right] to the range [0,left-1] during insertion sort. This results both undesired modification in range [0,left-1] and range [left,right] not being in order after the method returns.

**To Reproduce**
```
int[] array = new int[] { 4, 2, 3, 1  };
IntQuickSort.sort(array, 1, array.length-1, Integer::compare);
System.out.println(Arrays.toString(array));
```
This prints `[1, 4, 2, 3]` instead of expected `[4, 1, 2, 3]`.

**Possible solution**
The bug seems to be the following line in IntQuickSort.insertionSort:
```
                while (i > -1 && comparator.compare(key, array[i]) < 0);
```
Instead of `i > -1` the comparison should be `i >= left`.

**Environment:**
- Choco-solver version: 4.10.17

**Comment by cprudhom** [comment]
Can you give the full path of the class IntQuickSort?

**Comment by niemisto** [comment]
My mistake. Reported this to a wrong project. The bug was in eclipse-collections.
