### ISSUE TITLE
Support arithmetic x + y = z with 3 variables

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#178]
Quite often I have this constraint. Most of the time, it was to express relationships between a task variable. In this case VF.task() ... do the job perfectly.

The potential problem is when a new user want to state this constraint without knowing about task variables. This was my situation at the beginning. In this case, I naturally tried to use ICF.arithmetic but this does not work. Once I get the "task hack", that was ok. but in the API or the documentation, there should be a workaround to support such a constraint more explicitly.

**Comment by cprudhom** [comment]
Now available in 3.3.3
