### ISSUE TITLE
Straightforward constraints

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco-solver#288]
Hi all, 

I wondered why there is not some straightforward constraints like: 
1- arithmetic with three variables: X op1 Y op2 Z 
2- distance:  |X - Y| != Z
Is there a reason to not add these constraints to ICF, because they seem to be easy to add (unless for 1-). I think that the propagator of 2 must be implemented. Right? 

Cheers,

**Comment by cprudhom** [comment]
Hi Mohamed,

Hope you're doing well.
You are right, those constraints are missing in the API, the main reason is that they can easily reformulated with other constraints.
However, we plan to make an expression parser (see #242) in order to ease modeling.

**Comment by mwahbi** [comment]
Thank you Charles, 
I am fine, hope the same for you ;) 
Okay, I wish in the new (old) expression parser you will keep the arithmetic constraints. They very useful for students to go through choco. 
Cheers

**Comment by cprudhom** [comment]
Done in 3abed5a17d33d86bbbc9be6e41cc505a68eb1159
