### ISSUE TITLE
Task does not check input

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#316]
Declaring a task with fixed variables such as 
- s = 0;
- d = 2;
- e = 4;

does not fail (never).

**Comment by jgFages** [comment]
Tasks have a method to perform initial propagation. 
As it is not a constraint, you have to call it manually.

I believe we should remove tasks...

**Comment by fhermeni** [comment]
As a heavy user of tasks, I appreciate to have structures that are more expressives than n-ary array of variables to express constraints ;)

**Comment by cprudhom** [comment]
I think this is close; cf. 3abed5a17d33d86bbbc9be6e41cc505a68eb1159 and #383
