### ISSUE TITLE
Element: to refactor

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#325]
There seems to be a loss of efficient (and filtering) on PropElement and PropElemenVar.
See MZN2015: is.mzn and open-stacks.mzn.

We could have a unique Constraint with multiple implementations, depending on the underlying cases (boolean values, increasing values, etc). As a central constraint, it should not be overlooked.

**Comment by jgFages** [comment]
More precisely, element currently does not apply the filtering of the member constraint, see: 

public void testElementMissMember(){
		Model model = new Model();
		int[] table = new int[]{15, 50, 700};
		IntVar indexVar = model.intVar("index", 0, 2000, false);
		IntVar valueVar = model.intVar("value", 1, 2000, false); // enumerated
		model.element(valueVar, table, indexVar).post();
		// model.member(valueVar, table).post();
		System.out.println("before filtering : "+valueVar);
		try {
			model.getSolver().propagate();
		} catch(ContradictionException e) {
			e.printStackTrace();
		}
		System.out.println("after filtering : "+valueVar);
	}
