### ISSUE TITLE
Printing model transformation information

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#360]
When some model transformations are automatically applied, (i.e., when intension constraints are converted into extension versions), what about tracing such modifications on console to inform users ?

**Comment by jgFages** [comment]
The user models the problem with (semantical) constraints, not filtering algorithms, that are preserved through these transformations. Why should the user care about which propagator is used behind it?

**Comment by cprudhom** [comment]
Sure, but sometimes Choco makes some arbitral changes and users may want to be aware of that (or not). It could be an advanced user feature, but it can be useful for debugging purpose.

**Comment by cprudhom** [comment]
This should be done in a plugin
