### ISSUE TITLE
ParallelResolution API

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#362]
Hi

Currently there is no dedicated object related to the parallel resolution. SMF helps at preparing the environment but at the end, there is no API to provide the best solution computed. We must browse every solver, analyse the solutions and return the best one.

This might be automated. I propose you to provide a dedicated ParallelResolution object that:
- takes as parameters the solver objects
- expose a method to populate each solver
- expose the methods to launch the resolutions
- expose a method to retrieve the best solution computed. Internally it will have to merge all the individual solution pools of course

That was my two cents

Regards

**Comment by cprudhom** [comment]
Unlike I told you, I spent some time on your issue.
I'll commit a suggestion on the develop branch. Any feedback is appreciated.
