### ISSUE TITLE
Discussion: constructive disjunction based on v = union(v1, v2)

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#367]
I think constructive disjunction can be obtained by implementing a UNION view.

Consider the following problem:
```java
Solver s = new Solver();                                 
IntVar a = VF.enumerated("A", 0, 100, s);                
BoolVar b1 = ICF.arithm(a, "=", 9).reif();               
BoolVar b2 = ICF.arithm(a, "=", 10).reif();              
SatFactory.addBoolOrArrayEqualTrue(new BoolVar[]{b1,b2});
Chatterbox.showStatistics(s);                            
s.set(ISF.lexico_LB(a));                                 
s.findAllSolutions();                                    
```
it needs 12 nodes to explore all the search space even though we trivially detect that `a` can only be set to 2 or 3.

Now, let's consider the following example:
```java
Solver s = new Solver();                                 
IntVar a = VF.enumerated("A", 0, 100, s);     
IntVar a1 = VF.enumerated("A1", 0, 100, s);
IntVar a2 = VF.enumerated("A2", 0, 100, s);                
solver.post(ICF.arithm(a1, "=", 9));               
solver.post(ICF.arithm(a2, "=", 10));               
solver.post(ICF.union(a, a1, a2));
Chatterbox.showStatistics(s);                            
s.set(ISF.lexico_LB(a));                                 
s.findAllSolutions();  
```
Actually `ICF.union(a, a1, a2)` does not exist yet, but in principle, it should better the propagation (in the example showed here, the constructive disjunction is obvious, but with more complex constraints, it should be even more relevant).

Somehow, there is a problem: union should accept that one variable among a1 and a2 has an empty domain... 

This is just to start a discussion.

**Comment by jgFages** [comment]
Yes it does exist. 
Just use a SetVar with a union constraint:
//VALUES = {value(x) | x in VARS}
SetConstraintFactory.int_values_union(IntVar[] VARS, SetVar VALUES)

You get 

SCF.int_values_union({x1,x2}, set)
SCF.int_values_union(x, set)

**Comment by cprudhom** [comment]
Ok to use Setvar.
But, this is not enough, since x1 or x2 can be empty, which is not possible from technical reason.

**Comment by jgFages** [comment]
Set var can be empty so you can use set var for x1 and x2 (and classical union constrant)

**Comment by cprudhom** [comment]
No, that's not correct, IntVar can't be empty. But, to go further, I need to think to a more relevant example.

**Comment by jgFages** [comment]
Well, maybe I misunderstand your example, but this works to me:

```java
		Solver s = new Solver();
		IntVar a = VF.enumerated("A", 0, 100, s);
		// set view of A
		SetVar aset = VF.set("A as a set", 0, 100, s);
		s.post(SCF.int_values_union(new IntVar[]{a},aset));
		// disjunctive construction
		SetVar a9 = VF.set("{} or {9}", new int[]{9}, s);
		SetVar a10 = VF.set("{} or {10}",new int[]{10},s);
		s.post(SCF.union(new SetVar[]{a9,a10},aset));
		// link to booleans
		BoolVar b1 = SCF.notEmpty(a9).reif();
		BoolVar b2 = SCF.notEmpty(a10).reif();
		// ---
		SatFactory.addBoolOrArrayEqualTrue(new BoolVar[]{b1, b2});
		Chatterbox.showStatistics(s);
		Chatterbox.showSolutions(s);
		s.set(ISF.lexico_LB(a));
		s.findAllSolutions(); 
```

**Comment by cprudhom** [comment]
I'm not saying it doesn't work but I think this is not straightforward.
Getting a result with SetVar may not be easy when dealing with n-ary constraint (and n>1).

Consider now the following example (constructive disjunction should reduce domain of X and Y to {0,1,9,10}) :
```
X = {0..10}, Y={0..10} 
X +9 <= Y or Y + 9 <= X 
```
I don't think SetVar is very suitable.

**Comment by jgFages** [comment]
Well, it is not straightforward I admit, but I still think it is a good lead as it enables to allow optional variables somehow. For your example, I would do the following:

```java
public static void main(String[] args) {
		Solver s = new Solver();
		IntVar x = VF.enumerated("x", 0, 10, s);
		IntVar y = VF.enumerated("y", 0, 10, s);
		// set view of A
		SetVar xset = VF.set("x as a set", 0, 10, s);
		SetVar yset = VF.set("y as a set", 0, 10, s);
		s.post(SCF.int_values_union(new IntVar[]{x},xset));
		s.post(SCF.int_values_union(new IntVar[]{y},yset));
		// X +9 <= Y or Y + 9 <= X
		SetVar Xleft = VF.set("", 0, 10, s);
		SetVar tmpLeft = VF.set("", 9, 19, s);
		s.post(SCF.offSet(Xleft,tmpLeft,9));
		SetVar Yleft = VF.set("", 0, 10, s);
		s.post(leqSet(tmpLeft, Yleft));

		SetVar Yright = VF.set("",0, 10, s);
		SetVar tmpRight = VF.set("", 9, 19, s);
		s.post(SCF.offSet(Yright,tmpRight,9));
		SetVar Xright = VF.set("", 0, 10, s);
		s.post(leqSet(tmpRight, Xright));

		//
		s.post(SCF.union(new SetVar[]{Xleft, Xright}, xset));
		s.post(SCF.union(new SetVar[]{Yleft,Yright},yset));
		// link to booleans
		BoolVar b1 = SCF.notEmpty(Yleft).reif();
		BoolVar b2 = SCF.notEmpty(Yright).reif();
		// ---
		SatFactory.addBoolOrArrayEqualTrue(new BoolVar[]{b1, b2});
		Chatterbox.showStatistics(s);
		Chatterbox.showSolutions(s);
		try {
			s.propagate();
		} catch (ContradictionException e) {
			e.printStackTrace();
		}
		System.out.println(x);
		System.out.println(y);
    }

	public static Constraint leqSet(SetVar x, SetVar y){
		return SCF.offSet(x,y,0); // equality here because leqSet is not implemented (yet)
	}
```

It may seem a bit heavy but it actually follows a pattern. You can see an AST on the top of this. 

However, moving from an AST of the CSP (which we don't even have yet) to a constructive disjunction reformulation in an automated way requires hard work I guess!
