### ISSUE TITLE
Record solution: reduce memory footprint

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#370]
When calling `Solution.record(Solver solver)`, a call to `solver.getVars()` is made.
It creates a copy of the variables from the solver, but the solution object only needs to read it, not copy it. 
So, calling `solver.getNbVars()` and `Variable var = solver.getVar(i);` should be enough.

**Comment by cprudhom** [comment]
In milestone 4.0.0, no solution is recorded by default and recording solution should be done manually.

**Comment by arnaud-m** [comment]
Hi,

I do not really understand why. 
Almost all solvers record the last solution found. It is not really time consuming, but very helpful.

**Comment by cprudhom** [comment]
Automatic solution recording is still available.
