### ISSUE TITLE
Refactor factories

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#372]
There are many factories and finding the right element becomes difficult. 
To solve this issue, we propose to use the following factories:

**Vars** : to declare all variables (merges VF and VariableFactory)
**Cstrs** : to declare all constraints (merges ICF, IntConstraintFactory, LCG, LogicalConstraintFactory, SCF, SetConstraintFactory) 
**Search**: to declare how to explore the search space (merges ISF, IntStrategyFactory, SSF, SetStrategyFactory, RSF, RealStrategyFactory, SearchMonitorFactory, SearchLoopFactory, LNSFactory)

**Comment by cprudhom** [comment]
What about SatFactory ?

**Comment by jgFages** [comment]
The objective is that SatFactory is only used internally (i.e. inside the methods of Cstrs)
and the "lambda" user should need to access it directly.

**Comment by jgFages** [comment]
ok, to go deeper, we now plan to put all factories directly accessible from Solver 
e.g. 
solver.makeIntVar
solver.makeAllDifferent
etc.

**Comment by arnaud-m** [comment]
Hello,

It was the case in Choco2 and it was a very messy at the end !
I would prefer the first solution with three main factories. 

Cheers.

**Comment by jgFages** [comment]
The idea is actually to somehow keep the three main factories, but to move from static method to default implementation of an interface (Java8) so that Solver can inherit from the three factories. 

So from a maintenance point of view, code is separated.
From a user point of view, it is possible to use everything in the solver but also to use the factories (although no longer in static access).

Does it suit you?

**Comment by cprudhom** [comment]
Maintaining jdk7 will become even harder (but, that's another story)

**Comment by arnaud-m** [comment]
The architecture looks sounds, but I believe that the user is disturbed when a class offers too many methods. Since I am a new user of Choco3, I have found that the factories were an improvement over Choco 2.

Take also a look at some competitors : [IloOplModel](http://127.0.0.1:40933/help/index.jsp?topic=%2Filog.odms.cplex.help%2Frefcppcplex%2Fhtml%2Fclasses%2FIloOplModel.html%3Fresultof%3D%2522%2549%256c%256f%254f%2570%256c%254d%256f%2564%2565%256c%2522%2520%2522%2569%256c%256f%256f%2570%256c%256d%256f%2564%2565%256c%2522%2520l) and [ISolver](http://www.sat4j.org/maven23/org.sat4j.core/apidocs/org/sat4j/specs/ISolver.html)

**Comment by jgFages** [comment]
Well, it seems the competitors put (almost) everything in the solver (see CPO java API, Cplex Java API and Sat4J). I will do my best to keep things easy to understand and provide something to feed the discussion. The other factories will be maintained so they will be no backward compatibility issue.

**Comment by fhermeni** [comment]
In my opinion, the factories should stay outside the solver because they are not specific to a given solver.
Each method added into the solver reduces the flexibility because it becomes a huge class that cannot be derived.

Have a look at this principle for example: https://en.wikipedia.org/wiki/Interface_segregation_principle <https://en.wikipedia.org/wiki/Interface_segregation_principle>

> Le 3 févr. 2016 à 18:31, Jean-Guillaume Fages <notifications@github.com> a écrit :
> 
> Well, it seems the competitors put (almost) everything in the solver (see CPO java API, Cplex Java API and Sat4J). I will do my best to keep things easy to understand and provide something to feed the discussion. The other factories will be maintained so they will be no backward compatibility issue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/chocoteam/choco3/issues/372#issuecomment-179363402>.
> 

---
Fabien Hermenier
Associate Professor SCALE Project, University of Nice-Sophia Antipolis
http://fhermeni.github.io

**Comment by jgFages** [comment]
I am not sure to understand. When creating a variable, you have to specify the solver as an argument, so in my understanding, it is specific to a given solver. Can you explain what you mean by not specific?

About the segregation principle, do you mean it would be inconvenient if someone wants to create a new solver class that uses only boolean variables? So the user does not want to have methods related to other variables kinds? If so, do you mean it was (somehow) wrong to add methods such as 
retrieveIntVars, retrieveBoolVars, retrieveSetVars in the solver class?

**Comment by fhermeni** [comment]
> Le 3 févr. 2016 à 19:13, Jean-Guillaume Fages <notifications@github.com <mailto:notifications@github.com>> a écrit :
> 
> I am not sure to understand. When creating a variable, you have to specify the solver as an argument, so in my understanding, it is specific to a given solver. Can you explain what you mean by not specific?
> 
Not specific to a given implementation.

> About the segregation principle, do you mean it would be inconvenient if someone wants to create a new solver class that uses only boolean variables? So the user does not want to have methods related to other variables kinds? If so, do you mean it was (somehow) wrong to add methods such as retrieveIntVars, retrieveBoolVars, retrieveSetVars in the solver class?
> 
> 
If he wants to provide a new solver for booleans only stuff, his class will be full off empty class throwing UnsupportedOperationException for example which reveal kind of a architectural problem.

In fact, I like the current approach of having the factories outside the Solver object.
It is just a bit disturbing to have multiple static classes when we are browsing the documentation.
 Especially, the split between the variables and the constraints for example as, as far as I remember, offseted variables can be considered as a variable wrapped with kind of a constraint. So the frontier might be thin at some places.

**Comment by jgFages** [comment]
Ok my example was stupid. Booleans, Integers, Sets, Reals and all choco-solver constraints are in the core of choco and it makes no sense trying to remove part of it. Choco solver should be considered as an atom. What is considered as "segregable" is put in extensions of choco-solver. This is the case of choco-graph that provides graph variables and graph constraints. If we move the factories in the solver, I could update the choco-graph project with a GraphSolver extends Solver implements GraphVariableFactory, which would include the methods to build graph stuffs if you see what I mean...  So the classic Solver of choco will not include graph constraints. This would satisfy the segregation principle, right?

Back to the factories: 

We want the user to have only one entry point to setup his model but we want the code to be split into different parts (for maintenance purpose). This is why we are thinking of using interfaces with default implementation : you can have multiple inheritance, which is not possible using static methods (Having one big factory with hundreds of static constraints is not an option). The counterpart is that you need to create one object. That object could be either the Solver or a new object that we could call Modeler.

What bothers me with having an external object is that:
1) I find a pity to create a new class in the source and a new line to each model while the Solver could do the job and will be created for sure anyway.
2) If you create a Modeler, you have to pass it the solver anyway.
3) If you have both the solver and the modeler, the frontier will remain thin : where to put time limits, logging, search strategies, etc?

**Comment by cprudhom** [comment]
Maybe an alternative could be to integrate some factories (vars and cstrs) in the solver.
The solver could provide two additional methods: `solver.varMaker()` and `solver.cstrMaker()` which bind respectively to VF and ICF/SCF/... (with adoption of the API, to avoid always having to set the solver).
That alternative limit the API of `Solver`, avoid having tons of static methods not overridable, and consulting the API of Solver is self-content for modeling purpose (no need to know VF and ICF...).

**Comment by arnaud-m** [comment]
It is funny because it was again an issue with Choco2 where the model and solver were separated.
It allowed to easily use reformulation or to build portfolio, but it was painful because there were too much redundancies between the two layers.

From my personal point of view, I can live very well with 3 factories that can be overriden to extend/restrict features. I even find it helpful, because I can easily focus on a component of the solver (variables/ constraints/ search). 

I agree that everything is in the solver in SAT4J, but it is easier to do with SAT.
However, I believe that there are at least three layers in Ilog (data, model, search factory).

**Comment by cprudhom** [comment]
Yes, you are right, and we discussed that point with JG.
But, I eventually think that the two approaches are different.
In Choco2, we wanted to have a separation between modeling and solving.
Consequently, we created 2 objects one for each purpose, but it forces to convert model's objects into solver's objects.Thus, variables and constraints co-exist in the two objects, which was very confusing, from user point of view, and the major drawback of this approach.
In this proposal, the purposes are kept distinct, we simply want to ease modeling by grouping variable and constraint creation close to the solver.
The solving part is more related to the search loop, and we can consider copying the main principle to the search loop object.

**Comment by jgFages** [comment]
Ok I have created an IModeler interface to build variables, views and (todo) constraints. So you can build variables like this:

RealVar z = solver.realVar("z", -1.0e8, 1.0e8, 0.1);
IntVar x = solver.intVar("sum", 12, 19);
SetVar s = solver.setVar("s", new int[]{2}, new int[]{2,1,3,5,7,12});

Isn't it more convenient?

For now solver implements IModeler but it is possible to put it as an instance variable which would lead to: 

RealVar z = solver.getModeler().realVar("z", -1.0e8, 1.0e8, 0.1);
IntVar x = solver.getModeler().intVar("sum", 12, 19);
SetVar s = solver.getModeler().setVar("s", new int[]{2}, new int[]{2,1,3,5,7,12});

I would prefer avoid such indirections that make the model verbose but it is possible

**Comment by arnaud-m** [comment]
Yes, the first one is better ;)

**Comment by cprudhom** [comment]
BTW, keep in mind, while refactoring, the [following rules](https://javax0.wordpress.com/2014/02/05/use-java-annotation-deprecated-the-right-way/).

**Comment by cprudhom** [comment]
This was the main objective of version 4.0.0. Now done in the current branch.
