### ISSUE TITLE
Constraint.reif() in code vs. Constraint.reify() in documentation

### ISSUE THREAD

**Issue by 0x203** [chocoteam/choco-solver#373]
Just stumbled about this:
In [the Documentation](https://github.com/chocoteam/choco-solver/blob/master/docs/source/2_modelling.rst#reifying-constraints) a method `reify()` is described. However, in [the code](https://github.com/chocoteam/choco-solver/blob/master/choco-solver/src/main/java/org/chocosolver/solver/constraints/Constraint.java#L166) the actual method is called `reif()`, **without y**.

For me it seems like `reify()` with the `y` is correct. Am I missing something? The code change would be minimal (I think), but I'm afraid this affects the public API so I'm not sure how to deal with that in a good way.

**Comment by jgFages** [comment]
It is a typo. reif() and reify() denote the same thing so you can use it with no worry. 
We will use the term "reify()" in the next release.
