### ISSUE TITLE
simpler SetVars

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#374]
SetVar domain will be accessible in a simpler way using

public ISet getLB() and public ISet getUB();

This means you can iterate over integers in the envelope of x doing this:

for(int i:x.getUB()){
...
} 

Note these ISet are read-only. 
To filter the domain of the variable, use:
x.force(42, aCause) to add 42 in x's kernel
x.remove(42, aCause) to remove 42 from x's envelope

**Comment by cprudhom** [comment]
Done in 25c6fff3e95b85ce152dcdf5f1849cbd013eee46
