### ISSUE TITLE
simpler iteration over ISet objects

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#375]
ISet now implements Iterable<Integer>, meaning you can use loops of the form
for(int i:mySet){
...
}
Note that you can modify the set while iterating over it:
- If you add, you may or may not have it in the current iteration (the set is not ordered so we do not know in which 'position' it is added
- If you remove an element, you will not have it in your current iteration

Note also that, while it gives a nicer code, it uses auto-boxing which slightly decreases performances. Therefore, we recommend using it with caution

**Comment by cprudhom** [comment]
Done in 25c6fff3e95b85ce152dcdf5f1849cbd013eee46
