### ISSUE TITLE
IntVar implements Iterable<Integer>

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#376]
IntVar now implements Iterable<Integer>, meaning you can enumerate domain values using the following loop:

for(int i:myIntVar){
...
}

Note also that, while it gives a nicer code, it uses auto-boxing which slightly decreases performances. Therefore, we recommend using it with caution (maybe not inside a filtering algorithm)

**Comment by glelouet** [comment]
you can use intStream instead if you want to avoid auto-boxing. Example :

IntervalIntVarImpl
```
    public IntStream sValues() {
    	return IntStream.range(LB.get(), UB.get());
    }
```

BitsetArrayIntVarImpl
```
    public IntStream sValues() {
    	return IntStream.range(LB.get(), UB.get()).map(idx->VALUES[idx]);
    }
```

FixedIntVarImpl
 ```
   public IntStream sValues() {
    	return IntStream.of(constante);
    }
```

I'm not sure for BitSetIntVarImpl, but
```
    public IntStream sValues() {
    	return IntStream.range(LB.get(), UB.get()).filter(v->VALUES.get(v-OFFSET));
    }
```
May be correct ?

Intview should directly use the backend IntVar and map it.

**Comment by cprudhom** [comment]
Done in 406d074d41d5f44264808644ce296b73fcce65ff
