### ISSUE TITLE
postNogood() in LearnCBJ does not work

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco-solver#377]
Hey @cprudhom, @jgFages, 
In 3.3.3 (and I can see that it is the same in develop branch) activating nogoodFromConflict in CBJ does not work, I think the problem is because the `lastExplanation` is never complete because in `Explanation`, line 197 `isComplete()` checks if `rules == null`, however, in the construction of each explanation (line 95) rules are created. I guess that the test should be `rules != null`, right? 
Best

**Comment by chocotrust** [comment]
I'll check this out asap, but, thank you for the bug report.

**Comment by cprudhom** [comment]
You're right, I'll fix it in the develop branch !

**Comment by cprudhom** [comment]
Done in commit 82f1c25bb5a209fdd3f5dcd0aa5dc9454be594fe
