### ISSUE TITLE
Bug in cost-regular propagation when using « pre instanciated » variables ?

### ISSUE THREAD

**Issue by bebui** [chocoteam/choco-solver#379]
Hi, 

If I'm not mistaken, there might be a bug in the propagation of cost-regular under certain circumstances.
If I post a very simple simple cost-regular constraint (one state, two variables) with a arithmetic constraint, then it appears that the event from the aritchmetic constraint is not propagated.
(Only branching on automaton variable (i.e. not the cost), which should be enough to infer the cost value)

Attached  the minimal example I could make.

Regards,

Julien
[Debug.java.zip](https://github.com/chocoteam/choco-solver/files/184958/Debug.java.zip)

**Comment by cprudhom** [comment]
The two events (related to x[0] wrt arithm and x[1] wrt the decision) are correctly caught by the CR propagator. 
I believe that there is a bug in the `initialize()` method. I'll try to figure it out.

**Comment by bebui** [comment]
Do you happen to know when the fix might be available ?

**Comment by jgFages** [comment]
Hi I have got the following output:
Solution : true
x[0] = 1 x[1] = 0 | c = 1

What is the expected output?

**Comment by bebui** [comment]
Can't see J-G post anymore, the variables were not being instantiated, with choco 3.3.3
BR
Julien

**Comment by jgFages** [comment]
Thanks! 
I removed my post when I saw Charles has already fixed the issue in the develop branch. 
So I believe your question was : when will the next release be done? 
We still need a bit of time to make it stable and update doc but it should not be too long.
