### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/choco-solver#382]
Hello Everyone,

The test suite takes a very long time. It has started since more than 1 hour and it is still running on my laptop.
Is there a way to execute a relevant subset of test through within  a reasonable time ?

Thank you.
Arnaud

**Comment by jgFages** [comment]
Hi Arnaud,

Each test is associated with a group "1s", "10s" or "5min" that gives an upper bound of the test runtime. So you can ask to run only tests of group "1s" with mvn test -Dgroups="1s"
You can also completely skip tests when compiling sources using : mvn clean install -DskipTests
By the way, it takes 50minutes on my computer so it should finish soon.

**Comment by arnaud-m** [comment]
Thanks Jean-Guillaume ! That's what I was looking for.

`mvn test -Dgroups="1s"`

A few tests took more than 1 second. 

- testcase name="test2" time="22.149" classname="org.chocosolver.memory.DynamicAdditionTest"
- testcase name="test3" time="17.967" classname="org.chocosolver.solver.explanations.ExplanationEngineTest"
- testcase name="test2B" time="36.092" classname="org.chocosolver.solver.constraints.nary.ClauseChannelingTest"
- testcase name="test2E" time="44.616" classname="org.chocosolver.solver.constraints.nary.ClauseChannelingTest"

I use openjdk version "1.8.0_72".

**Comment by arnaud-m** [comment]
`mvn test -Dgroups="10s"` fails on Fedora 22 + OpenJDK.
See [test_error.txt](https://github.com/chocoteam/choco-solver/files/200521/test_error.txt).

**Comment by jgFages** [comment]
We have updated the tests suite in the develop branch so you should no longer have such gap in runtime. By the way, contrary to what I said above, the third group is not "5min" but "5m".

About the JRE fatal error encountered on Fedora, I have no idea where this come from. 
Can you identify which test causes this error?

**Comment by fhermeni** [comment]
On My side (osx), I have JVM crashes while testing BtrPlace when jacoco is enabled. You might be in the same situation.

> Le 2 avr. 2016 à 12:10, Jean-Guillaume Fages <notifications@github.com> a écrit :
> 
> We have updated the tests suite in the develop branch so you should no longer have such gap in runtime. By the way, contrary to what I said above, the third group is not "5min" but "5m".
> 
> About the JRE fatal error encountered on Fedora, I have no idea where this come from. 
> Can you identify which test causes this error?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/chocoteam/choco-solver/issues/382#issuecomment-204687383>

---
Fabien Hermenier
Associate Professor SCALE Project, University Nice Sophia Antipolis
http://fhermeni.github.io

**Comment by arnaud-m** [comment]
I did not activate jacoco by myself. 

By looking at the attached error log, I suppose that the failed test follows : org.chocosolver.solver.constraints.nary.BottleneckTest.testStynes2 SUCCESS (11975ms).

Are you using sun jdk or open jdk ?

**Comment by fhermeni** [comment]
Look at your log. It is activated by default.
I am using the sun jvm. I had big perf issues with openjdk

Sent from a mobile, so with a ton of auti completion fails.




On Sat, Apr 2, 2016 at 5:29 AM -0700, "Arnaud Malapert" <notifications@github.com<mailto:notifications@github.com>> wrote:


I did not activate jacoco by myself.

By looking at the attached error log, I suppose that the failed test follows : org.chocosolver.solver.constraints.nary.BottleneckTest.testStynes2 SUCCESS (11975ms).

Are you using sun jdk or open jdk ?

-

**Comment by arnaud-m** [comment]
To conclude 

```
$ java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b14)
OpenJDK 64-Bit Server VM (build 25.101-b14, mixed mode)

$mvn test -Dgroups="1s"  -Djacoco.skip=true
...
...
Tests run: 1840, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:report (report) @ choco-solver ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.650 s
[INFO] Finished at: 2016-09-12T16:01:42+02:00
[INFO] Final Memory: 27M/433M
[INFO] ------------------------------------------------------------------------

```
