### ISSUE TITLE
[request] [choco4] add findOptimal in Model.

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#386]
I understand that using this function with modification of the model may lead to bad behaviour, however this is a simple use case that should IMO be of very simple use. I fear people (including me :( ) will need to rewrite this small part of code on several places otherwise.

add (…keep) a method in Model  :

```java
public Solution findOptimum(IntVar objective, boolean maximize){
  setObjective(maximize?ResolutionPolicy.MAXIMIZE:ResolutionPolicy.MINIMIZE, objective);
  Solution s = new Solution(this);
  while (solve()) {
    s.record();
  }
  return getSolver().isFeasible() == ESat.TRUE ? s : null;
}
```

**Comment by cprudhom** [comment]
Well, that's not the point at all, since we want the user to be aware of what was done on his back.
However, we certainly write a short reference guide which list the most used methods.

**Comment by cprudhom** [comment]
What about adding a resolution helper ?
The resolution processes will still be disconnected from the model (solver) but the code will not be lost.
That may also ease capitalizing on tricky resolution process.

poll: 👍 / 👎

**Comment by cprudhom** [comment]
👍

**Comment by arnaud-m** [comment]
Nice. I support this solution !

**Comment by cprudhom** [comment]
I initialized a class, namely `IResolutionFactory` and added 5 methods, IMO the most commonly used.
If one wants to add new methods, please upgrade the class and push a request.

**Comment by glelouet** [comment]
I think this should be called a resolutionHelper because it is not
something that builds elements of a model following an internal strategy (a
factory)

I thus propose
 - to name it ResolutionHelper ;
 - to set it to a class ( the idea is singleton but useless code for strict
singleton as we don't need to ensure there is only one of those in the
classloader ) ;
 - to set the methods static instead of default .

about the methods
 - List<Solution> findAllSolutions() should IMO return a stream. I can
propose a modification if you agree with that.
 - same for findAllOptimalSolutions

The idea is that stream can easily be converted to list and thus avoid
finding all solutions when we want a specific one.
  ```Stream.of(new Object()).collect(Collectors.toList());```

2016-04-25 12:51 GMT+02:00 cprudhom <notifications@github.com>:

**Comment by glelouet** [comment]
I think this should be called a resolutionHelper because it is not something that builds elements of a model following an internal strategy (so not a factory)

I thus propose

 - to name it ResolutionHelper ;
 - to set it to a class ( the idea is singleton but useless code for strict singleton as we don't need to ensure there is only one of those in the classloader ) ;
 - to set the methods static instead of default .


about the methods
 - List<Solution> findAllSolutions() should IMO return a stream. I can propose a modification if you agree with that.
 - same for findAllOptimalSolutions

The idea is that stream can easily be converted to list and thus avoid finding all solutions when we want a specific one.
`Stream.of(new Object()).collect(Collectors.toList());`

**Comment by cprudhom** [comment]
I agree too.
I think we should not provide a solution iterator, since it may be problematic for the user to distinct COP from finding all solutions from a CSP.

**Comment by glelouet** [comment]
summing up discussion : static is not good for @cprudhom for modeling reason (should be integrated in Solver) ; for this reason the first part of my previous message is bad (static etc.)

**Comment by glelouet** [comment]
adding also an empty interface for Measures(to be filled later) and following methods :
``` eachWithMeasures(BiConsumer<Solution, Measures>);```
for iteration of solutions and 
```eachWithMeasures(Bicosumer<Solution, Measures>, IntVar, boolean)```
for iteration over optimal solutions

**Comment by glelouet** [comment]
also to add optionnal criterions to the exploration.

**Comment by glelouet** [comment]
#394

**Comment by glelouet** [comment]
sorry for bad indentation :(

**Comment by jgFages** [comment]
Shouldn't the ResolutionHelper be in Solver rather than Model?
