### ISSUE TITLE
solver is not stopped by Thread.interrupt() method

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco-solver#388]
When a solver thread is running in some thread pool, support for java way of stopping a thread should be implemented. For example when a thread pool is shutdown.

I think good place to check whether thread is interrupted is SearchLoop.launch method. In do-while loop it can be checked by Thread.isInterrupted() and in case it is true, the code when criteria are met can be reused.

**Comment by cprudhom** [comment]
Can you pull a request ?

**Comment by gregy4** [comment]
Yes, a moment ago I created pull request with one line change of code in develop branch.

**Comment by cprudhom** [comment]
See #393
