### ISSUE TITLE
InputOrder efficiency

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#390]
Hi

In the good ol' days, InputOrder tracked the last instantiated variable to avoid iterating over variables already instantiated.

I have a list of 90000 variables and InputOrder.getVariable() is taking 61.2% of my solving duration :D

**Comment by jgFages** [comment]
done!

**Comment by gregy4** [comment]
I think some note about repeating iteration over decision variables would be helpful in user guide. When number of variables increases, it is highly probable that a user uses its own search strategy and a code from predefined search strategies isn't used.

**Comment by cprudhom** [comment]
You're probably true, what do you suggest ?

**Comment by cprudhom** [comment]
The `AntiFirstFail` variable selector can be adapted too.
