### ISSUE TITLE
Tuning the TrailingEnvironment

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#397]
One the biggest problems I am dealing with, resizing the stack is the hot CPU path:
12,1% - 2 702 ms org.chocosolver.memory.trailing.trail.flatten.StoredIntTrail.resizeUpdateCapacity

It would be great to be able to customize the initial stack size and the growing factor to tune the solver when needed

**Comment by fhermeni** [comment]
I planned to extend it for customization but it is final so it limits the possibility to play with it properly

**Comment by cprudhom** [comment]
To allow anybody tuning it, I suggest to externalize its configuration.

**Comment by fhermeni** [comment]
In details, it would be great to be able to indicate a specific trail size per variable or backtrackable stuff.

In my case, at least when I do `getEnvironment().makeInt()`, I would be able to set somewhere the initial size of the backed array.

**Comment by fhermeni** [comment]
You can simplify EnvironmentTrailing now I guess ? It still proposes its default values while the builder takes care of that properly now.

**Comment by cprudhom** [comment]
Sure. I'll do it

**Comment by jgFages** [comment]
Hi Fabien, any feedback about the different environment performances on your benchmarks?

**Comment by fhermeni** [comment]
it works well on my case.
I am waiting from some support from @cprudhom about a method I cannot implement

**Comment by jgFages** [comment]
I have completed EnvironmentBuilder so that it is easier to test the CHUNK, FLAT and UNSAFE implementation: ::

Model model = new Model(EnvironmentBuilder.buildChunkEnvironment(),"");

Could you test the three alternatives?

**Comment by fhermeni** [comment]
What I  did with Charles is a custom chunk environment. 
I cannot test your code in develop because I am currently running with the released version of Choco and the APIs are incompatible

**Comment by jgFages** [comment]
ok

**Comment by cprudhom** [comment]
See #397, #405 and #421
