### ISSUE TITLE
present SetVar.cardinality() as an IntVar

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#403]
Though there is a way to assign the cardinality of a SetVar to an IntVar( namely PropCardinality ), there is no specific "card" variable as an attribute of a SetVar.

This can lead to several times the same propagator being used.

I propose to add a field and two methods in SetVar, with the same idea as reify() for constraints:
 - [IntVar card] is the Variable related to the cardinal of the SetVar, is null if not necessary.
 - [IntVar card()] creates the card and post a propagator if the card is null ; and return the card
 - [void cardIs(IntVar var)] assign card:=var and post a propagator if null ; or post an equality propagator var==card if not null.

**Comment by jgFages** [comment]
I like it

**Comment by glelouet** [comment]
Charles told me to do it.
https://github.com/chocoteam/choco-solver/pull/407
