### ISSUE TITLE
create constant SetVar from range

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#411]
The goal is to create quickly a constant set for the user. 

in IVariable factory

Version 1 makes a fixed set
```
    /**
     * Creates a constant set variable, equal to <i>{min..max}</i>
     * @param name the name of the variable
     * @param min minimum value to contain
     * @param max maximum value to contain
     * @return a new SetVar with set equal to min..max. If max &lt; min return an empty SetVar
     */
    default SetVar setVarOver(String name,int min, int max) {
    	return setVar(name, IntStream.rangeClosed(min, max).toArray());
    }
```

Version 2 with boolean to specify whether it is constant or not.
 ```
  /**
     * Creates a set variable, containing at most <i>{min..max}</i>
     * @param name the name of the variable
     * @param constant if true {min..max} are contained in the SetVar ; if false those values CAN be contained.
     * @param min minimum value to contain
     * @param max maximum value to contain
     * @return a new SetVar with UB equal to min..max ;
     * If max &lt; min return an empty SetVar ; if constant then UB=LB, else LB is empty.
     */
    default SetVar setVarOver(String name,boolean constant, int min, int max) {
    	 return constant ?
    			 setVar(name, IntStream.rangeClosed(min, max).toArray())
    			 :setVar(name, new int [] {},IntStream.rangeClosed(min, max).toArray());
    }
```

**Comment by jgFages** [comment]
You are aware that you cannot use setVar(String name, int... values) anymore?
What do you prefer between setVar(String name, int... values) and setVar(String name, int min, int max) ?

**Comment by glelouet** [comment]
> You are aware that you cannot use setVar(String name, int... values) anymore?

how that ?

>  What do you prefer between setVar(String name, int... values) and setVar(String name, int min, int max) ?

I don't get your point, and think we should discuss it.

**Comment by jgFages** [comment]
Well, if I put setVar("", 2,5), will it be {2,5} or [2,5]?

**Comment by glelouet** [comment]
I named my function setVarOver, not setVar, because I use a range.

**Comment by jgFages** [comment]
My mistake!

**Comment by jgFages** [comment]
all variables are created using intVar, setVar realVar, etc. so I do not want to insert a different method name such as setVarOver. 

Is ``setVar(name, ArrayUtils.array(min, max))`` satisfying?
Or ``setVar(name, IntStream.rangeClosed(min, max).toArray()) ``

**Comment by JLiangWaterloo** [comment]
@jgFages 

> Is setVar(name, ArrayUtils.array(min, max)) satisfying?
> Or setVar(name, IntStream.rangeClosed(min, max).toArray())

I've ran into memory issues many times with this before since I'm often working with very large sets.

Consider these two snippets of pseudocode:

1.
```java
public static SetVar setVar(String name, int[] env) {
    BitSet lb = new BitSet(...);
    BitSet ub = new BitSet(...);
    for (int e : env) ub.add(e);
    return new SetVar(lb, ub);
}
```

2.
```java
public static SetVar setVar(String name, int envMin, int envMax) {
    BitSet lb = new BitSet(...);
    BitSet ub = new BitSet(...);
    for (int e = envMin; e <= envMax; e++) ub.add(e);
    return new SetVar(lb, ub);
}
```

If I wanted to create a SetVar containing values between 1 and 1,000,000 then
1. For the first approach I would need to create an int[] of size 1,000,000 first which will cost 32*1,000,000 bits of memory.
2. For the second approach, the array is not needed and I only need to create the Bitset costing 1,000,000 bits of memory.

I've had many cases where this 32X difference caused my program to run out of memory.

My 2 cents.

**Comment by jgFages** [comment]
Thank you jimmy. However, this is yet another concern. For memory optimization, I prefer to add the following constructors to SetVarImpl: ::

public SetVarImpl(String name, ISet lb, ISet ub, Model model) 

public SetVarImpl(String name, ISet value, Model model)  (for fixed sets)

PROS:
- Avoids loosing memory in arrays (you create the BitSet implementation directly)
- Generic (ub does not have to be a complete range and it deals with the lb as well). 

CONS:
- It may be dangerous that the user has access to the variable domain (at least for beginners).

Perhaps this should be a public constructor but not ported to the factory (usual users keep using model.setVar and advanced users can use the constructor directly)?

**Comment by JLiangWaterloo** [comment]
@jgFages 
I'd be happy with that :+1:

**Comment by jgFages** [comment]
The memory optimization is done with the new constructor. 
For the modeling perspective, setVar(name, ArrayUtils.array(min, max)) is short enough
