### ISSUE TITLE
NameManager in Model

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#412]
## Issue

Now the names of variables and constraints are only a potential tool for users. They are either
- specified by the user, 
- or created with randomName().

The first use makes the user able to define two times a variable named "a", and thus two variable named "a²" constrained to timesxyz(a,a,a²).
This is a feature but could also raise a warning to help users know when they declare a variable with same name twice.

The second use leads to something like 
`(a==b) XOR (a==c)`
implemented with 
`arithm(a, "=", b).reifywith(arithm(a, "=",c).reify().not)`
showing debug lines like 

> TMP_1=0, TMP_2=1
## Proposal

I propose to have a optional name manager in the Model.
- store the names of every constraint created in the model
- create variables on request with names corresponding to their role
- store links to variables linked by equality, in order to only print those variables once on debugging.

The default name manager would have the same behavior as choco has now, to avoid memory footprint and warnings.
## Limits

I don't think this can easily be performed without a bit of refactoring.
This is more a basis of discussion than a real implementation proposal, as the necessary modifications may break some behaviors.

**Comment by jgFages** [comment]
It could help a little (if you have thousands of variables even a good name will not be sufficient to debug easily) but, in my opinion, the trade-off between work and benefit is poor so I won't do it :-) 
We can wait a little to see if someone wishes to do it. 
Otherwise, perhaps we should close that PR.

**Comment by cprudhom** [comment]
I think it should be in plug-in project, since it seems to be a labyrinthine system to me.
