### ISSUE TITLE
Using OptionalInt in Solution

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#414]
Maybe we should consider using `OptionalInt` instead of returning `null` in `Solution.getIntVal(IntVar)`.

More details about [Optional](http://www.javaspecialists.eu/archive/Issue238.html).

**Comment by glelouet** [comment]
I think a Solution should only be created when all the variables of the problem are instantiated. If a solution has no value for a variable, either the solution is not a correct one or the variable is not part of the model. In any case, this should return an exception IMO.

**Comment by jgFages** [comment]
I find the OptionalInt a bit heavy.

I suggest to return directly an int (not an Integer) but to throw an exception if:
- No solution has been recorded
- The variable has not been declared to be recorded
As long as the exception message is clear enough, I find it satisfying. 

Vote?

**Comment by jgFages** [comment]
done!
