### ISSUE TITLE
Weak filtering for atLeastNValues (ad hoc)

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#419]
```java
 @Test(groups="1s", timeOut=60000)
    public void testAtLeastFixed() {
        Model model = new Model();
        final IntVar[] XS = model.intVarArray("XS", 6, 0, 5, false);
        final IntVar N = model.intVar("N", 6);
        model.atLeastNValues(XS, N, false).post();
        model.getSolver().showStatistics();
        model.getSolver().showDecisions();
        model.getSolver().solve();
        Assert.assertEquals(model.getSolver().getBackTrackCount(), 0);
    }
```
I added other test files to the test suite (see develop branch).

**Comment by jgFages** [comment]
I do not see the problem. 
This configuration is not supposed to perform AC. 
We could try to add even more add hoc rules but I am not sure it would be a good thing because it would grow the had oc part : If more filtering is needed then I would recommend to use the AC option

**Comment by cprudhom** [comment]
Well it doesn't filter anything, it is a simple checker in that case. 
Maybe we should either improve it or double it with AC prop applied randomly to capture those cases.

**Comment by jgFages** [comment]
ok, I am on it

**Comment by jgFages** [comment]
I added a simple rule : when an alldiff is required over uninstantiated variables (n = number of uninstantiated variables), then remove from the domain of those variables values that are already taken by instantiated variables. 

The code change is not important and performance is much higher (enough to get 0 backtrack on your test although it does not apply alldiff AC). 

We could also add more filtering by calling AC times to times but this would become heavier to configure and I am not sure it is worth. I suggest to wait a practical application where it is needed, agreed?
