### ISSUE TITLE
Constraint.reif(), LogicalConstraintFactory, and automatic naming

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#420]
I have a CSP with a lot of reified constraint. 
The current hotspot (8% of my computation time) is StringUtils.randomName() that is called from Constraint.reif() and LCF.or().

It would be great to have an API where I can provide my own string label to prevent from that overhead.

**Comment by jgFages** [comment]
You are incredible! 
This method returns  "TMP_" + next++; 
I can't imagine how you can solve anything considering that this simple line consumes time! 
Would passing "TMP_42" directly be much faster?

**Comment by fhermeni** [comment]
The underlying problem is solved in 20 seconds so it is ok. 
I am not against an automatic labelling but put aside a call when I can specify my label.

In practice, the label will be "" if I am in production mode, or the label I generate when running in debug mode.

**Comment by jgFages** [comment]
Ok, well you can do it already by replacing constraint.reif() by constraint.reifyWith(BoolVar) and creating yourself the boolean variable (the factory allows you to specify a name directly)
Calling constraint.isReified() may help to know whether you need to create a new variable or not.

And the same for LCF.or(), which 
- reifies all variables
- posts an or constraint (sum >=1)
=> If you reify yourself these constraints it will be faster

Is that ok for you?

**Comment by fhermeni** [comment]
constraint.reifyWith(BoolVar) looks clean to me.
Ok for LCF.

**Comment by jgFages** [comment]
Good!
