### ISSUE TITLE
AbstractStrategy.getDecision() should return Optional instead of nullable Decision

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#422]
Currently, `AbstractStrategy.getDecision()` returns a `Decision<V>` which may be null.
If it is null, we consider that the strategy run dry and the next strategy should be called (or a solution has been found).
But, that would be better if a strategy returns `Optional<Decision>`, which avoid comparison with `null` and ease integration with lambda.

Look at the following ad hoc search:
```java
solver.set(SearchStrategyFactory.intVarSearch(
        variables -> {
            Optional<IntVar> selected =
                    Arrays.stream(variables)
                            .filter(v -> !v.isInstantiated())
                            .min((v1, v2) -> closest(v1, map) - closest(v2, map));
            return selected.isPresent() ? selected.get() : null;
        },
        var -> closest(var, map),
        myVars
));
```
where `closest` returns the distance to a target int.
I need to check the presence and return null when needed. If AbstractStrategy.getDecision() can deal with Optional, the code would be:

```java
solver.set(SearchStrategyFactory.intVarSearch(
        variables -> Arrays.stream(variables)
                            .filter(v -> !v.isInstantiated())
                            .min((v1, v2) -> closest(v1, map) - closest(v2, map)),
        var -> closest(var, map),
        myVars
));
```
That would ease specific search strategies.

**Comment by jgFages** [comment]
You don't need any modification, just add "orElse(null)" ::

        variables -> Arrays.stream(variables)
                            .filter(v -> !v.isInstantiated())
                            .min((v1, v2) -> closest(v1, map) - closest(v2, map))

becomes ::

        variables -> Arrays.stream(variables)
                            .filter(v -> !v.isInstantiated())
                            .min((v1, v2) -> closest(v1, map) - closest(v2, map))
			    .orElse(null)

I am not saying it is a bad idea to adapt variable selectors to Optional types, just that it does not depend on whether we use lambdas or not.

**Comment by cprudhom** [comment]
Thanks, I didn't that option existed. But I maintained that it would be nice to avoid returning null.

**Comment by jgFages** [comment]
What would the code look like with a "classical" (i.e. no lambda) implementation? 
Would InputOrder look like the following? 

public Optional<V> getVariable(V[] variables) {
        for (int idx = lastIdx.get(); idx < variables.length; idx++) {
            if (!variables[idx].isInstantiated()) {
                lastIdx.set(idx);
                return Optional.of(variables[idx]);
            }
        }
        lastIdx.set(variables.length);
        return Optional.empty();
    }

I hope there is a better way because this code gets just more complex without any benefit...

**Comment by cprudhom** [comment]
```java
@Override
    public V getVariable(V[] variables) {
        for (int idx = lastIdx.get(); idx < variables.length; idx++) {
            if (!variables[idx].isInstantiated()) {
                lastIdx.set(idx);
                return variables[idx];
            }
        }
        lastIdx.set(variables.length);
        return null;
    }
```

That's clearly not more complex, it is just that we are not used to `Optional` yet.
And I do not agree about the benefit: returning null is a bad hard-to-break habit : 
http://javablog.franksalinas.net/2010/06/09/avoid-returning-null/

**Comment by cprudhom** [comment]
Since 
- it should concern  `AbstractStrategy.getDecision()` too,
- `Optional.of(...)` create a new instance at each call and that decisions are critical wrt memory consumption (we use PoolManager for that purpose mainly)
- it dealing wit `null` is done internally by the Solver
the current use of returning null is maintained.
