### ISSUE TITLE
new constraint sumIf

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#423]
The purpose is to have a sum constraint that embeds a condition.
In my case, I have a large amount of assignment variables.
I want to sum their associated value iff they are assigned to a constant given as a parameter.

This constraint can be considered as a shortcut that prevents me from using a lot of reified constraints.
A drafty signature would be:

```
sumIf(IntVar[] vars, int[] vals, int def, int k)
```

 where `vars` are my assignment variables, `vals` the value to consider if the assignment equals `k` (`def` otherwise but in my case, it would be 0)

**Comment by jgFages** [comment]
It seems you need to count the number of variables assigned to k and then multiply it by k, right? 
Then I suggest to use a count constraint and a scaleView instead of adding a new constraint.

**Comment by jgFages** [comment]
Do you have this for many k? 
Like one k for each possible value in vars?

**Comment by cprudhom** [comment]
Still open ? I believe you add used a `occurrence` constraint and a `scalar` one ?

**Comment by cprudhom** [comment]
I assume this is outdated.
But if still relevant, feel free to re-open it.
