### ISSUE TITLE
Problems on Choco(Release 3.3.3)

### ISSUE THREAD

**Issue by siweisun** [chocoteam/choco-solver#426]
I try to use the Choco library () in my project.

Windows 7 (64-bit system), IDE(eclipse).

When I try to import the following:

import org.chocosolver.solver.Model;
import org.chocosolver.solver.Solution;
import org.chocosolver.solver.variables.IntVar;

It seems there is no org.chocosolver.solver.Model and  org.chocosolver.solver.Solution, but org.chocosolver.solver.variables.IntVar is OK.

What's wrong?  Thank you very much.

**Comment by jgFages** [comment]
This code is for Choco Solver 4.0
It is not compatible for choco solver 3.3.3
You can DL version 4.0 (alpha release) here: https://github.com/chocoteam/choco-solver/releases
