### ISSUE TITLE
Calling model.sum(BoolVar[], ...) should not be decomposed

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#430]
I think this should be optional and set to false by default.
Running this (I know it is an artificial example):
```java
Model m = new Model();
BoolVar row[] = m.boolVarArray("r", size);
m.sum(row, "<", 10).post();
m.getSolver().setSearch(Search.inputOrderLBSearch(row));
m.getSolver().findAllSolutions();
```
leaves no argument to decomposition:

size | decomp | no decomp
------------ | ------------- | -------------
21 | 2.736s | 1.744s 
22 | 3.738s | 2.681s 
23 | 6.466s | 4.374s 

Same goes when the constraint is reified:
```java
Model m = new Model();
BoolVar row[] = m.boolVarArray("r", size);
BoolVar b = m.boolVar();
m.sum(row, "<", 10).reifyWith(b);
m.getSolver().setSearch(Search.inputOrderLBSearch(row), Search.inputOrderLBSearch(b));
m.getSolver().findAllSolutions();
```

size | decomp | no decomp
------------ | ------------- | -------------
21 | 9.980s | 4.256s 
22 | 13.460s | 10.135s 
23 | 38.442s | 25.944s 
 
Same goes with smaller sizes (when incrementally is not activated).

Note: I got the same number of solutions and the same number of nodes.

**Comment by jgFages** [comment]
Makes sense to me as the purpose of the table decomposition is to provide AC, which we already have when variables are booleans.

**Comment by cprudhom** [comment]
table decomposition ? No, I'm talking about decomposition a sum over boolean into two constraints.
Eg: `m.sum(bs, ">", v)` becomes `m.sum(bs,"=", w) /\ m.arithm(w, ">", v)`
