### ISSUE TITLE
bug in scalar when using strict operators

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#431]
scalar(... > 8) autorizes a scalar equal to 7
> x is translated into >= x-1 instead of >= x+1
I fix it

**Comment by cprudhom** [comment]
Wtf !?!
Il est temps que j'arrête ...


Charles Prud'homme
--
Research engineer
Choco solver :
http://choco.emn.fr
Tel: +33 251 85 83 68

**Comment by cprudhom** [comment]
Strangely that was correct for sum (and tested)
