### ISSUE TITLE
[proposal] Objectify objective

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#436]
At the moment, we have several common use cases for choco :
- find a solution
- find all solutions
- prove there is no solution (which is, find a solution and show it does not exist)
- find a solution that maximizes a variable
- find a solution that minimizes a variable
- find a solution that maximizes/minimizes a variable within a given range
- find a solution that is lexically optimal wrt a vector of variables
- find all solutions that are the best wrt a variable and 
- find a paretto front according to a vector of variables
- find all paretto fronts

I may have forgotten some.
All those use case can be defined as strategies which
- observe all solutions found
- modify the problem according to the solutions already found (eg manage optimal constraint if searching for optimal)
- specifiy whether the search should stop after finding a solution
- make a restart when searching for all optimal solutions
- finaly, create the result of the search.

this would reduce our use case (findOptimal, findParetto, etc ) to ONE call search(Objective, Heuristic..) in the solver helper (handling multiple heuristics, as well as one or zero). Of course a first step would be to ADD the correct interface, the "search" call and deprecate the existing methods, then be sure this one method is enough ; adding an helper to allow easy use.

**Comment by jgFages** [comment]
I am not sure to see the benefit of this refactoring. I fear the code will be more complex for both the user and the developer. I you want to use the same entry point, you can already do everything with solver.solve().
