### ISSUE TITLE
Resetting the solver after finding optimal solutions

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco-solver#444]
Consider the following example:

```java
        Model m = new Model();
        IntVar i = m.intVar("i", 0, 5);
        Solver s = m.getSolver();
        System.out.println(s.findOptimalSolution(i, true));
        s.reset();
        System.out.println(s.findOptimalSolution(i, false));
        s.reset();
        System.out.println(s.findSolution());
```

This will print

```
Solution: i=5, 
Solution: i=0, 
null
```

The findSolution call failed even though the solver was reset?

**Comment by jgFages** [comment]
I will add a model.clearObjective() at the beginning of findSolution()
Thanks

**Comment by JLiangWaterloo** [comment]
I think reset should be calling model.clearObjective?

**Comment by jgFages** [comment]
I would say that this is a different debate. 

As findOptimalSolution sets the objective, it makes sense to me that findSolution and findAllSolutions make an objective clearance. As said in my commit post: For step-by-step
optimization, I recommend to use a while(solver.solve()) or to introduce a method called 
findImprovingSolution(). In particular, calling solver.findAllSolutions() with an objective variable makes no sense : should we compute all solutions or all optimal ones? 

solver.reset is supposed to focus on the solver object / the solving process.
The objective function is part of the model (although it also concerns the solver). 
Changing the objective function is changing the problem to be solved in a sense, which is something that I would not expect when calling the reset function of the solver. 

Does it make sense to you? I am open to discussion :-)

**Comment by JLiangWaterloo** [comment]
Makes sense. Thanks for the clarification.
