### ISSUE TITLE
StringUtil.randomName

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/choco-solver#452]
Hello, 

It is a detail, but the class BiArExpression generates names with a double underscore such as sum_exp__31.

Creating the same model/solver twice within a single execution leads to different variable names.
Is it possible to generate the same names ?

**Comment by cprudhom** [comment]
Ok for the double '_'.
About the name, I believe the seed that helps generating the number in the names are static. 
We can consider declare it in the solver instead.

**Comment by arnaud-m** [comment]
It would be nice

I use the variable name as its primary key to exchange messages between different solvers (possibly in different processes).

**Comment by arnaud-m** [comment]
Note that a similar feature is also offered by org.chocosolver.solver.Model.nextId().

**Comment by arnaud-m** [comment]
See also #412

**Comment by cprudhom** [comment]
Well, I can try to move the method from `StringUtils` (factory-like, with only static methods) to `Model`, for example, but I certainly won't go to such a  complex solution as a name manager.

**Comment by arnaud-m** [comment]
Yes, the NameMananger is too complex. I just wanted to outline a "similar" request. 

I would prefer unique variables names, but I can check the unicity by myself.
