### ISSUE TITLE
Prepare Measures/Objectives/Decisions for EPS 

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/choco-solver#454]
Some fixes, improvements and modifications coming from the implementation of Embarrassingly Parallel Search for Choco.

**Comment by arnaud-m** [comment]
A few questions arise while refactoring the objective manager.

What is the expected behavior of the SAT manager ? Actually it either [returns null](https://github.com/chocoteam/choco-solver/blob/master/src/main/java/org/chocosolver/solver/objective/BoundsManager.java#L171) or [raises an exception](https://github.com/chocoteam/choco-solver/blob/master/src/main/java/org/chocosolver/solver/objective/BoundsManager.java#L107).

I doubt that it is required to [check for null](https://github.com/chocoteam/choco-solver/blob/master/src/main/java/org/chocosolver/solver/objective/ObjectiveManager.java#L225) when updating the bounds.
Indeed, they are initialized in the constructor before the object becomes accessible.
I wonder if these lines do not come from older version.

**Comment by cprudhom** [comment]
It is designed to be the default implementation for satisfaction problem, so there is need to retrieve the best bound.
We wanted to define a unique entry point for the two major resolution types (CSP and COP).
This is not a class directly manipulated by users, that may explain why it became ugly :)

We are open to suggestions/modifications, but please avoid too much abstraction.
