### ISSUE TITLE
Filtering issue in `count`

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#469]
```java
Model model = new Model();

IntVar[] vars = model.intVarArray("var", 4, 0, 2);
IntVar occ = model.intVar("occ", 2, 3);
IntVar occ2 = model.intVar("occ2", 1, 2);

model.count(1, vars, occ).post();
model.count(0, vars, occ2).post();
while (model.getSolver().solve()) {}
```
with the default search strategy and any default settings.

In the PropCount_AC class, there is a little mistake which can lead to doing more steps and backtracks in the DFS than necessary.
The filter() method contains the following code:

```java
for (int j : possibles)
{
  if (vars[j].removeValue(value, this)) {
    possibles.remove(j);
  }
}
```
The removing of values can disturb the loop so the for loop ( here  is "that possible" ) will not iterate correctly. In this case, if this code is called the first time the following happens:

At the beginning the possibles list contains this {1,2,3}, j is 1 and the removal of value from vars[j] is successful. So the element j will remove from the "possibles" list, but this confuses the loop and leads to that j will not be set to 2 or 3. In other words, the for loop is only executed once.

This means that the Deep First Search will extend one unnecessary node or even more. Because it tries to assign a value to a variable , which will not be part of any solution. Besides, it causes extra backtracking step.

**Comment by jgFages** [comment]
This has already been fixed in commit number cc6fa23b849175c5c24f26fce06e0e73a298b1b4 of the 28/07/16 that removed auto-boxing code
