### ISSUE TITLE
Counting number of nodes should exclude solution

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#471]
In `Solver`, the `extend` case in `searchloop()` counts a node even if no extension is done:
```java
case extend:
    left = true;
    searchMonitors.beforeOpenNode();
    mMeasures.incNodeCount();
    if (!M.extend(this)) {
        action = validate;
    } else {
        action = propagate;
    }
    searchMonitors.afterOpenNode();
    break;
```

I suggest to not increment the number of nodes when a solution is found:
```java
case extend:                        
    left = true;                    
    searchMonitors.beforeOpenNode();
    if (!M.extend(this)) {          
        action = validate;          
    } else {                        
        mMeasures.incNodeCount();   
        action = propagate;         
    }                               
    searchMonitors.afterOpenNode(); 
    break;                          
```

**Comment by arnaud-m** [comment]
From my point of view, a solution is a leaf of the search tree.
An extreme case would be to have more solutions than nodes in the search tree.

But, what are doing other CP solvers ?

**Comment by cprudhom** [comment]
To be clear, when there is no more decision, a solution is found.
So, the last decision leads to that solution (implicitly), there is no reason to count another search node for that.

**Comment by jgFages** [comment]
+1

**Comment by arnaud-m** [comment]
As you want because, in most cases, it will not change much. 

However, it would break the backward compatibility and some unit tests (not only yours).

**Comment by jgFages** [comment]
Very good point arnaud!!!

**Comment by cprudhom** [comment]
Ok, so an alternative would to add a new API like `getDecisionsCount()` which returns the correct number of decisions taken so far, and to patch `getNodeCount()` so it returns `getDecisionsCount() + getSolutionCount()`.

(btw, shouldn't we add an 's' in 'getDecision**s**Count()' ?)

**Comment by jgFages** [comment]
I think there is no s

**Comment by arnaud-m** [comment]
OK for me.
