### ISSUE TITLE
Solver.reset() could also reset the ObjectiveManager

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#472]
Indeed, when dealing with a COP, the user has to manually call reset() and erase the strategy.
Would it be nice that, by default, the objective manager is reset too ?
+ javadoc is not up to date.

**Comment by JLiangWaterloo** [comment]
I had a conversation with @jgFages in https://github.com/chocoteam/choco-solver/issues/444 on this topic

**Comment by cprudhom** [comment]
I share the opinion of @jgFages about resetting the OM: calling reset on solver should not change the OM but simply reinitialize it.
In other words, nothing changes for CSP, but when dealing with COP, the best know value should be  erased.
