### ISSUE TITLE
IResolutionHelper.findAllSolutions

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/choco-solver#482]
Hello, 

All solutions are stored in a list. It can raise java.lang.OutOfMemoryError Exception. 
It is easy to fix, but I have lost one hours of computation time ! 

Best regards.

**Comment by arnaud-m** [comment]
Unfortunatly, the problem seems similar with streamSolutions.

**Comment by cprudhom** [comment]
If you don't want to keep all solutions, you should simply call the basic code:
```java
while(solver.solve()){
   // do something, like record solution, or nothing
}
``` 
as described in the [javadoc](http://www.choco-solver.org/apidocs/org/chocosolver/solver/search/IResolutionHelper.html#findAllSolutions-org.chocosolver.util.criteria.Criterion...-).

**Comment by jgFages** [comment]
Isn't it a confusion between findOptimalSolution and findAllOptimalSolution?

**Comment by arnaud-m** [comment]
Yes, there was a confusion in the issue title. 

I am sorry because I did not read the javadoc ;) 
So, I used 
`  model.getSolver().streamSolutions().count();`

Anyway, these functions should not throw exception as easily.
Before the search, I have no clues about how many solutions my model have.

**Comment by cprudhom** [comment]
What would you suggest ?
I never encountered such a case where the number of solutions were so important that a memory error was thrown. I'm not sure we can do lot of things after catching that error.

**Comment by arnaud-m** [comment]
I am not sure. It is mostly for benchmarking (solving 17 queens that has 95815104 solutions).

In Choco2, the default solution pool kept only the last solution.

**Comment by arnaud-m** [comment]
By the way, runtime statistics are printed after the exception !

**Comment by cprudhom** [comment]
I think this is OK now ?

**Comment by arnaud-m** [comment]
Yes.
