### ISSUE TITLE
Solution.getIntVal method has incorrect description

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco-solver#487]
The method returns int value but the description in javadoc says that null value should be returned when a variable is not instantianed in a solution. Otherwise is there some other method that can tell me that a variable wasn't instantiated in a solution ?

**Comment by cprudhom** [comment]
The javadoc is not correct.
Actually, when recording a solution, if a variable is not instantiated, it is not recorded.
Then, when you call for its value in the solution, it throws an exception.
However, unstantiated variable can be logged when if you override `Settings.warnUser()` to `true`.

I will update the javadoc.
