### ISSUE TITLE
Providing Model.renewSolver()

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#490]
I'm considering to create in `Model` a method named `renewSolver()` that erases the current solver and replaces it by a new one.
Such a method should be helpful when `Solver.reset()` is not enough, for instance when dealing with search monitors, counters or explanation (that is a `Learner` but also an `Explainer`).
By creating a new solver, the model remains the same, but the way it can be solved may be adapted.

The following part should be reconsidered to avoid unexpected behavior:
- [ ] `Model.setObjective(boolean, IntVar)` should not create the objective manager, but only records the parameters. Then, at initialization, the solver should create the objective manager.
- [ ] same goes with `Model.clearObjective()`

There are also some restrictions to consider:
- a solver can only be renew at root node, before running any search. This will be ensured by calling `solver.reset()` on the old solver before creating the new one.

Alternatively, we can consider a `deepReset()` in `Solver`, that acts as a solver renewal, but that may be confusing with current `reset()`. 
In both cases, the actions about objective should be done.

**Comment by cprudhom** [comment]
After discussion with @jgFages : 
- [ ] let's list references to `Solver` in the library and sum up what should be reset
- [ ] update `Solver.reset()` instead of `renewSolver()` or `deepReset()`
- patch objective behavior.

**Comment by cprudhom** [comment]
Here is what calling `reset()` will do:
- [x] backtrack to rootWorldIndex
- [x] set searchWorldIndex to 0
- [x] set action to Solver.Action.initialize
- [x] reset bounds of objectivemanager (calling IObjectiveManager.resetBestBounds()
- [x] reset mMeasures
- [x] synchronize dpath to erase out-dated decisions, presumably all of them
- [x] flush engine
- [x] clear criteria, that forget any declared limit
- [x] clear searchMonitors, that forget any declared one
- [x] replace M by MoveBinaryDFS
- [x] replace P by PropagateBasic
- [x] replace L by LearnNothing
- [x] set explainer to NoExplanationEngine.SINGLETON

**Comment by cprudhom** [comment]
I also let `Model.setObjective(boolean, IntVar)` and `Model.clearObjective()` as is, since the objective manager is now reset.

**Comment by mwahbi** [comment]
Hi Charles , 
What about Nogoods?

**Comment by cprudhom** [comment]
Though question. 
This has to do with the model and the solver. 
My first though is to keep them, but should maybe consider differently nogoods from failure (that we should keep) and ones from solutions (that should be removed).
I would prefer to externally deal with the nogoodstore.
What is your opinion about that?
Maybe we should open a new issue

**Comment by cprudhom** [comment]
See #491 to discuss about nogoods

**Comment by jgFages** [comment]
Is the search strategy set back to null?

**Comment by mwahbi** [comment]
By the way, this changes on reset will require a lot of changes for me developing dischoco based on choco4. I don't know what is the case for other choco users. In order to make it easier for us maybe it would be better to make Solver extendable and its attributes protected!!

**Comment by cprudhom** [comment]
@jgFages the move is set to a new instance of MoveBinaryDFS which automatically erase the search strategy. So the answer is yes.

**Comment by jgFages** [comment]
thanks! Well, you have to redefined the search strategy, I believe you can redefine that you want to record nogoods...

**Comment by cprudhom** [comment]
I finally made the choice of two methods instead of one:
- `reset()` that preserves how the search space is explored as defined by the user (ie, search strategy, move, learn and propagate are untouched)  but backtracks to root node, reset measures, erases feasibility status, resets bounds of objective manager and forgets limits.
- and `hardReset()` that calls `reset()` and then erases move, search strategy, learn, propagate and search monitors.

The former restores the solver as before running the last resolution call, the latter restores the solver as after its creation.
`reset()` has an impact on internal variables that cannot be modified thanks to setters, but that's not the case for `hardReset()`, so mid-level reset can be defined by the user.

**Comment by marquessbr** [comment]
Hi
I want to make a crossword game, so, I got the crossword example and when I try to compile I got a error in the call "solver.post(IntConstraintFactory.alldifferent(E, "BC"));" line, so, How is the equivalent command in the 4.0.2 version?

thanks!

**Comment by cprudhom** [comment]
Hi marquessbr, 

Please use the [google groups](https://groups.google.com/forum/#!forum/choco-solver) and **not an unrelated closed issue** to post that kind of questions.

Best,
CP

**Comment by marquessbr** [comment]
Hi, thanks, @cprudhom!
Ok
