### ISSUE TITLE
final Solver! 

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco-solver#499]
Is there a particular reason to make Solver final? I would be very helpful for me if it is not! 
I can make the changes, mainly the search loop to call different procedures one for each action as in version 3!

**Comment by cprudhom** [comment]
Since there is no way to renew or replace the solver, I believe it can be final.
However, if a class inherits from `Model` and define those methods, obviously, we should remove the final keyword.
I'll manage it.
