### ISSUE TITLE
Calculation of bounds for division returns wrong bounds

### ISSUE THREAD

**Issue by limond** [chocoteam/choco-solver#502]
It seems to me like the method ``VariableUtils.boundsForDivision`` does not return the right bounds.

Example:
```java
Model model = new Model();
int[] bounds = VariableUtils.boundsForDivision(model.intVar(-10, 10), model.intVar(-10, 10));
System.out.println(bounds[0]);
System.out.println(bounds[1]);
```
I would expect the following output:
```
-10
10
```

The actual output is:
```
-1
1
```

This makes it impossible to find a solution for problems in certain cases if the divisors domain includes a sign change:
```java
IntVar dividend = model.intVar(-10, 10);
IntVar divisor = model.intVar(-10, 10);
IntVar quotient = model.intVar(-10, 10);
dividend.div(divisor).eq(quotient).post();
quotient.eq(10).post();
```
A solution would be: dividend=10; divisor= 1; quotient=10
However ``model.getSolver().propagate()`` throws a ``ContradictionException``

**Comment by cprudhom** [comment]
Thank you for the bug report, I'll have a look today.
