### ISSUE TITLE
CSP with costed domain {choco 3}

### ISSUE THREAD

**Issue by semantoro** [chocoteam/choco-solver#503]
Hi , 
the question seems very easy, but i can't find the solution since serveral weeks.
I want to attach in my model EXPLICITLY for each value in domain a cost (all the regular_cost constraint are not good for me)
I want some cost structure for variables that allow to attach for each value in domain its cost.
I tried the TSP constraint but its propagator filters some interesting solutions. 
thank you for your response.

**Comment by jgFages** [comment]
Hi, look at the ELEMENT constraint (it is used by the TSP)

**Comment by semantoro** [comment]
Im not interested by the tsp constraint by its given here as an example,
My issus is how attach **explicitly** for each value in domain a cost.

Thank your for your interaction.

**Comment by cprudhom** [comment]
With the element constraint, you can attach a cost to any value in the domain of a given variable.
`element(IntVar value, int[] table, IntVar index)`
See, for instance:
```java
IntVar x = model.intVar("x", 0, 5);
int[] costs = {10,20,30,22,12,2};
IntVar Cx = model.intVar("x", 0, 5);
model.element(Cx, costs, x);
```
Doing so, you'll attach 10 to value 0 of x, 20 to value 1, etc. and Cx will reflect the cost.

Hope this helps.

**Comment by semantoro** [comment]
I get it.
Thank you for your responses.
