### ISSUE TITLE
Constraint.unpost not working?

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#504]
I am trying to apply choco in an interactive setting, where user requirements cause posting constraints on some variables. Changed requirements would need unposting the old requirement constraint and posting a new one. Of course, as much as possible of the solver state should be retained.
However, it seems that unposting a constraint still leaves the old constraint in effect even with         model.getSolver().restoreRootNode();
model.getSolver().hardReset();
Please find below and attached  a simplified example program, executed with choco 4.0.2 under Windows.
(If this is an error in my style of using choco, then maybe javadoc could explain the conditions when unpost works)
[ChocoTest0.zip](https://github.com/chocoteam/choco-solver/files/747430/ChocoTest0.zip)

import org.chocosolver.solver.Model;
import org.chocosolver.solver.constraints.Constraint;
import org.chocosolver.solver.exception.ContradictionException;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.util.iterators.DisposableRangeIterator;

public class ChocoTest0 {

    public static void main(String[] args) {
        Model model = new Model("model");
        IntVar myEnum = model.intVar("myEnum", new int[] {1, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 423, 424});
        try {
            //simulate a user requirement
            Constraint c=model.arithm(myEnum, "=", 239);
            model.getSolver().showDecisions();
            model.post(c);
            
            //I am interested in allowed values of different variables after some user requirements 
            //this example is naive, because the same variable is constrained and domain inspected.
            model.getSolver().propagate();
            DisposableRangeIterator rit =  myEnum.getRangeIterator(true);
            while (rit.hasNext()) {
                int from = rit.min();
                int to = rit.max();
                System.out.print(from+" "+to+": ");
                rit.next();
            }
            System.out.println();
            rit.dispose();
            
            //the requirement is changed
            model.unpost(c);
            //the following do not help (commented out or not)
            model.getSolver().restoreRootNode();
            model.getSolver().hardReset();
            //I would prefer preserve as much of the solver state as possible.
            Constraint c2=model.arithm(myEnum, ">", 239);
            model.post(c2);
            //This fails. Is this a bug or am I doing something wrong?
            //CONTRADICTION (myEnum >= 240, myEnum = 239) : new upper bound is lesser than lower bound
            model.getSolver().propagate();

            //here I would like to see the new domains
            //in realistic scenarios, propagation could affect many variables
            rit =  myEnum.getRangeIterator(true);
            while (rit.hasNext()) {
                int from = rit.min();
                int to = rit.max();
                System.out.print(from+" "+to+": ");
                rit.next();
            }
            System.out.println();
            rit.dispose();
            //    
        } catch (ContradictionException e) {
            e.printStackTrace();
        }
        int i = 1;
        while ((i<200) && model.getSolver().solve()) {
            System.out.println("Solution " + i++ + " found : " + myEnum);

        }

    }
}

**Comment by cprudhom** [comment]
Hi,

Unposting constraint works, but you made a wide spread mistake when only propagation is required.

Propagation has side effect on variables' domain (ei, domain reduction), and if you don't anticipate this, you will set the model in an incoherent state.

So what you need to do is pushing a copy of the current (that is, here, initial) state of the model **before** running a propagation, then propagate and **after** restoring the state, i.e. popping the last copy made.

Making a copy is done with:
```java
model.getEnvironment().worldPush();
```
Restoring the last copy is done with:
```java
model.getEnvironment().worldPop();
```

Here is your code with the required instructions:
```java
Model model = new Model("model");
IntVar myEnum = model.intVar("myEnum", new int[] {1, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 423, 424});
try {
    //simulate a user requirement
    Constraint c=model.arithm(myEnum, "=", 239);
    model.getSolver().showDecisions();
    model.post(c);

    //I am interested in allowed values of different variables after some user requirements
    //this example is naive, because the same variable is constrained and domain inspected.
    model.getEnvironment().worldPush(); //  NEW CODE HERE
    model.getSolver().propagate();
    DisposableRangeIterator rit =  myEnum.getRangeIterator(true);
    while (rit.hasNext()) {
        int from = rit.min();
        int to = rit.max();
        System.out.print(from+" "+to+": ");
        rit.next();
    }
    System.out.println();
    rit.dispose();
    model.getEnvironment().worldPop(); //  AND HERE
    //the requirement is changed
    model.unpost(c);
    //the following do not help (commented out or not)
    model.getSolver().restoreRootNode();
    model.getSolver().hardReset();
    //I would prefer preserve as much of the solver state as possible.
    Constraint c2=model.arithm(myEnum, ">", 239);
    model.post(c2);
    //This fails. Is this a bug or am I doing something wrong?
    //CONTRADICTION (myEnum >= 240, myEnum = 239) : new upper bound is lesser than lower bound
    model.getEnvironment().worldPush(); //  AND HERE
    model.getSolver().propagate();

    //here I would like to see the new domains
    //in realistic scenarios, propagation could affect many variables
    rit =  myEnum.getRangeIterator(true);
    while (rit.hasNext()) {
        int from = rit.min();
        int to = rit.max();
        System.out.print(from+" "+to+": ");
        rit.next();
    }
    System.out.println();
    rit.dispose();
    model.getEnvironment().worldPop(); //  AND HERE
    //
} catch (ContradictionException e) {
    e.printStackTrace();
}
int i = 1;
while ((i<200) && model.getSolver().solve()) {
    System.out.println("Solution " + i++ + " found : " + myEnum);
}
```
which outputs:
```
239 239: 
240 249: 423 424: 
Solution 1 found : myEnum = 240
Solution 2 found : myEnum = 241
Solution 3 found : myEnum = 242
Solution 4 found : myEnum = 243
Solution 5 found : myEnum = 244
Solution 6 found : myEnum = 245
Solution 7 found : myEnum = 246
Solution 8 found : myEnum = 247
Solution 9 found : myEnum = 248
Solution 10 found : myEnum = 249
Solution 11 found : myEnum = 423
Solution 12 found : myEnum = 424
```

Hope its helps.

**Comment by JiiTee** [comment]
Thank you very much for prompt guidance! It really helps!
Now I have a better mental model on the interactive use of of choco. 

I would further like to ask: Can one 
model.getEnvironment().worldPush();
be used several times? E.g. for interactive scenarios, I would perform initial propagation without any user requirements and call
model.getEnvironment().worldPush();

Then I could post and unpost requirements, propagate, solve even and then return to this initial state and call 
model.getEnvironment().worldPop(); 
? Or is worldPush() really a push that is consumed by the next pop?

Thanks!

**Comment by JiiTee** [comment]
Confirmed - worldPop() is really a pop. No problem :-)

**Comment by cprudhom** [comment]
`worldPush()` stores (pushes) a copy on the top of a stack, 
`worldPop()` restores (pops) the copy on the top of the stack.
