### ISSUE TITLE
Ibex integration partially broken in 4.01/4.02?

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#505]
I'm trying to apply enumerated floating point numbers.
In a real linux machine with choco 4.0.0 I get the expected 4 solutions.
In my virtualbox with previously choco 4.0.1 and now 4.0.2 I get only one solution!
(different jar's and package names, but same program code otherwise)

jti@v8:~/workspace/ChocoTest/ChocoTest0$ /opt/java8/bin/java -Djava.library.path=/usr/local/lib -jar build/jar/Chocotest0.jar
Solution 1 found : i1_test_float_value_list = [4.4000000000000000 .. 4.4000000000000000]
Solution 2 found : i1_test_float_value_list = [1.1000000000000000 .. 1.1000000000000000]
Solution 3 found : i1_test_float_value_list = [2.2000000000000000 .. 2.2000000000000000]
Solution 4 found : i1_test_float_value_list = [3.3000000000000000 .. 3.3000000000000000]

jti@jti-VirtualBox:~/workspace/chocopropagationTest$ java -Djava.library.path=/usr/local/lib -jar build/jar/ChocopropagationTest.jar 
Solution 1 found : i1_test_float_value_list = [1.1000000000000000 .. 1.1000000000000000]
jti@jti-VirtualBox:~/workspace/chocopropagationTest$ 

package chocoPropagationTest;

import org.chocosolver.solver.Model;
import org.chocosolver.solver.constraints.real.RealConstraint;
import org.chocosolver.solver.variables.BoolVar;
import org.chocosolver.solver.variables.RealVar;

public class ChocoTest1 {

    public static void main(String[] args) {
        Model model = new Model("Choco Solver Hello World"); 

        RealVar i1_test_float_value_list = model.realVar("i1_test_float_value_list", 1.1, 4.4,1.0E-5);
        BoolVar[] i1_test_float_value_list_guards =new BoolVar[4];
        i1_test_float_value_list_guards[0] = new RealConstraint("{0} = 1.1", i1_test_float_value_list).reify();
        i1_test_float_value_list_guards[1] = new RealConstraint("{0} = 2.2", i1_test_float_value_list).reify();
        i1_test_float_value_list_guards[2] = new RealConstraint("{0} = 3.3", i1_test_float_value_list).reify();
        i1_test_float_value_list_guards[3] = new RealConstraint("{0} = 4.4", i1_test_float_value_list).reify();
        model.sum(i1_test_float_value_list_guards, "=" , 1).post();
        int j = 1;
        while (model.getSolver().solve() ) {
            System.out.println("Solution " + j++ + " found : " + i1_test_float_value_list);
        }
    }
}

**Comment by JiiTee** [comment]
Actually, in 4.01 I had a similar, bigger program that did not behave as expected. Therefore 4.02 update and isolation of the situation, because that the update did not help.

**Comment by cprudhom** [comment]
I believe this is related to #489 and #498 and not the underlying system.
But, I need to check that by myself (presumably by the end of the day)
