### ISSUE TITLE
Real + int problem

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#506]
Is there a problem in my code or is there a bug?
choco 4.0.0 under native Linux
run:
     [java] Exception in thread "main" java.lang.ClassCastException: org.chocosolver.solver.variables.events.IntEventType cannot be cast to org.chocosolver.solver.variables.events.RealEventType
     [java]     at org.chocosolver.solver.variables.impl.scheduler.RealEvtScheduler.init(RealEvtScheduler.java:39)
     [java]     at org.chocosolver.solver.propagation.hardcoded.SevenQueuesPropagatorEngine.onVariableUpdate(SevenQueuesPropagatorEngine.java:327)
     [java]     at org.chocosolver.solver.variables.impl.AbstractVariable.notifyPropagators(AbstractVariable.java:313)
     [java]     at org.chocosolver.solver.variables.impl.AbstractVariable.notifyViews(AbstractVariable.java:327)
     [java]     at org.chocosolver.solver.variables.impl.AbstractVariable.notifyPropagators(AbstractVariable.java:314)
     [java]     at org.chocosolver.solver.variables.impl.BitsetArrayIntVarImpl.instantiateTo(BitsetArrayIntVarImpl.java:391)
     [java]     at org.chocosolver.solver.search.strategy.assignments.DecisionOperator$1.apply(DecisionOperator.java:71)
     [java]     at org.chocosolver.solver.search.strategy.assignments.DecisionOperator$1.apply(DecisionOperator.java:67)
     [java]     at org.chocosolver.solver.search.strategy.decision.IntDecision.apply(IntDecision.java:78)
     [java]     at org.chocosolver.solver.search.strategy.decision.DecisionPath.apply(DecisionPath.java:106)
     [java]     at org.chocosolver.solver.search.loop.propagate.PropagateBasic.execute(PropagateBasic.java:46)
     [java]     at org.chocosolver.solver.Solver.searchLoop(Solver.java:298)
     [java]     at org.chocosolver.solver.Solver.solve(Solver.java:265)
     [java]     at chocoPropagationTest.ChocoFloatCalc02.main(Unknown Source)
     [java] Java Result: 1
-------
package chocoPropagationTest;

import java.util.LinkedList;

import org.chocosolver.solver.Model;
import org.chocosolver.solver.constraints.real.RealConstraint;
import org.chocosolver.solver.variables.BoolVar;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.variables.RealVar;
import org.chocosolver.solver.variables.Variable;

public class ChocoFloatCalc02 {

    public static void main(String[] args) {

        Model model = new Model("model");
        IntVar dim_H = model.intVar("dim_h", new int[] {2000, 2100, 2200});
        RealVar dim_A = model.realVar("dim_A", 150.0, 470.0,1.0E-5);
        BoolVar[] dim_A_guards =new BoolVar[5];
        dim_A_guards[0] = new RealConstraint("{0} = 150.0", dim_A).reify();
        dim_A_guards[1] = new RealConstraint("{0} = 195.0", dim_A).reify();
        dim_A_guards[2] = new RealConstraint("{0} = 270.0", dim_A).reify();
        dim_A_guards[3] = new RealConstraint("{0} = 370.0", dim_A).reify();
        dim_A_guards[4] = new RealConstraint("{0} = 470.0", dim_A).reify();
        model.sum(dim_A_guards, "=" , 1).post();
        RealVar dim_H_asReal = model.realIntView(dim_H, 1.0E-5);
        model.realIbexGenericConstraint("{0}+{1} > 2500", dim_A,dim_H_asReal).post();
        LinkedList<Variable> printVars = new LinkedList<Variable>(); 
        printVars.add(dim_A);
        printVars.add(dim_H);

        int i = 0;
        while (model.getSolver().solve()) {
            i++;
            System.out.print("Solution " + i + " found :");
            for(Variable v: printVars) System.out.print(v + ", ");
            System.out.println("");
        }

    }

}

**Comment by cprudhom** [comment]
Hi,

I believe that using the last released version of the library should work, this bug (#478) has been fixed on december 2016. 

Best
