### ISSUE TITLE
LNS factory class missing completely

### ISSUE THREAD

**Issue by eramol** [chocoteam/choco-solver#508]
Has it been removed or deprecated? It is still used in the docs

**Comment by eramol** [comment]
to be more precise, I added a maven dependency to my project as was suggested in the docs. Although the solver was checked out, the LNSFactory class is not present. Only the INeighborFactory is present in the org.chocosolver.solver.search.loop.lns package

**Comment by cprudhom** [comment]
Hi,

In version >= 4.0.0, you have to go through the solver:
```java
solver.setLNS(INeighborFactory.random(X), new NodeCounter(model, 10));
```
Sorry if the doc is not up-to-date, I'll have a look quickly.

Best

**Comment by eramol** [comment]
OK, thank you very much for the quick reply
