### ISSUE TITLE
Improve IntLinCombFactory.reduce()

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#510]
This may be a worse-case scenario but I'm solving a problem with a sum constraint on up to 40000 distinct variables and creating the constraint takes more than 10 sec on my computer.
Anything that speed up the method is welcomed.

**Comment by fhermeni** [comment]
I am also interested in that point.
Maybe a fail fast in reduce() to  quickly detect equivalent variables.
Also, if you already know there is not a lot to do in terms of static analysis, bypass reduce completely and create directly a SumConstraint + PropSum?

**Comment by cprudhom** [comment]
Actually, bypassing the factory is what I am doing, that works like  a charm, but I know that all variables are distinct.

**Comment by cprudhom** [comment]
- [ ] based 'reduce' on a map
- [ ] enable auto-division on smaller sum on very large sum

**Comment by fhermeni** [comment]
Once reduce() will be in linear time, what would be the benefit of splitting the sums ?

**Comment by cprudhom** [comment]
That should limit the overhead of 'prepare' in 'PropSum' which is called anytime a propagation is triggered

**Comment by fhermeni** [comment]
got it.
