### ISSUE TITLE
A view to normalise a variable

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#513]
Would be great :D.
Normalisation is useful from times to times.
- Normalising by scaling up the variables to the least common multiplier is precise but lead to -overflow when we increase the number of variables
- Normalising to a ratio is precise but theoretical :D

Normalising to a percentage with a given precision is possible (e.g. normalising to 10th of a point: an integer between 0 and 1000) solves the overflow but the DivPropagator makes things so slow: first a scale view, then a new variable and a propagator for each variable to normalise.

IntVar.normalise(int base) : IntVar would then be great

**Comment by cprudhom** [comment]
Actually, like 'abs' such a function is not bijective and cannot exist as a view.
I will add dedicate propagator so you can evaluate it before publishing it in the trunk.
