### ISSUE TITLE
Add constraints on instantiation, remove constraints on backtrack

### ISSUE THREAD

**Issue by eramol** [chocoteam/choco-solver#528]
Hi,

is there a way to join the instantiation of the constraint with an action? E.g. I have got an array of BoolVars. 

Every time I instantiate one, I would like to add a row to some external matrix and post some new constraints. Every time I backtrack and thus lose the instantiation, I would like to unpost the constraints and delete the row in the matrix.

Is there some way to achieve that?

**Comment by cprudhom** [comment]
Hi Eramol,

First, only a variable can be _instantiated_, a constraint can be _satisfied_ .
You want to add new constraints on variable instantiation, right ?

You can add a `monitor` to any variable which acts like an observer.
In the case of a Boolean variable, when it gets instantiated, the observer is called, that's where you can post the new constraints.

By calling, `model.postTemp(c)` you can add temporarily a constraint `c`. This constraint will be unposted upon backtrack.

About the row deletion, that's not really clear to me, but you can try to add a new `IOperation` anytime a new row is added. This operation will be called on backtrack, so it should encode the row deletion.

To sum up:

```java
Model model = new Model();                                          
BoolVar[] bvars = model.boolVarArray(10);                           
List<Long> rows = new ArrayList<>();                                
// add permanent constraints on bvars here                          
for(BoolVar b: bvars){                                              
    b.addMonitor((v,e)-> {                                          
        // v is the touched variable                                
        // e is always INSTANTIATE for BoolVar, so you can ignore it
        model.postTemp(/* some constraints */);                     
        /* add the row here, f-ex.*/                                
        long tt = System.currentTimeMillis();                       
        rows.add(tt);                                               
        model.getEnvironment().save(() -> {                         
            /* delete the row here, f-ex.*/                         
            rows.remove(tt);                                        
        });                                                         
    });                                                             
}                                                                   
// ...                                                              

```

Hope it helps,
CP

**Comment by eramol** [comment]
Thank you very much for the valuable information
