### ISSUE TITLE
DecisionMaker has inconsistent method signatures

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#537]
[internal link](https://github.com/chocoteam/choco-solver/blob/master/src/main/java/org/chocosolver/solver/search/strategy/decision/DecisionMaker.java)

The three methods allow
- [ real ] to create a split decision over a variable and a value
- [ integer | set ] to create a decision over a variable, a value, and an operator 

basically real users do not need (and can't) specify their operator.

Two main operator classes are used for integers : assign/remove and split
I thus propose to add two methods :

``` java
/** assign var=val */
public IntDecision makeIntAssign(IntVar var, int val){
  return makeIntDecision(var, DecisionOperatorFactory.makeIntEq(), val);
}

/** split var into [var.lb, val] */
public IntDecision makeIntSplit(IntVar var, int val){
  return makeIntDecision(var, DecisionOperatorFactory.makeIntSpkit(), val);
}
```

makeIntRemove could be also present with a simple `return makeIntAssign(var, val).flip();`

The set method should also be present ( makeSetForce )

**Comment by jgFages** [comment]
what is your real motivation for doing so? 

Regarding consistency, I would rather rename makeRealDecision into makeRealSplitDecision, but I do not see the point in adding more code...
