### ISSUE TITLE
solver instance

### ISSUE THREAD

**Issue by mwahbi** [chocoteam/choco-solver#541]
Hi @cprudhom, @jgFages, 
I think the solver should not be final in the model. If somebody wants to extend the solver and to maneuver its extensions. Why this? 
I have a user communicating with the solver through (1) adding decisions and (2) adding nogoods or reporting nogoods when the problem is infeasible regarding (1). But, I have restrictions on the processing of doing so: (3) a solver is not allowed to change the decisions in (1) and (4) can only make decision on a subset of variables. 
For doing (4) it is easy defining a strategy on the subset of variables is the solution. 
I think for doing (3) there two options: The first adding new equality constraints (maybe it will be slow) but it will be a problem when we can not find a solution and we need to report the nogood to the user (2), i.e., a subset of (1). The second one is to manipulate the decision path adding new decisions from (1) to it and in this case as well we need to change the repair phase because we cannot refute a decision form (1). 
I think all those issues can be solved if the solver/model is modular and will avoid to change the source codes and use directly the maven dependency. Moreover, it will ease maintaining the codes. Right? 
Any other thoughts on my issues are very welcome!
Cheers,

**Comment by cprudhom** [comment]
I agree that it could be useful when one has its own implementation of `Solver`.
But I think we should avoid using hook to store such crucial object.
Indeed, `model.getSolver()` is used almost everywhere.

I suggest we define a method in `Model` named `createSolver()` with no parameter which, by default, create a `Solver` object as for now.
This method can be overridden  by anyone who wants to change the way a solver is created.

Alternatively, we could this new method in `Settings` instead of `Model`.

**Comment by mwahbi** [comment]
I initially propose createSolver()/setSolver() but change it later to the hook thinking that would be better. But, now I see the issue of hook so yes it shouldn't be a hook. I am for createSolver()/setSolver(). So, it is up to you.

**Comment by jgFages** [comment]
Hi,
First of all, I am not sure I really understood what you need but it seems that:
You have a server with a choco model. 
You receive a user request that applies a few constraints/decision
You want a solution or an explanation of failure

1) -> You can do all this without changing anything in source code. 
Applying constraints should be ok but actually you could instantiate it directly manually if it is only assignments (I do it on some configurator projects).
2) -> What do you use to explain the conflict? Maybe here is the issue

**Comment by mwahbi** [comment]
Hi JG,
What I need to do is feasible by reusing the codes from Solver (that is what I am doing). But, it will be easier using codes from Solver and override only methods I need to depending on what I want to do. 
What I do have is a set of agents each with its local CSP (i.e., model/solver). Variables from different agents/models are involved in some constraints between them (to do so, every model contains copies of variables from other models constrained with). Now, when an agent will take its decisions by solving its own CSP it is not allowed to take decisions on the copies from other models. But, agents/models need to collaborate to satisfy constraints between them. They do that by sharing the decisions they took. A model does not involve all variables from other models nor their constraints. Those are the general restrictions. 
Now depending on the negotiation protocol used by agents we might have different behavior on response to the decisions received from their neighbors to satisfy constraints between them. An agent might need for example to tell that he could not find a solution because of a subset of decisions from other agents or he could change its own decisions. So mainly explanation are in the form of nogoods: not(x=a,y=b,z=c) that should be shared with other agents. When an agents will receive a nogood he needs to post it. Briefly, what I need to make interfaces that communicate between different models/solvers that share some variables/constraints. I hope it is more clear now! I can always work on an example if you think it will help to illustrate what I am using choco for.

**Comment by jgFages** [comment]
As you say, all you need is to make interfaces that communicate... I would really do it in pure Java without modifying/overriding any line of code of the model/solver...

**Comment by mwahbi** [comment]
Thank you JG,
That is what I previously did, but when new versions appear I found it difficult to upgrade my codes accordingly, so I thought it will be nice and easier if I will only address the parts that needs revision. 
Cheers,
