### ISSUE TITLE
Reification of Ibex constraints does not work

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#545]
It seems that Ibex constraint reification is not working.

According to experiments on my home Windows PC, Ibex reification works in 4.01, but it does not work in any later version. I'm using Ibex 2.3.4. 

Is there a way around this? A solution / workaround would be most helpful! 

The problem exists under Linux, too (choco 4.0.4 does not work, some older choco worked, probably 4.0.1).

Example, (with imports excluded) below.

public class RealEnum {

    public static void main(String[] args) {
        Model model = new Model("test");
        RealVar x =model.realVar("x", 0 , 20, 0.00001);
        RealVar y =model.realVar("y", 0 , 15, 0.00001);
        BoolVar [] guards = new BoolVar [2];
        guards[0] = model.realIbexGenericConstraint("{0} = 13.2", x).reify();
        guards[1] = model.realIbexGenericConstraint("{0} = 3.2", x).reify();
        model.sum(guards, "=", 1).post();
        model.realIbexGenericConstraint("{0} + {1} = 14", x, y).post();
        try {
            model.getSolver().propagate();
            System.out.println( x.getLB() +  ", " + x.getUB() +", " + y.getLB() +  ", " + y.getUB());
        } catch (ContradictionException e) {
            e.printStackTrace();
        }
        int sol = 0;
        while(model.getSolver().solve()) {
            sol++;
                System.out.println(sol+":" + x+", "+ y+", "+ y.getLB() +  "," + y.getUB() +", "+ x.getLB() +  ", " + x.getUB());
        }
    }

}

```
Choco 4.01:
0.0, 14.0, 0.0, 14.0
1:x = [3,2000000000000000 .. 3,2000000000000000], y = [10,7999999999999990 .. 10,8000000000000000], 10.799999999999999,10.8, 3.2, 3.2
2:x = [13,2000000000000000 .. 13,2000000000000000], y = [0,8000000000000007 .. 0,8000000000000007], 0.8000000000000007,0.8000000000000007, 13.2, 13.2

Choco 4.0.2, 4.03, 4.0.4

13.2, 13.2, 0.8000000000000007, 0.8000000000000007
1:x = [13,2000000000000000 .. 13,2000000000000000], y = [0,8000000000000007 .. 0,8000000000000007], 0.8000000000000007,0.8000000000000007, 13.2, 13.2

```
Best & thanks!
Juha

**Comment by JiiTee** [comment]
Plain old 'or'would work here, I think. But reification is still needed!

**Comment by cprudhom** [comment]
Could you try with the current snapshot version (i.e., 4.0.5-SNAPSHOT) ?

You can either try it with maven or download [the nightly build](https://oss.sonatype.org/content/repositories/snapshots/org/choco-solver/choco-solver/4.0.5-SNAPSHOT/choco-solver-4.0.5-20170710.130654-31-with-dependencies.jar).

**Comment by JiiTee** [comment]
It works! Thank you!
( I tried with nightly build choco-solver-4.0.5-20170710.130654-31-with-dependencies.jar)

Sorry for late reply - holidays!
Best,
Juha
