### ISSUE TITLE
How to use choco-solver to compare different table constraints algorithms(CT, STR..) .

### ISSUE THREAD

**Issue by Meko1** [chocoteam/choco-solver#547]
Hi

I want to use choco-solver to compare different table constraints algorithms(CT, STR) on various sample, How to do this? I am not much familiar with choco.
thanks for your reply!

Best
Meko

**Comment by cprudhom** [comment]
Sorry for late reply.
Simply change the algorithm parameter of the table constraints:
```java
model.table(vars, tuples, algo);
```
where 'algo' can be set to : "CT+", "FC", "GAC2001", "GACSTR+", "GAC2001+", "GAC3rm+", "GAC3rm", "STR2+", "MDD+"
