### ISSUE TITLE
Bug in subcircuit

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#550]
The following code fails at finding all solutions:

```java
Model model = new Model();
IntVar[] x = model.intVarArray("x", 10, 0, 20, true);
model.subCircuit(x, 0, model.intVar("length", 0, x.length - 1, true)).post();
model.getSolver().findAllSolutions();
assertEquals(1, model.getSolver().getSolutionCount());
```

**Comment by jgFages** [comment]
Are you saying the number of solution is incorrect or there is a time out?
The number of solutions is exponential... its normal that it takes time.
Can we discuss over a smaller size?
Btw, the assertion is wrong (more than 1 solution)

**Comment by jgFages** [comment]
are you on your current dev branch?
it works for me on master...

**Comment by cprudhom** [comment]
with `-ea`?

**Comment by jgFages** [comment]
ahah yes I doubled checked ^^

**Comment by cprudhom** [comment]
Ok, my bad, I've introduced a bug :/
