### ISSUE TITLE
Geost Constraint

### ISSUE THREAD

**Issue by bourreauEric** [chocoteam/choco-solver#552]
Hello,
 Have you a roadmap to adapt Geost Constraint (last choco release 3.2.1) to Choco 4 ?
 Thanks.
    Eric

**Comment by cprudhom** [comment]
Honestly no. 
This constraint is too hard to maintain, that's why it is in another project.
There is a known bug which I am clearly unable to understand (and so to fix).
I can make basic migration of the code so it is compliant with Choco4, but nothing more.

**Comment by bourreauEric** [comment]
At least, it will be great !

**Comment by cprudhom** [comment]
Close see [choco-geost-4.0.5](https://github.com/chocoteam/choco-geost/releases/latest).
