### ISSUE TITLE
Optimization multi Objective 

### ISSUE THREAD

**Issue by semantoro** [chocoteam/choco-solver#553]
Hi, 
I have aproblem with MultiObjective Optimization (pareto front), i respected exactly the example in docs , but i have the  follow exception 
Cannot access value of exceeding[0] = [69,85]: This variable has not been declared to be recorded in the Solution object (see Solution constructor).

code: 
```java
//declaration of model and solver and all the packed nedded.
IntVar[] exceeding = model.intVarArray("exceeding", NbOfPeriod * services.length, -1000000, 1000000);
ParetoOptimizer po = new ParetoOptimizer(Model.MINIMIZE,exceeding);
		solver.plugMonitor(po);
         	while (solver.solve());
		List<Solution> paretoFront = po.getParetoFront();
		System.out.println("The pareto front has " + paretoFront.size() + " solutions : ");
		for (Solution s : paretoFront) {
		System.err.println(s);	
```

Thank you for your response.

**Comment by cprudhom** [comment]
I'm not able to reproduce the bug.
Which version of choco are you using?

**Comment by semantoro** [comment]
Iuse the last version choco 4

**Comment by cprudhom** [comment]
4.0.5 ?

**Comment by semantoro** [comment]
I used 4.0.2 and i just moved to the latest version 4.0.5 , the problem still unsolved.

**Comment by jgFages** [comment]
Can you try calling directly
solver.findParetoFront(...)?

**Comment by cprudhom** [comment]
Could you please provide a MWE  (as depicted in [CONTRIBUTING.md](https://github.com/chocoteam/choco-solver/blob/master/CONTRIBUTING.md)) otherwise that will be difficult to help you more.

On my side, when I run this:
```java
@Test(groups="1s", timeOut=60000)
public void testPP() {
    Model model = new Model();
    //declaration of model and solver and all the packed nedded.
    IntVar[] exceeding = model.intVarArray("exceeding", 10, -1000000, 1000000);
    ParetoOptimizer po = new ParetoOptimizer(Model.MINIMIZE, exceeding);
    Solver solver = model.getSolver();
    solver.plugMonitor(po);
    while (solver.solve()) ;
    List<Solution> paretoFront = po.getParetoFront();
    System.out.println("The pareto front has " + paretoFront.size() + " solutions : ");
    for (Solution s : paretoFront) {
        System.err.println(s);
    }
}
```
I got no error but:
```
Solution: exceeding[0]=-1000000, exceeding[1]=-1000000, exceeding[2]=-1000000, exceeding[3]=-1000000, exceeding[4]=-1000000, exceeding[5]=-1000000, exceeding[6]=-1000000, exceeding[7]=-1000000, exceeding[8]=-1000000, exceeding[9]=-1000000,
```

Best.

**Comment by semantoro** [comment]
It's the same , the problem is how to access to the varibales' values when findind the solution in multi Optimizing problme

**Comment by cprudhom** [comment]
Ok, I didn't understand you didn't find how to get variables' value.
This is done thanks to `solution.getIntVal(IntVar)` API, something like:

```java
for (Solution s : paretoFront) {
    for(int i = 0 ; i< exceeding.length; i++){
        System.out.printf("%d ",s.getIntVal(exceeding[i]));
    }
    System.out.printf("\n");
}
```

**Comment by semantoro** [comment]
OK, thank you for your responses.
I finnaly fix my problem.
