### ISSUE TITLE
Modulo

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#555]
current modulo constraint has all arguments variables: x1%x2 = x3
I believe it is very rare that x2 is a variable

- a specific implementation with x2 as a fixed int should improve runtime

- Having another signature with both x2 and x3 fixed would also make sense, and it can be implemented easily as a member over a precomputed array

No hurry but to keep in mind

**Comment by arnaud-m** [comment]
Hello, 

I am ready to implement these constraints if it helps. 

I was wondering if the current decomposition could not be also replaced by a specialized constraint. 
What do you think ?

**Comment by cprudhom** [comment]
You have my green light
