### ISSUE TITLE
How to add condition based on a boolean value?

### ISSUE THREAD

**Issue by kunalsapru** [chocoteam/choco-solver#556]
Experienced with choco-solver-_*{4.0.5}*_

In Choco Solver 2, if we had to add a constraint that some boolean variable(for eg v2) must be true when some boolean variable(for eg v1) is true, we would write it as follows:
```java
Constraint c = Choco.implies(Choco.eq(v1,1), Choco.eq(v2,1));
```
How can we acheive the same thing in ChocoSolver 4.0.5 ?

**Comment by jgFages** [comment]
model.ifThen

**Comment by kunalsapru** [comment]
But, model.ifThen does not return a constraint object. Actually, I want to save this in a constraint list.

**Comment by jgFages** [comment]
ifThen(A,B) is equivalent to
xA = A.reify();
xB = B.reify();
xA <= xB (you can store that arithm constraint)

**Comment by kunalsapru** [comment]
Thanks, but it's not what I was hoping for. Anyways, thanks again.

**Comment by kunalsapru** [comment]
Can you please give equivalent statements for `ifOnlyIf(A,B)` also, the same way you gave for `ifThen(A,B)` ?

**Comment by kunalsapru** [comment]
Thanks, but can we get the final statement as a constraint like arithm in case of ifThen(A,B) ?

**Comment by jgFages** [comment]
ah lol
you wanted this:
xA = A.reify();
xB = B.reify();
xA = xB

**Comment by kunalsapru** [comment]
Oh. That's easy. Many thanks.
