### ISSUE TITLE
What are the equivalent statements for the following in ChocoSolver 4?

### ISSUE THREAD

**Issue by kunalsapru** [chocoteam/choco-solver#559]
Hello,
I'm using aspect programming to add constraints to certain classes. In our project we were using ChocoSolver 2 to write statments like this:
```java
    public Constraint MEquivExp.collectConstraints(ChocoSolver s) {
        return Choco.ifOnlyIf(getLeft().collectConstraints(s),getRight().collectConstraints(s));
    }
    public Constraint MImpliesExp.collectConstraints(ChocoSolver s) {
        return Choco.implies(getLeft().collectConstraints(s),getRight().collectConstraints(s));
    }
    public Constraint MOrBoolExp.collectConstraints(ChocoSolver s) {
        return Choco.or(getLeft().collectConstraints(s),getRight().collectConstraints(s));
    }
    public Constraint MAndBoolExp.collectConstraints(ChocoSolver s) {
        return Choco.and(getLeft().collectConstraints(s),getRight().collectConstraints(s));
    }

    public Constraint MGTExp.collectConstraints(ChocoSolver s) {
        return Choco.gt(getLeft().collectIntExpr(s),getRight().collectIntExpr(s));
    }
    public Constraint MLTExp.collectConstraints(ChocoSolver s) {
        return Choco.lt(getLeft().collectIntExpr(s),getRight().collectIntExpr(s));
    }


```
Now as you see, when collectConstraints method is called on any of these classes they return a Constraint object.  Can you please suggest, how can I achieve the same thing with ChocoSolver 4?

I tried using Clauses, but I want to use constraints so that I can post and unpost them.

**Comment by kunalsapru** [comment]
Here's another exampe of what I'm expecting:
```java
(F7.g >= 5 && F7.g <= 200 && F7.f==1 && F7.r > 45 && F7.r < 76)
```
I want this equation to be treated like a constraint, so that I can post and unpost it and also, show to the user, which constraint failed for the given input.

**Comment by kunalsapru** [comment]
Also, please suggest a way to write a constraint for a equation like this:

```java
(F7.g >= 5 && F7.g <= 200 && F7.f==1 && F7.r > 45 && F7.r < 76)
-> 
(F7.a >= 5 && F7.b <= 200 && F7.t==1 && F7.j>45 && F7.n < 76)
```
Here `->` symbol means that we have to apply Choco.implies function in Chocosolver 2.

**Comment by jgFages** [comment]
The same way as I answered in #556

**Comment by kunalsapru** [comment]
What about this equation:
`(F7.g >= 5 && F7.g <= 200 && F7.f==1 && F7.r > 45 && F7.r < 76)`

How can I write this?

**Comment by jgFages** [comment]
model.and(model.arithm(F7.g,">=",5),...)
Please do model.+ctrl space to see all constraints

**Comment by kunalsapru** [comment]
Thanks, I completely overlooked this. I thought only Clauses can do logical operations. My bad.
