### ISSUE TITLE
How to compute arithmetic equations in choco solver 4?

### ISSUE THREAD

**Issue by kunalsapru** [chocoteam/choco-solver#560]
Hi,

In choco solver 2.1.1, we were able to compute some values based on operators. For eg.
`Choco.div(), Choco.mod(), Choco.mult()...` All these functions would take two variables and return the corresponding result.

How can we do the same in ChocoSolver 4 ?
I searched the model functions and found functions:
`model.div(), model.times() etc...` All these functions take 3 instead of 2 parameters and we also have to provide our expected result. Are there functions which just calculate the result and send it back?

**Comment by cprudhom** [comment]
Did you read the tutorial ?
In [Verbal Arithmetic](http://choco-tuto.readthedocs.io/en/latest/src/303.code.html) there is an example of usages you are looking for.

```java
IntVar X = model.intVar(0,6); 
IntVar y = model.intVar(1,7);
IntVar W = X.mod(Y); 
```

**Comment by kunalsapru** [comment]
Thanks :+1:
