### ISSUE TITLE
How to use RealVar

### ISSUE THREAD

**Issue by ycbbit** [chocoteam/choco-solver#563]
### Expected behavior
I am currently using CHOCO 4  , I can use IntVar to get the solution, but when  I try using a RealVar, I don't know how to change the code, it will be appreciated you can help me  and give feedback, thanks
### Actual behavior
I want to change the shift from  IntVar to RealVar, the precision = 0.1, could you kindly show me how to change the code, thanks
### Minimal Working Example
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.solver.*; 

public class MWE {
	public static void main(String[] args) {
		String[] series = { "Y", "U", "G", "E", "P&W", "Yoda", "Windu","L","T", "X", "DT","SSD"};  
		int[] ppQty = new int[] {125000,63000,862000,235000,26000,60000,200000,65000,120000,95000,230000,100000};  	
		int[] uph = new int[] {190,280,342,275,64,210,250,250,230,280,160,600}; 
		int[] manpower = new int[] {69,69,59,67,65,102,102,102,102,102,83,8}; 
		int rate = 24;
		int oRate = 13; 
		int wRate = 17;
		int productType = ppQty.length;
		int maxLine = 50;
		int maxppQty = 10000000;
		int workDays = 21;
		int otWorkdays = 21;
		int weekends = 4;
		int workHours = 8;
		int otWorkdayHours = 3;
		int otweekendHours = 11;

		for (int i = 0; i <=productType - 1; i++) {
			Model model = new Model("Cost");
			// Variants
			IntVar overtime = model.intVar("overTime", 0,400,false);
			IntVar weekend = model.intVar("weekend", 0,maxLine*5,false);
			IntVar shift = model.intVar("line", 0, maxLine, false);
			IntVar quantity = model.intVar("quantity", 0, maxppQty);
			// Objective variant
			IntVar cost = model.intVar("cost", 0, 8 * 22 * maxLine * 200 * rate);
			IntVar otCost = model.intVar("otCost", 0, 4 * 22 * maxLine * 200*oRate);
			IntVar weekendCost = model.intVar("weenkendCost", 0, 11 *4* maxLine * 200 * wRate);		
			IntVar myCost = model.intVar("myCost", 0, 8 * 22 * maxLine * rate * 200 * 2);

			quantity.eq(((overtime.mul(otWorkdayHours)).add(weekend.mul(otweekendHours)).add(shift.mul(workHours*workDays))).mul(uph[i])).post();
			model.arithm(quantity, ">=", ppQty[i]).post();
			model.arithm(overtime, "<=", shift,"*",otWorkdays).post();
			model.arithm(weekend, "<=", shift,"*",weekends).post();
 			cost.eq(shift.mul(workHours).mul(workDays).mul(manpower[i]).mul(rate)).post();
			otCost.eq(overtime.mul(3).mul(manpower[i]).mul(oRate)).post();
			weekendCost.eq(weekend.mul(11).mul(manpower[i]).mul(wRate)).post();
			myCost.eq(cost.add(otCost).add(weekendCost)).post();

			Solver solver = model.getSolver();
			model.setObjective(Model.MINIMIZE, myCost);
			Solution solution = new Solution(model);
			while (solver.solve()) {
				solution.record();
			}
			if("Empty solution. No solution recorded yet".equals(solution.toString())){
				System.out.println("msg:"+solution.toString());
				continue;
			}
			System.out.println(series[i]+ " Shift: " + solution.getIntVal(shift)+" Cost: " + solution.getIntVal(myCost));			
		}
	}
}

Experienced with choco-solver-_*{version here}*_

```java
{your hava code here}
```

**Comment by ycbbit** [comment]
I saw that Real variables have a specific status in Choco 4, which uses Ibex solver to define constraints in tutorial. If I install the Ibex ,how I write the java code for Realvar to get the solution?

**Comment by cprudhom** [comment]
Hi,

Have a look at the `samples` project, more specifically to [real samples](https://github.com/chocoteam/samples/tree/master/src/main/java/org/chocosolver/samples/real).
Prior to solve your model, follow instructions to install and bind [Ibex](http://choco-solver.readthedocs.io/en/latest/4_advanced.html#using-ibex).

Hope it helps.

NB: please avoid asking the same question by private mail, GitHub, google-groups and Gitter at the same time.

**Comment by ycbbit** [comment]
thanks for your quickly feedback.

**Comment by ycbbit** [comment]
@cprudhom when I executed the example programs, meet a error as follows:
The following option should be passed as VM argument: "-Djava.library.path=/path/to/ibex/dynlib"

**Comment by cprudhom** [comment]
Did you pass this parameter as a JVM argument ?

**Comment by ycbbit** [comment]
Yes , I did that  pass this parameter as a JVM argument.   
Unfortunately, based on environment:Win10+Mingw 32+JDK1.7 32bit
there is another error as below:
ibex-java.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method);
How to fix this issue?

**Comment by cprudhom** [comment]
Well, I don't know, that seems to not be related to choco but either to Ibex or Java+Windows.
If I were you, I would contact Ibex support first.
Best

**Comment by ycbbit** [comment]
thanks for your feedback,  I fix the error I mentioned,
when I run the real examples, meet a new issue, give exception as below 👍
Exception in thread "main" java.lang.NullPointerException
	at org.chocosolver.samples.real.CycloHexan.solve(CycloHexan.java:77)
	at org.chocosolver.samples.AbstractProblem.execute(AbstractProblem.java:123)
	at org.chocosolver.samples.real.CycloHexan.main(CycloHexan.java:81)

**Comment by cprudhom** [comment]
Hi,

I'm unable to reproduce the error (I supposed that you were using samples-4.0.6, choco-solver-4.0.5 and Ibex-2.3.x). Could you be more precise about your environment and give us a minimal working example ? 
Best

**Comment by ycbbit** [comment]
my environment:  samples-4.0.6, choco-solver-4.0.6-SNAPSHOT from Github package and Ibex -2.6.1;
example from Github real examples: CycloHexnan.java

**Comment by cprudhom** [comment]
Ok, I got it.

If you work with the source code, remove `model.getIbex().release();`.

Otherwise, you'll need to wait for the next release of samples (that depends on the next release of choco)

**Comment by ycbbit** [comment]
Clear, appreciating your quickly feedback, thanks again.
