### ISSUE TITLE
Declared constraints, sum decomposition

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#569]
I switched to choco-4.0.5 yesterday and I have major performance regressions due to some optimisations in choco.

The check for declared constraints in the Constraint constructor is very costly. If I let the default settings. It takes 9122 ms to build the CSP. If I disable the checking the building duration is 1227ms.

By default, Choco decomposes sums having more than 100 variables. I have large sums with tens of thousand of variables and the benefits of the decomposition is not clear to me. Using the default settings, the first solution arrives at 5952ms, using a threshold of 10000 variables, the first solution arrives at 2286ms.

What is the benefit of such optimisation ? 
In the case of the sum decomposition, it might be great to have the javadoc of sum discuss about this optimisation to make the user aware of that.

**Comment by cprudhom** [comment]
This is more or less related to #510 
I tried to define a MWE like this:

```java
for(int b =0; b < 2; b++) {
    for(int i = 10; i < 100001; i*=10) {
        Model m = new Model();
        int finalB = b;
        int finalI = i;
        m.set(new Settings() {
            @Override
            public int getMinCardForSumDecomposition() {
                return finalI;
            }
            @Override
            public boolean checkDeclaredConstraints() {
                return finalB == 0;
            }
        });
        IntVar[] is = m.intVarArray("i", 200000, 0, 10);
        for (int j = 0; j < 100; j++) {
            m.sum(is, "<=", j * 100).post();
        }
        m.getSolver().findSolution();
        System.out.printf("%s\t%s\t%.3fs\t%.3fs\n",
                i, (b==0),
                m.getSolver().getReadingTimeCount(),
                m.getSolver().getTimeCount());
    }
}    
``` 

```
Card	Check	BuildT	SolvT 
10	true	25,565s	9,689s
100	true	6,504s	3,761s
1000	true	4,338s	1,952s
10000	true	3,530s	1,858s
100000	true	3,614s	2,392s
10	false	14,501s	20,120s
100	false	4,957s	4,280s
1000	false	3,322s	1,752s
10000	false	3,630s	1,749s
100000	false	3,819s	1,853s
```

To me, the decomposition brings some benefits, but maybe the value 100 is not well selected.
Do you have another MWE ?

**Comment by cprudhom** [comment]
Default value is now set to 1024 + commit 70fc4ce04b8abb21db3e7847eb331201ed3c35a3 now enables to programmatically define a specific value for each sum/scalar
