### ISSUE TITLE
solver depends on not official version of jgrapht-core

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco-solver#570]
Hello,
  log from shaded plugin of my project showed me conflict between classes from jgrapht-core artifacts from two groups org.jgrapht and org.javabits.jgrapht used by choco solver. Since official site of jgrapht mentions org.jgrapht group as maven dependency and version of artifacts is updated here (current version is 1.1.0) I think that choco solver should use it if there's no very good reason against it.

  Is it safe to use jgrapth version from org.jgrapht group instead version from org.javabits.jgrapht ?

Thanks,
Jan

**Comment by cprudhom** [comment]
You are right, I'll fix that.
