### ISSUE TITLE
Incorrect interval of intVal after propagate with a constraint including OR

### ISSUE THREAD

**Issue by frankFic** [chocoteam/choco-solver#571]
I want to get the intervals or bounds for a int variable whose constraint is UNION of some intervals that I can only dynamically know at runtime.

It seems that after propagation, the interval of the intVar is not correct. Here is a simplified code example:

```java
Model model = new Model();
IntVar sdk_int = model.intVar("sdk_int", new int[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24});
constraint = model.or(model.arithm(sdk_int, "<=", 15), model.arithm(sdk_int, ">=", 17));
constraint.post();
try {
        model.getSolver().propagate();
} catch (ContradictionException e) {
        e.printStackTrace();
}
DisposableRangeIterator rit = sdk_int.getRangeIterator(true);
while (rit.hasNext()) {
        int from = rit.min();
        int to = rit.max();
        System.out.println("from: " + from + ", to: " + to)
        rit.next();
}
rit.dispose();
```

### Expected behavior
I expected it to print

from: 1, to: 15
from: 17, to: 24
### Actual behavior
It actually printed

from: 1, to: 24

Am I using Choco in a wrong way?
Thx in advance

Experienced with choco-solver-_*4.0.5*_

**Comment by cprudhom** [comment]
The behavior you are expecting is called 'constructive disjunction', which is defined by default as it can be very time consuming.

You can try it with:

```java
// Constraint constraint = model.or(model.arithm(sdk_int, "<=", 15), model.arithm(sdk_int, ">=", 17));
// constraint.post();
model.addConstructiveDisjunction(model.arithm(sdk_int, "<=", 15), model.arithm(sdk_int, ">=", 17));
```

which will print:
```
from: 1, to: 15
from: 17, to: 24
```
as expected.

**Comment by frankFic** [comment]
Thank you very much for your reply!
After a brief testing I found it can work if there are two constraints. What if I have more than two constraints? Like
```
model.addConstructiveDisjunction(model.arithm(sdk_int, "<=", 15), model.arithm(sdk_int, ">=", 17), model.arithm(sdk_int, "<=", 18));
```

This will print
```
from: 1, to: 24
```

A problem for me is that I cannot know how many constraints I will have beforehand.

**Comment by jgFages** [comment]
It works with n constraints
1-24 is the correct answer

**Comment by frankFic** [comment]
@jgFages Oh yes! Thank you for your quick reply!
I just realised my mistake...

**Comment by frankFic** [comment]
Sorry for bothering again so soon...
Can it work for any kind of constraint, including conjunction? For example, if I would want the output is
```
from: 1, to 15
from: 17, to 18
```
Using the code below seems not work
```
```

**Comment by cprudhom** [comment]
That theoretically works for any types of constraints, but it also depends on the strength of their filtering algorithm. Constructive disjunction removes values from variables that are removed by each constraints taken individually. If at least one constraint does not remove a value, this value is not removed from the CD.

**Comment by cprudhom** [comment]
Well, in your case, the second constraint is reformulate (reification) and there is no common variables anymore.

Try this:
```java
model.addConstructiveDisjunction(model.arithm(sdk_int, "<=", 15), model.member(sdk_int, 17, 18));
```

**Comment by frankFic** [comment]
I see. Thanks a lot for your patience and detailed answer. I may close this as it's just my question on how to use Choco.

Thanks a lot!

**Comment by cprudhom** [comment]
The code of CD could be improved to deal with reified constraints that involve one or more shared variables...
