### ISSUE TITLE
model.sum().post() not work

### ISSUE THREAD

**Issue by tao0708** [chocoteam/choco-solver#572]
Model model = new Model("landing");
IntVar[][] y = model.intVarMatrix("runways", N, R, new int[]{0,1});
IntVar[] runways = ArrayUtils.flatten(y); 

model.sum(y[i], "=", 1).post();

model.getSolver().solve();

then print y, all the value of y is 0, why?

**Comment by cprudhom** [comment]
Hi,

I'm unable to run your code: what are the values of `N` and `R`, which value `i` refers to in the sum ?

Also, could you please follow the issue guidelines, set by default, when an issue is open ?

Best

**Comment by tao0708** [comment]
N is 10， R is 2，
for(int i = 0; i < N; i ++){model.sum(y[i],"=",1).post();}

**Comment by tao0708** [comment]
sorry, i don't find out how to reset the label when the issue has been published.

**Comment by tao0708** [comment]
N is 10， R is 2，
for(int i = 0; i < N; i ++){model.sum(y[i],"=",1).post();}

these are parts of my codes.

and sorry, i don't figure out how to reset the label when the issue is already exists.

**Comment by cprudhom** [comment]
With the last version of choco (4.0.6), everything went fine:
```java
Model model = new Model("landing");
int N = 10, R = 2;
IntVar[][] y = model.intVarMatrix("runways", N, R, new int[]{0,1});
  IntVar[] runways = ArrayUtils.flatten(y);

for(int i = 0; i < N; i ++){
    model.sum(y[i],"=",1).post();
}
if(model.getSolver().solve()){
    for(int i = 0; i < N; i ++){
        for(int j = 0; j < R; j ++){
            System.out.printf("%d ", y[i][j].getValue());
        }
        System.out.printf("\n");
    }
}
```
will print:
```bash
0 1 
1 0 
1 0 
1 0 
1 0 
0 1 
1 0 
0 1 
1 0 
0 1
```

Could you be more precise about the version you are using and how do you print `y` values ?

**Comment by tao0708** [comment]
My choco version is 4.04,

 class AircraftLanding (){
       public void modelAndSolveMultipleRunways(){
            Model model = new Model("landing");
            int N = 10, R = 2;
             IntVar[][] y = model.intVarMatrix("runways", N, R, new int[]{0,1});
             IntVar[] runways = ArrayUtils.flatten(y);
          for(int i = 0; i < N; i ++){
                 model.sum(y[i],"=",1).post();
             } 
           Solver solver = model.getSolver();
	        solver.plugMonitor((IMonitorSolution) () -> {
	            for (int i = 0; i < 2 * N; i++) {
		                System.out.printf("%d\n",runways[i].getValue());
		        }
	        });
      }
      	public static void main(String[] args) {
		new AircraftLanding().modelAndSolveMultipleRunways();	
	}
}

the print
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

**Comment by cprudhom** [comment]
With 4.0.6, that works, so I can only encourage you to migrate to that version.

**Comment by jgFages** [comment]
Try to call solver.solve(); before printing output...

**Comment by tao0708** [comment]
Calling solver.solve();before printing does still not work

I think that it's not about the version,  because if I move  the code from the method "modelAndSolveMultipleRunways" to the main function, then it works well, so... i cannot figure out ...

**Comment by cprudhom** [comment]
The following code (corrected from yours) works like a charm:
```java
class AircraftLanding {
    public void modelAndSolveMultipleRunways() {
        Model model = new Model("landing");
        int N = 10, R = 2;
        IntVar[][] y = model.intVarMatrix("runways", N, R, new int[]{0, 1});
        IntVar[] runways = ArrayUtils.flatten(y);
        for (int i = 0; i < N; i++) {
            model.sum(y[i], "=", 1).post();
        }
        Solver solver = model.getSolver();
        solver.plugMonitor((IMonitorSolution) () -> {
            for (int i = 0; i < 2 * N; i++) {
                System.out.printf("%d\n", runways[i].getValue());
            }
        });
        model.getSolver().solve();
    }

    public static void main(String[] args) {
        new AircraftLanding().modelAndSolveMultipleRunways();
    }
}

```
So I believe this is not a problem related to choco.

**Comment by tao0708** [comment]
oh..., the values of y are still not right, it's weird..thanks very much for your patient.

**Comment by cprudhom** [comment]
Maybe you can describe your environment (IDE, OS, java version, command line, etc...) to have a better idea of goes wrong.

**Comment by tao0708** [comment]
Do you have ever solved the static multiple-runway aircraft landing problem using choco?, if do, can you share your code or materials about it with me? I'll be very appreciated.

**Comment by tao0708** [comment]
Do you have ever solved the static multiple-runway aircraft landing problem using choco?, if do, can you share your code or materials about it with me? I'll be very appreciated.

**Comment by cprudhom** [comment]
No we don't.

**Comment by tao0708** [comment]
okay,thanks a lot
