### ISSUE TITLE
MavenCentral does not have Choco 4.0.6

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#573]
### Expected behavior
Maven Central lists the latest release 4.0.6 and makes it available for maven/gradle builds.

Link from: https://github.com/chocoteam/choco-solver/
is
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.choco-solver%22%20AND%20a%3A%22choco-solver%22

### Actual behavior
4.0.5 is listed as the latest version.

**Comment by cprudhom** [comment]
Thank you. Something goes wrong in my release script, I thought I fixed it last time.
I'll have a look.
