### ISSUE TITLE
how to implement z[i][j] >= y[i][r] + y[j][r] using choco?

### ISSUE THREAD

**Issue by tao0708** [chocoteam/choco-solver#575]
IntVar[][] z = model.intVarMatrix("sameway_or_not", 10, 10, new int[]{0,1});
IntVar[][] y = model.intVarMatrix("runways", 10, 2, new int[]{0,1});
IntVar[] runway = model.intVarArray("runway", 10, 1, 2, false);

(1) z[i][j] >= y[i][r] + y[j][r] - 1; i = 1, ..., 10; j = 1, ..., 10; r = 1,2
(2) if runway[i] is equal to runway[j], then z[i][j] = 1
(3) if runway[j] is not equal to runway[j], then z[i][j] = 0

how to implement the above 3 constraints using choco?

**Comment by cprudhom** [comment]
Hi Tao, 

I bet you didn't read the [documentation](http://choco-solver.readthedocs.io/en/latest/) and [tutorials](http://choco-tuto.readthedocs.io/en/latest/). Could you, please ? That kind of questions are answered in them.

Best,

**Comment by tao0708** [comment]
I'v actually read the documentation and some of the tutorials, but i still can not implement them, maybe it's easy for you, but I'm newbie in choco, so please try to understand that. Many thanks.

**Comment by jgFages** [comment]
Do you know how to code in Java? If not we cannot help you (really).
If yes, then yes everything is in the documentation but in case you find this simpler to follow:

(in)equality constraints see line "arithm" there https://www.cosling.com/choco-solver/hello-world

iterations will be done by java for loops, not choco code (https://www.cosling.com/choco-solver/portfolio)

you have model.ifThen(A,B) constraints in choco solver (see official doc/samples or try it yourself)

**Comment by tao0708** [comment]
okay, i'll read the tutorials in deep, actually, i'v read the "arithm" "element"and etc, still, thanks for your two suggestions and answers.

**Comment by cprudhom** [comment]
Hi, 

Did you find answers to your questions ?

BEst,

**Comment by tao0708** [comment]
thanks for your concern, not yet, but i will put the answers into here if i find, then close the issue.

**Comment by cprudhom** [comment]
Here is a way to achieve this.

Best,

```java
BoolVar[][] z = model.boolVarMatrix("sameway_or_not", 10, 10);
BoolVar[][] y = model.boolVarMatrix("runways", 10, 2);
IntVar[] runway = model.intVarArray("runway", 10, 1,2, false);

for (int i = 0; i < 10; i++) {
    for (int j = 0; j < 10; j++) {
        for (int r = 0; r < 2; r++) {
            // (1) z[i][j] >= y[i][r] + y[j][r] - 1; i = 1, ..., 10; j = 1, ..., 10; r = 1,2
            model.scalar(
                    new IntVar[]{z[i][j], y[i][r], y[j][r]},
                    new int[]{1,-1,-1}, ">=", -1).post();
            // or:
            // z[i][j].ge(y[i][r].add(y[j][r].sub(-1))).post();
        }
        // (2) if runway[i] is equal to runway[j], then z[i][j] = 1
        // (3) if runway[j] is not equal to runway[j], then z[i][j] = 0
        model.arithm(runway[i], "=", runway[j]).reifyWith(z[i][j]);
    }
}
```

**Comment by tao0708** [comment]
Thanks, i will try your way, too. The below is also a way to solve above problem.

IntVar[][] z = model.intVarMatrix("sameway_or_not", 10, 10, new int[]{0,1});
IntVar[][] y = model.intVarMatrix("runways", 10, 2, new int[]{0,1});
IntVar[] runway = model.intVarArray("runway", 10, 1, 2, false);


//(2) if runway[i] is equal to runway[j], then z[i][j] = 1
// (3) if runway[j] is not equal to runway[j], then z[i][j] = 0
for(int i = 0; i < 10; i++ ){
    for(int j = 1; j < 10; j ++){
         model.ifThenElse(
		        model.arithm(runway[i],"!=",runway[j]),
		        model.arithm(z[i][j],"=",0),
		        model.arithm(z[i][j],"=",1)
	);
    }
}
