### ISSUE TITLE
setNoGoodRecordingFromSolutions potentially buggy

### ISSUE THREAD

**Issue by RobertHilbrich** [chocoteam/choco-solver#577]
The `setNoGoodRecordingFromSolutions` call does not work as expected when used twice with different variables and having posted constraints in between.

As briefly explained on gitter - here is the short example, that does not work as expected:
```java
  public class TestClass {
	public static void main(String[] args) throws ContradictionException {
	
	Model chocoModel = new Model("ASSIST");

		IntVar v1 = chocoModel.intVar("v1", 0, 3, false);
		IntVar v2 = chocoModel.intVar("v2", 0, 3, false);
		IntVar v3 = chocoModel.intVar("v3", 0, 1, false);
		
		chocoModel.getSolver().propagate();
				
		/* Default case - make sure only solutions differing in the v1, v2 values are returned */
		chocoModel.getSolver().setNoGoodRecordingFromSolutions(v1, v2);
				
		/* Adding a constraint */
		Tuples tuples = new Tuples();
		tuples.add(0, 0, 0);
		tuples.add(0, 1, 0);
		tuples.add(1, 1, 1);
		tuples.add(1, 2, 1);
		tuples.add(2, 2, 0);
		tuples.add(3, 3, 0);
		
		IntVar[] varArray = {v1, v2, v3};
		chocoModel.table(varArray, tuples, "GAC3rm+").post();
		
		/* Setting the optional case - show me only solutions that differ in v1 value */
		chocoModel.getSolver().setNoGoodRecordingFromSolutions(v2);

		List<Solution> solutions = chocoModel.getSolver().findAllSolutions();
		System.out.println(solutions.size()); // <- expecting 4 solutions, but getting 6
	}
}
```

**Comment by cprudhom** [comment]
Can you tell me which version of choco you are using ?
I wasn't able to reproduce the bug in 4.0.6.

**Comment by RobertHilbrich** [comment]
I am using choco 4.0.4 - something important related to nogoodprops changed during the two minor versions?

**Comment by cprudhom** [comment]
A bug related to nogoods was fixed, see [CHANGE.log of 4.0.5](https://github.com/chocoteam/choco-solver/releases/tag/4.0.5).

BTW, we are not very good at determining what is a minor version and a major one...

**Comment by RobertHilbrich** [comment]
I upgraded to 4.0.6. Everything works fine now - thank you. 
(Except: the `assert initialized`stuff see PR #576.)
