### ISSUE TITLE
FEATURE: add (getBestSolution|getSolution|streamSolutions) to parallel portfolio

### ISSUE THREAD

**Issue by boxxxie** [chocoteam/choco-solver#579]
Currently, the org.chocosolver.solver.search.IResolutionHelper functions return solutions or solution streams, and this is a very nice interface to write against. the solver and solution APIs are small, and easy to use. The parallel portfolio API is much harder to use, possibly double the code, as I can only ask for the models from a portfolio's solution via .getBestModel(). I then tried to get a Solution from the model given back, as my code, and me being new to choco, thought that i could only trust values that i got from a Solution. however i couldn't get that to work, and proceeded to extract my vars from the model instead.

having the portfolio return a solution, would be more intuitive, especially for new-comers. 

also, what is the expected behavior of parallel portfolio? (maybe i should look at it's tests).
i'm currently extending loco to cover as much as choco that makes sense to me, and my portfolio doesn't stop finding solutions to problems i give it, even problems with only a single IntVar.

## Environment
* Choco-solver version: 4.0.6
* Java version: 8 or 9
* Link to your project: loco

**Comment by cprudhom** [comment]
Fist, you should know that a `Solution` depends on a single `Model` because it refers to variables which can only exist in one model at a time.
`ParallelPortfolio` deals with `n-1` copies of a main model. It launches each of the `n` models in a thread with a different search strategy and waits for the first solution. 
If you want to read the solution, you need the model that is associated to it, that is why we have preferred to rely on the model.
Knowing that, if you have suggestions, you are very welcome.

About finiteness, can you extract a minimal working example ?

Best

**Comment by cprudhom** [comment]
> i have attempted to get a solution from a model provided by portfolio, but it would not extract the model's state

A Solution is a **copy** of a model's variables' domain at a particular state, when all domains are reduced to singleton (if I limit my example to IntVar): a `Solution` is simply a map from model's variables to an index + an array of ints, from index to value (of the IntVar in the solution). 

A Solution is created by a Solver, which is the only one that can claim that the current state of variables is a solution (all variables are instantiated, and all constraints are satisfied).

So, a single Model can be referred into multiple solutions, but each solution can only refer to a single model. The value of a variable `v` in a solution `s` can be read through `s` (calling, `s.getIntVal(v)`).

So, getting a solution from a model is not possible, you can't extract a model state from a solution, only read the variables' value.

>  maybe it's possible to create a parallelSolutionStream()? where portfolio is used and solutions are returned?

The major limitation comes from the fact that a model cannot be duplicated (there is no method for that and no willing the design such a method). The only way to create multiple instance of a problem is to the declare a method that creates and returns a `Model`. Plus, there is no **master** model from which we could generate solution, or at least, associate solution to.

> i've made the portfolio in clojure, so, i can describe what i'm doing or show some clojure code.

Without java code, I can't help on that point.

Hope it helps.

**Comment by boxxxie** [comment]
Wow, really cool that you guys patched this.

however, i just updated to the latest version of choco, and now i see that Solver.streamSolutions is gone.
but i don't see this mentioned in the change log.

can you give me an idea of where this functionality exists now?

**Comment by cprudhom** [comment]
Hi Paul, 

The API still exists, did you try to call the function ? 
Best, 
CP 


Charles Prud'homme 


De: "Paul Iannazzo" <notifications@github.com> 
À: "chocoteam/choco-solver" <choco-solver@noreply.github.com> 
Cc: "cprudhom" <cprudhom@mines-nantes.fr>, "Comment" <comment@noreply.github.com> 
Envoyé: Vendredi 24 Mai 2019 22:26:57 
Objet: Re: [chocoteam/choco-solver] FEATURE: add (getBestSolution|getSolution|streamSolutions) to parallel portfolio (#579) 



Wow, really cool that you guys patched this. 

however, i just updated to the latest version of choco, and now i see that Solver.streamSolutions is gone. 
but i don't see this mentioned in the change log. 

can you give me an idea of where this functionality exists now?

**Comment by boxxxie** [comment]
I got it working. I was expecting choco to have a fluent API, and was just confused by the return values from some functions on model. which is why I deleted the comment.
