### ISSUE TITLE
Documentation of and types in setGeometricalRestarts

### ISSUE THREAD

**Issue by pwn1** [chocoteam/choco-solver#586]
Hi,
I am using setGeometricalRestarts with TimeCounter in Choco 4.0.6 with a line like this to set a 1 second restart (then 1.5 seconds etc):

`model.getSolver().setGeometricalRestart(1000000000, 1.5, new TimeCounter(model, 1000000000), 1000000000);`

I'm assuming that the number given to TimeCounter has no effect because it is overwritten by the first argument of setGeometricalRestart. 

There are two bits of documentation I could find:
[The user guide](https://media.readthedocs.org/pdf/choco-solver/latest/choco-solver.pdf)

[Javadoc](http://www.choco-solver.org/apidocs/org/chocosolver/solver/search/loop/move/IMoveFactory.html#setGeometricalRestart-int-double-org.chocosolver.solver.search.limits.ICounter-int-)

They don't say the same thing about the first argument of setGeometricalRestart -- the javadoc one says it is a scale factor. I'll assume the other one is correct. 

Second thing is the first argument of setGeometricalRestart is an int, which is not suitable for holding time limits expressed in nanoseconds. I wonder also if the geometric progression is calculated with ints, and would overflow after a small number of restarts in the example above. 

So I'd like to suggest:
1. changing the first argument of setGeometricalRestart to a long.
2. Updating the Javadoc to be consistent with the user manual
3. A clearer statement in the Javadoc and the user manual that the argument given to TimeCounter/BacktrackCounter is actually never used.

**Comment by cprudhom** [comment]
Hi,

I'll fix that.
In the future, we may consider extract the counter concept from `ICounter` which mix up observer and limitation behavior.
Restart strategy only required a counter, it manages its own limit.

**Comment by pwn1** [comment]
Great, thanks.
