### ISSUE TITLE
Mutiplication of IntVar by Int as objective

### ISSUE THREAD

**Issue by wilnzi** [chocoteam/choco-solver#587]
HI,
I'm very beginner to choco. 
I want to create a objective variable by mutiplying IntVar parameter by Int value. 
Please can you tell me, how can i make it ? 

Thanks in advance.

**Comment by cprudhom** [comment]
Hi,

Have a look at `scalar` constraint. 

You can find examples of such usage in http://choco-tuto.readthedocs.io/en/latest/

Best,
