### ISSUE TITLE
How to get the value of x which belongs to the previous  solution?

### ISSUE THREAD

**Issue by tao0708** [chocoteam/choco-solver#590]
Hi,
    If I want to get the displacement of x, then i need to get the previous x' in the previous solution, how to get the previous value in choco?
    Anyone has the tutorial about this?  

Many thanks from tao.

**Comment by cprudhom** [comment]
Hi,

You have to either store the value or the solution during resolution in order to be able to do that.

Have a look at the tutorial here: https://choco-tuto.readthedocs.io/en/latest/src/303.code.html?highlight=solve()

Best,
CP
