### ISSUE TITLE
More than one file was found with OS independent path 'gDay.aut'

### ISSUE THREAD

**Issue by Pascal66** [chocoteam/choco-solver#593]
Gradle compilation error
seems conflit with automaton and something else ?

* Choco-solver version: 4.0.8
* Java version: 8

**Comment by ingambe** [comment]
I've got the same error with Android Studio
The solution for me was to download the latest jar release
Then add the following options inside android { ... } to compile with Android 8:
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}

**Comment by Pascal66** [comment]
C'est en effet la seule solution pour le moment.
Modifying the jar..
Wish we can use it out of the box soon.
(Nice work about Awale Pierre)
