### ISSUE TITLE
How to start from a known solution?

### ISSUE THREAD

**Issue by MatthGond** [chocoteam/choco-solver#597]
Hi, 

I have a problem with a Choco implementation .
I know a high quality solution computed thanks to a heuristic.
I know that this solution is very closed to the optimal one.... probably...90% of the variables have the correct value... in other terms only 10% of the variables have to be changed to give the optimal ones.

I would like to start Choco with this solution and to make a LDS exploration considering the X variable that are the main variable of my model.

I have tried : 
 "Solution solution = new Solution(mon_modele);
 solution.setIntVal(a[1], 1);
 solution.setIntVal(a[2], 2);
 ...
  INeighbor nbh = INeighborFactory.propagationGuided(a);
  nbh.loadFromSolution(solution);
  mon_solveur.setLNS(nbh);
"
It does not work. The solution is not taken into account by the solver.
Hours of researches in internet failed.

Someone has a solution ?

Thanks

**Comment by cprudhom** [comment]
I created a [notebook to answer your question](https://hub.mybinder.org/user/chocoteam-notebooks-1o321hyg/notebooks/Loading_a_solution.ipynb).
I hope you find everything you need. 

Best

**Comment by pjharding** [comment]
I found that notebook super helpful. Thank you!

**Comment by cprudhom** [comment]
@pjharding Nice, I'll try to keep on writing some
