### ISSUE TITLE
BUG: Sometimes, the `sum` constraint provides a wrong result

### ISSUE THREAD

**Issue by xgillard** [chocoteam/choco-solver#601]
## Description
Sometimes, the `sum` constraint provides wrong result. It either discards solutions or fails to identify contradiction. 

## Context
I am currently writing and validating a library specifically aiming at in-depth testing of CP constraints. I applied it on choco-4.0.8 to validate my work. I hereby report the bugs which have automatically been found.

## Expected behavior
Consider the example: `x0= {2147483636} > -581118` . Obviously, this constraint should always be true. However, choco treats it as if it were always false.

## Environment
* Choco-solver version: 4.0.8
* Java version: 1.10
* Link to your project: https://bitbucket.org/xaviergillard/solvercheck/

## Possible Solution
As far as I know, it is caused by an underflow happening at line 114 of class `IntLinCombFactory`. It might not be trivial to solve though. Maybe this class should use `long` everywhere instead of `int`.

## Reproducing the "bug" and Actual behavior
Please consider running the enclosed JUnit test suite. It reproduces the findings and documents them. [SumIsSubjectToUnderflow.java.txt](https://github.com/chocoteam/choco-solver/files/2478166/SumIsSubjectToUnderflow.java.txt)

**Comment by cprudhom** [comment]
First of all, thank you for helping us improving choco.

In Java, there is no error on integer overflow/underflow.
That mostly impacts the sum constraint.
I can (and I will) easily fix the issues you detected but that is not enough.
But, the problem is more complex than that and to prevent that, we use to tell users not to declare too big domains (which is not satisfying too).

CP

**Comment by xgillard** [comment]
It's true that having the JVM throw an exception in case of over/underflow would be nice. 
You may call your solution of "reasonable domain size" not satisfactory, but I think its ok. Moreover, from what I've seen choco is remarkably robust at preventing this kind of error and explaining it to the user ;-)
