### ISSUE TITLE
BUG: AllDifferent constraint invokes the `PropAllDiffInst` propagator on variables that are not instantiated. 

### ISSUE THREAD

**Issue by xgillard** [chocoteam/choco-solver#603]
## Description
In some cases, choco's alldiff constraint invokes the `PropAllDiffInst` propagator
on variables that are not instantiated. This violates the preconditions of that 
propagator and therefore, results in an AssertionError being thrown.

## Impact
I have seen the bug occur on the alldifferent constraint with "BC" consistency and with "DEFAULT" consistency. A trace to reproduce the bug is provided for each of these flavors of the constraint.

## Context
I am currently writing and validating a library specifically aiming at in-depth 
testing of CP constraints. I applied it on choco-4.0.8 to validate my work. 
I hereby report the bugs which have automatically been found.

## Expected behavior
The propagator should not be invoked when its preconditions are not satisfied.

## Environment
* Choco-solver version: 4.0.8
* Java version: 1.10
* Link to your project: https://bitbucket.org/xaviergillard/solvercheck/

## Possible Solution
I honestly have no idea on how to fix this bug. My intuition (and firs _partial_ 
investigations) tell me that it is caused by some stale data left in the 
`eventmask` of the propagator. But this is really just an intuition. 

## Reproducing the bug + Demonstration of the actual behavior
Please consider running the enclosed JUnit test suites, they reproduce the bug. 
The enclosed tests are long (I apologize for that). They simply execute a trace 
which always leads to a state in which the bug occurs. This trace should really 
be understood as the log of some choco-search: digging down in the search space,
backtracking and digging back again.

*Note* Given that the suite for the AllDifferent + "DEFAULT" is much shorter than for the "BC" 
version, I would advise you to start your investigations with the former.

*Note* If that is of any help, I can either produce new traces for you or 
provide you with a maven project containing the test suites written with 
solvercheck.
[AllDiffDefaultInvokesPropAllDiffWithVariablesThatAreNotInstantiated.java.txt](https://github.com/chocoteam/choco-solver/files/2480761/AllDiffDefaultInvokesPropAllDiffWithVariablesThatAreNotInstantiated.java.txt)

[AllDiffBcInvokesPropAllDistInstWithVariablesThatAreNotInstatiated.java.txt](https://github.com/chocoteam/choco-solver/files/2480683/AllDiffBcInvokesPropAllDistInstWithVariablesThatAreNotInstatiated.java.txt)

**Comment by cprudhom** [comment]
Hi, first of all thank you for the bug report.

Something that is missing in your test suites that is required by choco.
Indeed, when a contradiction occurs, you need to flush pending events from the propagation engine. Otherwise, unexpected behavior may occur.
```java
try {
    choco.postTemp(choco.arithm(x, op, cst));
    choco.getSolver().propagate();
} catch (ContradictionException idontcare) {
    choco.getSolver().getEngine().flush();
}
```

Regarding your test, I agree with the starting domains and the decision (x3 < 1) but not with the expected domains and the actual domains.
The expected domains should be: `x0={3630704,3630705,3630709}, x1={3630702,3630703,3630705,3630709}, x2={3630701,3630704,3630705,3630710}, x3={3630700}, x4={3630704,3630709}`, which is actually found by the propagation.

PS: I simplify `363070i` to `i` in my tests.

CP

**Comment by xgillard** [comment]
Thank you for your swift reply. Sorry, I wasn't aware of the need to call `choco.getSolver().getEngine().flush()`. This is more than likely the cause of the error I've stumbled upon. 

Regarding the "expected state": I really should have trimmed it from my bug  report. When I faced the error, I was simply experimenting with my lib and choco. So I compared choco's alldiff with an (inefficient and bruteforce) _range consistent_ propagator for alldiff. Doing that test, I wanted to make sure that my lib reported an error telling me that choco AllDifferentBC (or choco AllDiffferent default) != range consitent. Hence the "expected state" is really that of the other range consistent filter. Not by any means what I considered choco should've returned.

**Comment by cprudhom** [comment]
Well, I will not do that for the following reason: `worldPop/Push` operations are related to the environment, that makes sure everything is OK on backtrack. `engine.flush()` operation is related to the propagation. There is nothing that forces those two mechanism to work synchronously and I can't presume how they would be used. 
In addition, most of the time, those operations are left to `Solver`.

One thing I can consider is to surround `solver.propagate()` with a `catch` that automatically flushe the propagation engine..
