### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by cespio** [chocoteam/choco-solver#609]
Hi,
I am Francesco from the University of Trento,
I am working on a project with other researchers and we encountered a difficulty when using Choco on a couple of instances (attached here: [choco-instances.zip](https://github.com/chocoteam/choco-solver/files/2649094/choco-instances.zip)), which we was hoping you could kindly help us with. 
In essence, the problem is that Choco is able to find an optimal solution, whereas all other tested solvers
(OptiMathSAT, Picat, Gecode, HaifaCSP, G12-FD, iZplus,OR-tool), return UNSAT.
The minizinc problem was encoded as a flatzinc instance using the Choco library of global constraints (we tried also to translate the minizinc input into flatzinc without using the library of global constraints and the result didn't change). The tool was run with the command:

`java -cp .: path/to/choco-parsers-4.0.4-with-dependencies.jar org.chocosolver.parser.flatzinc.ChocoFZN file.fzn`

We used this version of the tool: choco-parsers-4.0.4-with-dependencies

Thanks for your assistance,
Best Regards

**Comment by cprudhom** [comment]
Thank you for the bug reporting.
There is something in the flatzinc file that is detected as an inconsistency by other solver:
```
constraint bool_eq(X_INTRODUCED_2817_,false);
constraint array_bool_and([],X_INTRODUCED_2817_):: defines_var(X_INTRODUCED_2817_);
```
I assume that the other solvers interpret the second constraint as "X_INTRODUCED_2817_ is true", which contradicts the first constraint.

Maybe I should also consider that "void -> true" instead of "void -> undef".

Best regards,
CP

**Comment by cprudhom** [comment]
Or simply that the constraint is not correctly defined.

**Comment by cprudhom** [comment]
I presume that you didn't want to create a trivially inconsistent model, right ?

**Comment by cespio** [comment]
The original file does not seem to contain any trivial inconsistency, it is possible that this is the result of mzn2fzn processing
