### ISSUE TITLE
Maven central does not have Choco 4.10.0

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#610]
Thank you for the release of Choco 4.10.0!

It seems that the new release is not available at Maven central, the newest one is 4.0.9.
https://mvnrepository.com/artifact/org.choco-solver/choco-solver

Maybe there is a problem with the relasese script?

Best,
Juha

**Comment by cprudhom** [comment]
That's fixed now. But I can't figure out why it doesn't work the first time.

CP
