### ISSUE TITLE
Null pointer exception in hardReset()

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#611]
In choco 4.10.0 hardReset() in Solver.class throws null pointer exception at line 554 "this.M.getStrategy().remove();" in some cases, i.e. when there is no need to call a hard reset.
 ```
public void hardReset() {
        reset();
        this.M.getStrategy().remove();

```
A MWE is 
```
public class HardReset {

    public static void main(String[] args) {
        Model m = new Model();
        IntVar i = m.intVar("i", 1, 2);
        m.getSolver().hardReset();
```

Yes, I do have a bug in my code in tracing solver state - calling hard reset in a case where it is not really needed. Or it might also be seen as defensive programming ;-)
Anyway, a fix is desirable.
(Java 8, win + Linux)

**Comment by bios8086** [comment]
I also found this problem.
