### ISSUE TITLE
BoundSearch.getDecision() creating wrong decision?

### ISSUE THREAD

**Issue by ThisIsMyGitAcct** [chocoteam/choco-solver#615]
[BUG]  Just read your BIVS paper and am walking thru the BoundSearch code for the first time. It appears you have a bug, in one case it can create a decision with the wrong value.  In getDecison(), in the block when the domSize is within spec, and the var is NOT enumerated, the makeIntDecision call (ln 82) is getting its value from Math.min(lbB,ubB).   In turn, lbB/ubB are set from the return val of calls to bound() (ln 77/78). BUT bound() return a cost value relative to the objective var (ln 107/109), not the bounds of the var in question.   So this decision will attempt to bind the variable to a value from the objective (possibly even the objective's negated UB), not its own domain.

## Expected behavior

The value selection logic at line 82 should be the same as that from line 133.

## Possible Solution

The value selection logic at line 82 should be the same as that from line 133.

## Steps to Reproduce (for bugs)

1. Read the code.
2. Think about what it does.
3. Realize its wrong.

1.
2.
3.
4.

## Environment

* Choco-solver version:
* Java version:
* Link to your project:

**Comment by cprudhom** [comment]
Hi,

Thank you for the bug report.
Obviously, l.89 should be modified to get the bound that minimizes the cost.

Best
