### ISSUE TITLE
maven repository does not have the library version of Choco 

### ISSUE THREAD

**Issue by clo-vis** [chocoteam/choco-solver#616]
Since version 4.0.7, the maven repository contains only a huge jar with all dependencies used by Choco. It should contain the version **without** dependencies.

According to the [documentation](https://choco-solver.readthedocs.io/en/latest/1_overview.html#with-maven)

> Note that the artifact does not include any dependencies.

And according to the README:

> Note that if your program depends on dependencies declared in the jar file, you should consider using choco as a library.

And later:
> As a library
The jar file does not contains any dependencies, as of being used as a dependency of another application.

**Comment by integratedmodelling** [comment]
Endorsed - the Maven distribution is unusable as is, the configuration in pom.xml must be fixed to not include dependencies. This problem prevents any usage of the library in production.

**Comment by cprudhom** [comment]
I'm going to fix that in the near future

**Comment by smorel-plenty** [comment]
@cprudhom Is this still on your radar? Is https://github.com/yunglin/choco-solver/commit/b2f4b449ec0b2b498651c841dfc48dc638730a4f still a workable alternative?

**Comment by cprudhom** [comment]
Yes it is. You can have a look at the pom.xml and/or run `mvn package` to have an idea of what the next release will look like. But, to be honest, I'm running out of time to prepare the next release
