### ISSUE TITLE
Problem with Model.intGeView()

### ISSUE THREAD

**Issue by mr-tl** [chocoteam/choco-solver#617]
In our non public Choco model we have code on the form:

    final IntVar[] xs = model.intVarArray(10, 0, 9);
    final BoolVar[] bs = Stream.of(xs).map(x -> model.intGeView(x, 1)).toArray(BoolVar[]::new);

    final IntVar count = model.intVar(0, 10);
    model.sum(bs, "=", count).post();

Our model produced wrong solutions, and after debugging we found
out that:

* The domain size of all `bs` are 10, and not 2 that we had
  expected. It seems the domain size of the underlying `IntVar` is
  used.

* Replacing (only) the code `model.intGeView(x, 1)` above by
  `model.arithm(x, ">", 0).reify()` makes our model produce
  correct solutions. In addition the domain size of all `bs` are then 2,
  as expected.

* During debugging (and still using `intGeView()`), we replaced 
  `model.sum(bs, "=", count).post();` by `model.sum(bs, "<=", count).post();
  model.sum(bs, ">=", count).post();`. This made the solver (from producing 
  a solution within seconds) not producing any solution within reasonable time.

I apologise that this report does not contain a reproducing
example of the bug that produce wrong solutions, but hope that it
is still useful.

Choco version: 4.10.0
Java version: 11.0.1
Operating system: Linux Kernel 5.0.2

Best regards,

Magnus

**Comment by cprudhom** [comment]
I fix the issue (thank you for reporting it).
This was related to a missing method implementation in views.

This should work now (you can try the snapshot version, or wait for a release).

Best,
CP

**Comment by mr-tl** [comment]
I just tested 4.10.1 and have the following input: 

Using `Model.intGeView(x, 1)` is _still not equivalent_ to using `Model.arithm(x, ">", 0).reify()`. I have not investigated this in depth, but the former generates much worse solutions to our problem.

Best regards,

Magnus

**Comment by cprudhom** [comment]
@mr-tl Can you extract a minimal working examples (or many) ?

**Comment by mr-tl** [comment]
> @mr-tl Can you extract a minimal working examples (or many) ?

I'll try to find time to isolate it. /Magnus

**Comment by mr-tl** [comment]
@cprudhom I believe I have a small enough example for you:

The following program:

```
        final Model model = new Model();
        final IntVar[] vars = model.intVarArray(1000, 0, 1000);
        model.allDifferent(vars).post();

        final IntVar[] ges = Stream.of(vars).map(v -> model.intGeView(v, 10)).toArray(IntVar[]::new);

        final IntVar sum = model.intVar(0, ges.length);
        model.sum(ges, "=", sum).post();

        if (model.getSolver().solve()) {
            System.out.println("Solution found");
        } else {
            System.out.println("No solution found");
        }
```

This program generates "No solution found". Replacing the line
```
final IntVar[] ges = Stream.of(vars).map(v -> model.intGeView(v, 10)).toArray(IntVar[]::new);
```
by
```

**Comment by mr-tl** [comment]
@cprudhom I believe I have a small enough example for you:

The following program:

```
final Model model = new Model();
final IntVar[] vars = model.intVarArray(1000, 0, 1000);
model.allDifferent(vars).post();

final IntVar[] ges = Stream.of(vars).map(v -> model.intGeView(v, 10)).toArray(IntVar[]::new);

final IntVar sum = model.intVar(0, ges.length);
model.sum(ges, "=", sum).post();

if (model.getSolver().solve()) {
    System.out.println("Solution found");
} else {
    System.out.println("No solution found");
}
```

This program generates "No solution found". By replacing the line
```
model.intGeView(v, 10)
```
by
```
model.arithm(v, ">=", 10).reify()
```
the program generates "Solution found".

This is all running Choco 4.10.2.

Please let me know if something is wrong or unclear.

**Comment by mr-tl** [comment]
@cprudhom I believe I have a small enough example for you:

Consider the following program:

```
final Model model = new Model();
final IntVar[] vars = model.intVarArray(1000, 0, 1000);
model.allDifferent(vars).post();

final IntVar[] ges = Stream.of(vars).map(v -> model.intGeView(v, 10)).toArray(IntVar[]::new);

final IntVar sum = model.intVar(0, ges.length);
model.sum(ges, "=", sum).post();

if (model.getSolver().solve()) {
    System.out.println("Solution found");
} else {
    System.out.println("No solution found");
}
```

This program generates "No solution found". 

By replacing the line
```
model.intGeView(v, 10)
```
by
```
model.arithm(v, ">=", 10).reify()
```
the program generates "Solution found".

This is all running Choco 4.10.2.

Please let me know if something is wrong or unclear.

**Comment by cprudhom** [comment]
Thank you. I'm able to reproduce the bug and found what is wrong.
Now, I need to find a patch.
I let you know.

**Comment by mr-tl** [comment]
Great!

A question that arises here is the status of the other `view` operators (some of which we use). Could they also be affected by this problem?

**Comment by cprudhom** [comment]
Only `eq` and `leq` views were affected by the problem. The other ones (`scale`, `offset`, `minus` and `not`) act in a different way.
