### ISSUE TITLE
[BUG] Solver.hardReset() on an unmodified solver causes NPE

### ISSUE THREAD

**Issue by mr-tl** [chocoteam/choco-solver#622]
When calling `hardReset()` on a fresh `new Model().getSolver()`, a null pointer exception is thrown due to the move's strategy being null.

## Expected behavior

The `hardReset()` should be a no op.

## Actual behavior

The `hardReset()` causes a NPE.

## Steps to Reproduce (for bugs)

1. `new Model().getSolver().hardReset()`

## Environment

* Choco-solver version: 4.10.0
* Java version: 11.0.1

**Comment by ArthurGodet** [comment]
Hello,

This bug has been reported in issue #611 and has been corrected. This behaviour won't happen in next release.

Thank you for reporting.
