### ISSUE TITLE
PrintDecisions() not found

### ISSUE THREAD

**Issue by MehdiZrhal** [chocoteam/choco-solver#625]
Dear, 

I'm trying to print the decisions made by the solver. As shown in the documentation page 27 of Choco 4.10.0 , I tried to use  solver.printDecisions() but such function dosen't exist in the distribution. Can you please tell me if I'm missing something? 

Thanks in advance.

**Comment by ArthurGodet** [comment]
Hi,

I think it is a typo in the documentation. The function printDecisions() does not exist indeed. The documentation should talk about the function showDecisions() (as it does a few lines above in page 27 of the documentation).

Thank you for your report.

**Comment by MehdiZrhal** [comment]
Thank you for your help.
