### ISSUE TITLE
Array out of bound exception in PropLexInt

### ISSUE THREAD

**Issue by jgFages** [chocoteam/choco-solver#630]
https://github.com/chocoteam/choco-solver/blob/b441aa951fc024baa589cb38f97b5bcd21d954a7/src/main/java/org/chocosolver/solver/constraints/nary/lex/PropLexInt.java#L98

I believe ESat.TRUE should be returned instead.

Seems to come from a copy/paste of PropLex in which there is no array out of bound, but which could still be simplified by returning ESat.TRUE as well

**Comment by cprudhom** [comment]
That is a wrong copy/paste, it should return `TRUE` if all x[i]  == y[i].
