### ISSUE TITLE
[BUG] Combine IfThen-Constraints with and/or-Constraints

### ISSUE THREAD

**Issue by MaUt89** [chocoteam/choco-solver#632]
Hi everyone,

I am currently working on a project for my PhD using the Choco Solver. I am basically creating  constraints programmatical from String-Arrays and this works fine for simple approaches as:
If x=1 then y=0
model.IfThen(
   model.arithm(x, "=", 1), 
   model.arithm(y, "=", 0)
);

But I would like to do some more sophisticated constraints as:
If (x=1 and y=0) then z = 1

At the moment I try to combine therefore the IfThen-constraint with the and-constraint, which looks like the following:
model.IfThen(
   model.and(
      model.arithm(x, "=", 1),
      model.arithm(y, "=", 0))
   ),
   model.arithm(z, "=", 1)
);

The syntax is correct, but, unfortunatly, it seems like the solver does not reify the constraints correctly, since the result from my simple example is not correct. Same holds true if I try to combine the IfThen-constraint with an or-constraint.

In the following an current example:
First model:
Variables:
CPU = CPUs
MB = MBdiamond
RAM = RAM4
RAM = RAM8
...................................................................
CPU CPUs assign MB MBdiamond  
CPU CPUs AND MB MBdiamond assign RAM RAM4  
CPU CPUs incompatible RAM RAM8  
MB MBdiamond incompatible RAM RAM8  
...................................................................
REIFICATIONCONSTRAINT --> REIF_1 = [0,1]=>ARITHM ([CPU = 1]), !REIF_1 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_2 = [0,1]=>ARITHM ([CPU = 1]), !REIF_2 = [0,1]=>ARITHM ([CPU =/= 1])
ARITHM --> ARITHM ([prop(REIF_2.GEQ.REIF_1)])
REIFICATIONCONSTRAINT --> REIF_3 = [0,1]=>ARITHM ([CPU = 1]), !REIF_3 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_4 = [0,1]=>ARITHM ([MB = 1]), !REIF_4 = [0,1]=>ARITHM ([MB =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_3, REIF_4, IV_5)])
REIFICATIONCONSTRAINT --> REIF_6 = [0,1]=>ARITHM ([IV_5 = 2]), !REIF_6 = [0,1]=>ARITHM ([IV_5 =/= 2])
REIFICATIONCONSTRAINT --> REIF_7 = [0,1]=>ARITHM ([CPU = 1]), !REIF_7 = [0,1]=>ARITHM ([CPU =/= 1])
ARITHM --> ARITHM ([prop(REIF_7.GEQ.REIF_6)])
REIFICATIONCONSTRAINT --> REIF_8 = [0,1]=>ARITHM ([CPU = 1]), !REIF_8 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_9 = [0,1]=>ARITHM ([CPU = 1]), !REIF_9 = [0,1]=>ARITHM ([CPU =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_8, REIF_9, IV_10)])
ARITHM --> ARITHM ([IV_10 =/= 2])
REIFICATIONCONSTRAINT --> REIF_11 = [0,1]=>ARITHM ([MB = 1]), !REIF_11 = [0,1]=>ARITHM ([MB =/= 1])
REIFICATIONCONSTRAINT --> REIF_12 = [0,1]=>ARITHM ([CPU = 1]), !REIF_12 = [0,1]=>ARITHM ([CPU =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_11, REIF_12, IV_13)])
ARITHM --> ARITHM ([IV_13 =/= 2])
...................................................................
No solution has been found!
Model[Model-0], 0 Solutions, Resolution time 0,083s, 0 Nodes (0,0 n/s), 0 Backtracks, 0 Backjumps, 1 Fails, 0 Restarts

I would expect at least one solution, namely:

CPU = CPUS
MB = MBdiamond
RAM = RAM4

Any guesses how to do it right?

* Choco-solver version: 4.10
* Java version: 12

Thank you very much.

Cheers,

Mathias

**Comment by ArthurGodet** [comment]
Hi,
The example "If (x=1 and y=0) then z = 1" with the code you gave works fine for me. If x, y and z are all BoolVar and the only constraint is the one above, the only combination that would not be a solution is (1,0,0), which is exactly what found Choco.

Is it possible to have your Java code, to be sure what your variables and constraints are, please ?

Arthur

**Comment by MaUt89** [comment]
Thanks for the immediate response.

I found the issue, the constraints were not created correctly a small bug in my code I did not notice before was the issue, not choco...as usual the problem sits in front of the machine ;)

By the way I am not only using BoolVars as shown in the now working more complex example:

First model:
CPU = CPUs
CPU = CPUd
MB = MBsilver
MB = MBdiamond
RAM = RAM4
RAM = RAM8
...................................................................
CPU CPUs assign MB MBdiamond  
CPU CPUd allow MB MBsilver MBdiamond  
CPU CPUs AND MB MBdiamond assign RAM RAM4  
CPU CPUd OR MB MBsilver assign RAM RAM8  
CPU CPUs incompatible MB MBsilver  
CPU CPUs incompatible RAM RAM8  
CPU CPUd incompatible RAM RAM4  
MB MBsilver incompatible RAM RAM4  
MB MBdiamond incompatible RAM RAM8  
...................................................................
REIFICATIONCONSTRAINT --> REIF_1 = [0,1]=>ARITHM ([CPU = 1]), !REIF_1 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_2 = [0,1]=>ARITHM ([MB = 2]), !REIF_2 = [0,1]=>ARITHM ([MB =/= 2])
ARITHM --> ARITHM ([prop(REIF_2.GEQ.REIF_1)])
REIFICATIONCONSTRAINT --> REIF_3 = [0,1]=>ARITHM ([MB = 1]), !REIF_3 = [0,1]=>ARITHM ([MB =/= 1])
REIFICATIONCONSTRAINT --> REIF_4 = [0,1]=>ARITHM ([MB = 2]), !REIF_4 = [0,1]=>ARITHM ([MB =/= 2])
SUM --> SUM ([PropXplusYeqZ(REIF_3, REIF_4, IV_5)])
REIFICATIONCONSTRAINT --> REIF_6 = [0,1]=>ARITHM ([CPU = 2]), !REIF_6 = [0,1]=>ARITHM ([CPU =/= 2])
REIFICATIONCONSTRAINT --> REIF_7 = [0,1]=>ARITHM ([IV_5 >= 1]), !REIF_7 = [0,1]=>ARITHM ([IV_5 <= 0])
ARITHM --> ARITHM ([prop(REIF_7.GEQ.REIF_6)])
REIFICATIONCONSTRAINT --> REIF_8 = [0,1]=>ARITHM ([CPU = 1]), !REIF_8 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_9 = [0,1]=>ARITHM ([MB = 2]), !REIF_9 = [0,1]=>ARITHM ([MB =/= 2])
SUM --> SUM ([PropXplusYeqZ(REIF_8, REIF_9, IV_10)])
REIFICATIONCONSTRAINT --> REIF_11 = [0,1]=>ARITHM ([IV_10 = 2]), !REIF_11 = [0,1]=>ARITHM ([IV_10 =/= 2])
REIFICATIONCONSTRAINT --> REIF_12 = [0,1]=>ARITHM ([RAM = 1]), !REIF_12 = [0,1]=>ARITHM ([RAM =/= 1])
ARITHM --> ARITHM ([prop(REIF_12.GEQ.REIF_11)])
REIFICATIONCONSTRAINT --> REIF_13 = [0,1]=>ARITHM ([CPU = 2]), !REIF_13 = [0,1]=>ARITHM ([CPU =/= 2])
REIFICATIONCONSTRAINT --> REIF_14 = [0,1]=>ARITHM ([MB = 1]), !REIF_14 = [0,1]=>ARITHM ([MB =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_13, REIF_14, IV_15)])
REIFICATIONCONSTRAINT --> REIF_16 = [0,1]=>ARITHM ([IV_15 >= 1]), !REIF_16 = [0,1]=>ARITHM ([IV_15 <= 0])
REIFICATIONCONSTRAINT --> REIF_17 = [0,1]=>ARITHM ([RAM = 2]), !REIF_17 = [0,1]=>ARITHM ([RAM =/= 2])
ARITHM --> ARITHM ([prop(REIF_17.GEQ.REIF_16)])
REIFICATIONCONSTRAINT --> REIF_18 = [0,1]=>ARITHM ([CPU = 1]), !REIF_18 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_19 = [0,1]=>ARITHM ([MB = 1]), !REIF_19 = [0,1]=>ARITHM ([MB =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_18, REIF_19, IV_20)])
ARITHM --> ARITHM ([IV_20 =/= 2])
REIFICATIONCONSTRAINT --> REIF_21 = [0,1]=>ARITHM ([CPU = 1]), !REIF_21 = [0,1]=>ARITHM ([CPU =/= 1])
REIFICATIONCONSTRAINT --> REIF_22 = [0,1]=>ARITHM ([RAM = 2]), !REIF_22 = [0,1]=>ARITHM ([RAM =/= 2])
SUM --> SUM ([PropXplusYeqZ(REIF_21, REIF_22, IV_23)])
ARITHM --> ARITHM ([IV_23 =/= 2])
REIFICATIONCONSTRAINT --> REIF_24 = [0,1]=>ARITHM ([CPU = 2]), !REIF_24 = [0,1]=>ARITHM ([CPU =/= 2])
REIFICATIONCONSTRAINT --> REIF_25 = [0,1]=>ARITHM ([RAM = 1]), !REIF_25 = [0,1]=>ARITHM ([RAM =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_24, REIF_25, IV_26)])
ARITHM --> ARITHM ([IV_26 =/= 2])
REIFICATIONCONSTRAINT --> REIF_27 = [0,1]=>ARITHM ([MB = 1]), !REIF_27 = [0,1]=>ARITHM ([MB =/= 1])
REIFICATIONCONSTRAINT --> REIF_28 = [0,1]=>ARITHM ([RAM = 1]), !REIF_28 = [0,1]=>ARITHM ([RAM =/= 1])
SUM --> SUM ([PropXplusYeqZ(REIF_27, REIF_28, IV_29)])
ARITHM --> ARITHM ([IV_29 =/= 2])
REIFICATIONCONSTRAINT --> REIF_30 = [0,1]=>ARITHM ([MB = 2]), !REIF_30 = [0,1]=>ARITHM ([MB =/= 2])
REIFICATIONCONSTRAINT --> REIF_31 = [0,1]=>ARITHM ([RAM = 2]), !REIF_31 = [0,1]=>ARITHM ([RAM =/= 2])
SUM --> SUM ([PropXplusYeqZ(REIF_30, REIF_31, IV_32)])
ARITHM --> ARITHM ([IV_32 =/= 2])
...................................................................
1
CPU = CPUs
MB = MBdiamond
RAM = RAM4
2
CPU = CPUd
MB = MBsilver
RAM = RAM8
Model[Model-0], 2 Solutions, Resolution time 0,046s, 3 Nodes (65,2 n/s), 3 Backtracks, 0 Backjumps, 0 Fails, 0 Restarts

If someone is interested in more information regarding my project, please don't hesitate to contact me :)

You may close the thread.

Mathias
