### ISSUE TITLE
Initialize a solution

### ISSUE THREAD

**Issue by semantoro** [chocoteam/choco-solver#635]
Hi Team, 
I ask if there is a method chcoc where by i can initialze a solution or some variables.
The probleme is i have a solution and i wanna get an other based on the first one.
I'm on the last version of choco.

Best regards.

**Comment by cprudhom** [comment]
Hi,

Could you more precise ? 
In choco, you can initialize a resolution on a solution but that only matters when you use LNS.
Otherwise, there is no easy way to achieve such a thing.

Best

**Comment by semantoro** [comment]
OK thank you Charles, 
I wanna search the closest solution to a given solution after some added constraints.
Actually, I optimize the distance between the first solution (initial problem) and the solution(changed problem). 
I wanna do better than this if there is a specific method whereby we can initialize a partial/total assignation then search the new solution based on the first one.

Thank you very much for your response.

**Comment by semantoro** [comment]
Hi Charles,
I found some _**solver.set LNS(INeighborFactory**_ , is this how i can give the first solution as parameter?

Best

**Comment by cprudhom** [comment]
Sure, but it only works to trigger LNS.
In your case, if you want to find a solution closed to another one, you can define your own enumeration strategy (which goes to your solution) and use Limited Discrepancy Search (setLDS) to get closer to it.

**Comment by semantoro** [comment]
Hi Charles, 
I so sorry to back to you again , 
But,  if can you give me a small example to implement your proposition, 
Let take a small problem with 4 variables X (x1=0, x2=1, x3=4,x4=0) as an initial solution and we looking for a closed solution to this one after adding some new constraints o my problem (c1, c2).
When you said enumeration strategy is some thing applied after finding a new solution which is obliviously (from scratch and not based on the first one.  

thank you Charles for your feedback.

**Comment by ingambe** [comment]
@semantoro If I have correctly understood what you want to do, I think I've encountered the same need as you and, as it was suggested to me by Charles, you can use the [IntDomainLast](http://www.choco-solver.org/apidocs/org/chocosolver/solver/search/strategy/selectors/values/IntDomainLast.html) search strategy.

**Comment by cprudhom** [comment]
Is it still on or can I close the issue?

**Comment by semantoro** [comment]
You can close it
thank you very much.
