### ISSUE TITLE
Ginsberg Minimal perturbation

### ISSUE THREAD

**Issue by semantoro** [chocoteam/choco-solver#640]
Hi team, 
I wanna implement a minimal perturbation Ginsberg strategy on Choco(latest version).
It's an obviously the new strategy that I should implement if you can give me some tips especially what interfaces or classes I must implement, overwrite.
Cordialy.

**Comment by semantoro** [comment]
Thank you very much Charles, 
I will implement this as recommended and return to you for feedback.
Cordially.

**Comment by cprudhom** [comment]
Is it still on or can I close the issue?
