### ISSUE TITLE
[BUG] Adding stop criterion after `Solver.hardReset()` failure

### ISSUE THREAD

**Issue by mr-tl** [chocoteam/choco-solver#648]
Hi,

in my model I have several consecutive solving phases, where two such phases are separated by a `Solver.hardReset()` and a (timeout) `Solver.addStopCriterion()`. I have observed the behavior that, directly after adding the timeout stop criterion, the solver stops because of `Solver.isStopCriterionMet()`. This is directly after setting a rather long timeout, so I would not except this behavior.

This was also discussed as question 1 in https://groups.google.com/d/msg/choco-solver/xrBhq2RKVZM/gY-Uu700CgAJ

Many thanks in advance!

Magnus

## Expected behavior

The solver should continue the given time set by the timeout stop criterion.

## Actual behavior

The solver directly stops after setting the timeout stop criterion.

## Possible Solution

A reflection and what I currently use as workaround is adding a `Solver.getMeasures().reset()` directly after `Solver.hardReset()`. I would expect there is some problem with the time counter in `MeasuresRecorder`.

## Steps to Reproduce (for bugs)

```
    @Test
    public void testStopCriterion() {
        final Model model = makeNonTrivialModel();

        final Solver solver = model.getSolver();

        final long timeLimit = 2 * 1000000000L;

        solver.addStopCriterion(new TimeCounter(model, timeLimit));
        Assert.assertFalse(solver.isStopCriterionMet());
        solver.solve();

        solver.hardReset();

        solver.addStopCriterion(new TimeCounter(model, timeLimit));
        Assert.assertFalse(solver.isStopCriterionMet());
        solver.solve();
    }


    // Slightly adapted Golomb Ruler instance from:
    // https://github.com/chocoteam/samples/blob/master/src/main/java/org/chocosolver/samples/integer/GolombRuler.java
    //
    // The choice of model is irrelevant to this test, but must not be trivial to solve.
    private Model makeNonTrivialModel() {
        int m = 12;
        Model model = new Model("GolombRuler");
        IntVar[] ticks = model.intVarArray("a", m, 0, (1 << m + 1) - 1, false);

        model.arithm(ticks[0], "=", 0).post();

        for (int i = 0; i < m - 1; i++) {
            model.arithm(ticks[i + 1], ">", ticks[i]).post();
        }

        IntVar[] diffs = model.intVarArray("d", (m * m - m) / 2, 0, (1 << m + 1) - 1, false);
        IntVar[][] m_diffs = new IntVar[m][m];
        for (int k = 0, i = 0; i < m - 1; i++) {
            for (int j = i + 1; j < m; j++, k++) {
                model.scalar(new IntVar[]{ticks[j], ticks[i]}, new int[]{1, -1}, "=", diffs[k]).post();
                model.arithm(diffs[k], ">=", (j - i) * (j - i + 1) / 2).post();
                model.arithm(diffs[k], "-", ticks[m - 1], "<=", -((m - 1 - j + i) * (m - j + i)) / 2).post();
                model.arithm(diffs[k], "<=", ticks[m - 1], "-", ((m - 1 - j + i) * (m - j + i)) / 2).post();
                m_diffs[i][j] = diffs[k];
            }
        }
        model.allDifferent(diffs, "BC").post();
        return model;
    }
```

## Environment

* Choco-solver version: 4.10.2
* Java version: openjdk version "11.0.1" 2018-10-16

**Comment by ArthurGodet** [comment]
Hi,

I have looking into your problem. It is normal that the TimeCounter criteria is met, because the time counter for the solving process has not been reset yet. It is done during the method Solver.initialize().

If you change your method testStopCriterion() by the following one, you will see that it takes indeed 22s to execute the test : 
`@Test
    public void testStopCriterion() {
        final Model model = makeNonTrivialModel();

        final Solver solver = model.getSolver();

        final long timeLimit = 2 * 1000000000L;

        solver.addStopCriterion(new TimeCounter(model, timeLimit));
        Assert.assertFalse(solver.isStopCriterionMet());
        solver.solve();
        solver.printShortStatistics();

        for(int k = 0; k<10; k++) {
            solver.hardReset();
            solver.addStopCriterion(new TimeCounter(model, timeLimit));
            solver.solve();
            solver.printShortStatistics();
        }
    }`

I think that the use of Solver.isStopCriterionMet() is essentially designed to easily know if the search has been stopped or not, _i.e._ to know if the search was complete.

**Comment by mr-tl** [comment]
Hi Arthur,

thank you for your reply. I use `Solver.isStopCriterionMet()` as you say to determine whether or not the search has been stopped, that is if I should dispatch another search for an _improving solution_. This is done during a parallel portfolio solving process.

> I have looking into your problem. It is normal that the TimeCounter criteria is met, because the time counter for the solving process has not been reset yet. It is done during the method Solver.initialize().
> 

But it is reset in the call to `Solver.hardReset()`, no? That method calls `Solver.reset()` (on line 594) which in turn calls `MeasuresRecorder.reset()` (on line 561).

/Magnus

**Comment by ArthurGodet** [comment]
> But it is reset in the call to Solver.hardReset(), no? That method calls Solver.reset() (on line 594) which in turn calls MeasuresRecorder.reset() (on line 561).

No, the time counter is reset during the call to startStopwatch() (on line 350 in the class Solver). This is what reset the origin time of the search.

**Comment by mr-tl** [comment]
Hi Arthur,

ok so my usage as follows is not correct?

```
For a number of search phases:
  1. Set the timeout.
  2. Repeat until timeout: If stop criterion is not met, then search for improving solution.
```
It seems to work as intended by not checking the (timeout) stop criterion until after at least one call to Solver.solve(). So the above algorithm would become:
```
For a number of search phases:
  1. Set the timeout.
  2. Search for improving solution.
  3. Repeat until timeout: If stop criterion is not met, then search for improving solution.
```

Although this is fine, when you are aware of the behavior, I would have expected a `Solver.hardReset()` to behave exactly as a fresh Solver object. But this is not the case, then.

/Magnus

**Comment by ArthurGodet** [comment]
Hi Magnus,

I think your corrected algorithm should work as expected.
That said, I think you are right about `Solver.hardReset()` behaviour and I will propose a correction for this to Choco dev team.

**Comment by mr-tl** [comment]
Hi Arthur,

thank you for your pull request. Given that we would like a hardReset() to behave exactly as a fresh Solver object, I have the following input:

* A fresh solver object does not need your additional check in `Solver.isStopCriterionMet()`
* The limitation to instances of TimeCounter will not work if someone chooses to implement his/her own time counter class.

So I believe we are after something else here. Perhaps something that resets the time counting of MeasuresRecorder so that it behaves exactly as a fresh solver object?

/Magnus

**Comment by ArthurGodet** [comment]
Hi Magnus,

Indeed, you are right to look for a more general behaviour. I inverted call to `stopWatchWatch()` and `timeCount = 0` in `MeasuresRecorder.reset()`. The test is still good. I wait for Travis to see if all other tests are good too.

Arthur

**Comment by cprudhom** [comment]
Should I consider this issue as closed ?
