### ISSUE TITLE
[BUG] Assertion "try to pop a propagator from an empty queue"

### ISSUE THREAD

**Issue by mr-tl** [chocoteam/choco-solver#650]
In my model I have several search phases separated by `Solver.hardReset()`. Each search phase is an LNS search (spiced with Luby restarting) in a parallel setting.

I have recently started to trigger the assertion on line 168 (Choco 4.10.2) in `PropagationEngine` (`try to pop a propagator from an empty queue`). Is there some state there that I could print (when the assertion triggers) that could be useful for finding the culprit?

The assertion triggers in less than 5% of my test runs. I'm sorry that I cannot provide an MVE.

/Magnus

## Environment

* Choco-solver version: 4.10.2
* Java version: openjdk version "11.0.1" 2018-10-16

**Comment by cprudhom** [comment]
Hi @mr-tl,

You have to check the parameter `notEmpty` which maintains indices of not empty lists in `pro_queue`, ie lists that contain at least one scheduled propagator.

In your case, `notEmpty` indicates that a list from `pro_queue` is not empty whereas it is.
So `notEmpty > 0` and I bet this has to do with `pro_queue` which has been unwillingly cleared or wrongly updated. 

Best, 
CP

**Comment by cprudhom** [comment]
Is that still relevant?

**Comment by mrattfeldt** [comment]
Yes it is still relevant. I haven't investigated this further but catch and ignore that error currently. /Magnus (new GH account)

**Comment by cprudhom** [comment]
In that case, I'd appreciate a description of the steps to reproduce the bug. If it's possible to share some code with me (under conditions), it may also help me to understand the error.
