### ISSUE TITLE
[BUG] Error on creating dynamic variables and constraints using monitor

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#651]
Hello,

I'm using choco to solve dynamic constraint programming. I need to create dynamic variables and constraints based on other dynamic variables and constraints (multi-level dynamic creation).
In the following sample, I expect to create variable y after x value being defined, and z after y value being defined. In the end, the values of x, y and z must be equal to 2.

I need to handle this kind of instantiation for performance reasons. In my context, the model is composed of various components, and some of these are only instantiated given criteria. Therefore, I can reduce the solution space instantiating only the components relevant for a given set of input values.

```java
Model model = new Model();
// Static variable and constraint
IntVar x = model.intVar("x", 1, 3);
x.eq(2).post();
x.addMonitor((var, evt) -> {
	if (var.asIntVar().getValue() == 2) {
		// First dynamic variable and constraint
		IntVar y = model.intVar("y", 1, 3);
		x.eq(2).imp(y.eq(2)).post(); // It didn't works
		//x.eq(y).post(); // It works
		y.addMonitor((var2, evt2) -> {
			if (var2.asIntVar().getValue() == 2) {
				// Second dynamic variable and constraint
				IntVar z = model.intVar("z", 1, 3);
				y.eq(z).post();
				model.getSolver().propagate();
			}
		});
		model.getSolver().propagate();
	}
});
model.getSolver().propagate();
System.out.println(model);
```

If I execute this program using `x.eq(y).post()` it works fine, but when I execute `x.eq(2).imp(y.eq(2)).post()` a NullPointerException is thrown. Following, the stack trace:

```java
Exception in thread "main" java.lang.NullPointerException
	at org.chocosolver.solver.propagation.PropagationEngine.propagate(PropagationEngine.java:171)
	at org.chocosolver.solver.Solver.propagate(Solver.java:627)
	at net.weg.configurator.requirements.gcsp.GcspErrorApp.lambda$null$0(GcspErrorApp.java:24)
	at org.chocosolver.solver.variables.impl.AbstractVariable.notifyMonitors(AbstractVariable.java:336)
	at org.chocosolver.solver.variables.impl.AbstractVariable.notifyPropagators(AbstractVariable.java:330)
	at org.chocosolver.solver.variables.impl.BitsetIntVarImpl.instantiateTo(BitsetIntVarImpl.java:384)
	at org.chocosolver.solver.constraints.reification.PropXeqCReif.propagate(PropXeqCReif.java:45)
	at org.chocosolver.solver.propagation.PropagationEngine.propagate(PropagationEngine.java:180)
	at org.chocosolver.solver.Solver.propagate(Solver.java:627)
	at net.weg.configurator.requirements.gcsp.GcspErrorApp.lambda$main$1(GcspErrorApp.java:27)
	at org.chocosolver.solver.variables.impl.AbstractVariable.notifyMonitors(AbstractVariable.java:336)
	at org.chocosolver.solver.variables.impl.AbstractVariable.notifyPropagators(AbstractVariable.java:330)
	at org.chocosolver.solver.variables.impl.BitsetIntVarImpl.instantiateTo(BitsetIntVarImpl.java:384)
	at org.chocosolver.solver.constraints.unary.PropEqualXC.propagate(PropEqualXC.java:43)
	at org.chocosolver.solver.propagation.PropagationEngine.execute(PropagationEngine.java:216)
	at org.chocosolver.solver.propagation.PropagationEngine.activatePropagators(PropagationEngine.java:200)
	at org.chocosolver.solver.propagation.PropagationEngine.propagate(PropagationEngine.java:164)
	at org.chocosolver.solver.Solver.propagate(Solver.java:627)
	at net.weg.configurator.requirements.gcsp.GcspErrorApp.main(GcspErrorApp.java:30)
```

I think this is a bug and I have no idea about the cause (I'm new on choco-solver). Besides that, it's not clear in documentation if this approach is the better one to handle this kind of dynamic environment. 

Environment
* Choco-solver version: 4.10.2
* Java version: 1.8.0_161

**Comment by cprudhom** [comment]
Hi,

From my point of view, this is not a bug, since the propagation engine has not been designed to support nested calls to propagate, but I can try to help you on this.

Before discussing what fixes can be considered let me suggest a modification of your code:
```java
Model model = new Model();
// Static variable and constraint
IntVar x = model.intVar("x", 1, 3);
x.eq(2).post();
AtomicBoolean propNeeded = new AtomicBoolean(true);
x.addMonitor((var, evt) -> {
    if (var.asIntVar().getValue() == 2) {
        // First dynamic variable and constraint
        IntVar y = model.intVar("y", 1, 3);
        x.eq(2).imp(y.eq(2)).post(); // It didn't works
        //x.eq(y).post(); // It works
        y.addMonitor((var2, evt2) -> {
            if (var2.asIntVar().getValue() == 2) {
                // Second dynamic variable and constraint
                IntVar z = model.intVar("z", 1, 3);
                y.eq(z).post();
                propNeeded.set(true);
            }
        });
        propNeeded.set(true);
    }
});
while(propNeeded.get()) {
    propNeeded.set(false);
    model.getSolver().propagate();
}
System.out.println(model);
```
This proposal avoid nested loops and fixes the issue.
But it also supposes that everything goes right.
In CP, backtracking is a key component, and it supposes you are able to recover previous variables' domain and internal constraints' state (if any) and probably many other things.
In your code, if a contradiction occurs or you want to undo a decision, there is no mechanism that restores the state before error/decision.

In addition, while you are propagating a constraint `C`, you can `propagate` which propagates `C`. But, `C` is able to say that it is entailed (it has done it works, and nothing more can be done **in the current search space**), it goes silent. And, in choco, "go silent" function is not idempotent, calling it twice is not possible.  

So, I would suggest you to either find a way to use Choco-solver in the way it was designed (by calling `solver.solve()`) or, starting from the code I gave you, to find a way maintain the stack of states in order to be able to deal with contradictions and to undo operations.
 
Hope it helps,
CP

**Comment by schmittjoaopedro** [comment]
Thanks for the suggestion.

In my project I'm trying to use choco-solver to solve the interative configuration problem. Based on what I've studied, I found that propagate is sufficient and time efficient to process filter on variable domains.
The idea of use choco-solver is to filter the variables domains when the end-user inputs a value for a given variable. This filter must respect the constraints.

I can't see exactly how `solver.solve()` can guide the interative configuration process without iterating for all posible solutions to refine the domain of variables at each variable value selected by the en user. I think that such technique is very time consuming. Even more in the beginning of the configuration where the search space is big becayse few inputs where given by the user.

Besides that, as the configuration is applied for a given model, the model itself is broken in components that are instantiated accordingly with the user inputs. Therefore, I have to handle a generative CSP scenario where constrains are added dynamically during propagation. Based on your suggestion, I think that will be possible to handle such scenario. However, there is another efficiente way that choco-solver can handle it using `solver.solve()`?

**Comment by ArthurGodet** [comment]
Configuration is kind of a special case of using constraint programming technologies. Indeed, in configuration software, you are interested in the state of the variables at any node of the search space, whereas the usual use of CP is to find (optimal) solution(s) to a combinatorial problem.

In the case of configuration, it is indeed efficient to call for the propagation process. However, you still need to be able to backtrack any decision that has been made in case in leads to no solution (the domain of at least one variable has been emptied).

Usually, it is an inside job for the solver to deal with propagation and its consequences. Nevertheless, in configuration you will want to manage what happens yourself. In my opinion, you have two possibilities :

1. Build a new `Model` object and adding variables and constraints **each time** a decision is made by the user and call to `model.getSolver().propagate()` to filter the domains (_very easy but can be time and memory-consuming depending on the size of your problem_)
2. Build only one `Model` object, add all your variables and constraints **at the beginning** and use branching and backtrack mechanisms to apply and unapply user decisions (_very time and memory-efficient but a bit tricky to put in place, calling very advanced mechanisms of choco-solver_)

I would recommand to start with the first possibility, see how it fits your needs, and, depending on the results, see if you need the second one (but as I say, it is much harder to put in place as branching and backtracking can be hard to manage).

**Comment by schmittjoaopedro** [comment]
Thanks for the suggestions 

I started considering the first approach (create a new model at each user interaction). For now, I already have no idea about how will be the system performance because I don't have all the information about the configuration model already.

In parallel, I started to research your second suggestion and in the future, I think that this is the best approach. For now, I would like to make two suggestions related to the branching and backtrack mechanisms to apply and unapply user decisions:
1) Provide some examples or documentation of how to use the advanced mechanisms;
2) Simplify the internal mechanism by providing a simplified API.

**Comment by ArthurGodet** [comment]
We are currently in the process of revamping the documentation of the solver, including the advanced mechanisms part. However, it might take time before this process is finished.

About simplifying the call to advanced mechanisms, we are also thinking about it, despite it being difficult because of all the internal mechanisms and events to manage. So I can not promise it will be done in the future. All I can say is that we are thinking about how to simplify some internal processes linked to propagation, backtracking and cie.

**Comment by schmittjoaopedro** [comment]
Very nice, that's pretty informative. I'm anxious by the future versions =D.
Thank you by attention.

**Comment by cprudhom** [comment]
> 2. Simplify the internal mechanism by providing a simplified API.

It's a bit of a stretch, I assume you have something peculiar in mind... 
What parts need to be simplified for you? And what do you suggest?

**Comment by schmittjoaopedro** [comment]
Basically, I need to post and unpost constraints that instantiate variables. (e.g. `material.eq('iron').post()`. These constraints are ending user-defined values during the interactive configuration. 

In this sense, when the user unselect a given value, (e.g. `material.eq('iron').unpost()`) I would like to propagate the solver and return to the previous state (in this case the variable domains filtered without 'material = iron' value). If I can do it without the necessity to instantiate a new `Model` in every interaction, I think that it will result in many performance improvements.

**Comment by ArthurGodet** [comment]
In this special case, you can use Decision objects to push and pop user decisions, as if it was a search heuristic. Using such mechanisms will help you going forward and backward along the different states of your model.
