### ISSUE TITLE
Choco ge() for realvars not working

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#653]
Hello, I'm trying to bound the variable x domain with the following source code:

```java
Model model = new Model();
RealVar x = model.realVar("x", 0.16, 500.0, 0.01);
x.ge(1.0).ibex(0.01).post();
model.getSolver().propagate();
System.out.println("x = [" + x.getLB() + ", " + x.getUB() + "]");

// Output: x = [0.16, 500.0]
// Expected: x = [1.0, 500.0]
```
However, when I execute the source code, the propagation isn't updating the lower bound to 1.0.

**Comment by schmittjoaopedro** [comment]
Some advice?

**Comment by cprudhom** [comment]
You can follow the issue I opened in Ibex:
https://github.com/ibex-team/ibex-lib/issues/435

**Comment by schmittjoaopedro** [comment]
Hello, there is an prevision about when the feature will be fixed?

**Comment by cprudhom** [comment]
Sorry, I missed answers from Ibex issue.
Actually, fixing the issue seems quite easy, but I have no idea when the release will be done.
