### ISSUE TITLE
[FEATURE] Clean tests' messages

### ISSUE THREAD

**Issue by ArthurGodet** [chocoteam/choco-solver#658]
## Actual behaviour
A lot of printing appears in the tests' logs, which surely helps when debugging these tests but pollute the general readability of the tests' results.

## Expected behaviour
Only maven logs should appear in the tests' logs, other printings being used only for debugging purposes.

**Comment by cprudhom** [comment]
I bet we can do that by twisting `CustomListener`.
I'll have a try.
