### ISSUE TITLE
Ibex solver, strange behavior with power operator

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#667]
Hello, 

I'm replicating the example available in "Handbook of Constraint Programming" (pg. 575), and I notice a different behavior between the `pow` and the `mul` operator.
When I use the `mul` operator the model gives the same result from the book, `x=-0.61` and `y=0.38`, but when I use the `pow` operator it throws and contradiction exception.

The source code: 

```java
double PRECISION = 1e-8;
Model model = new Model();
RealVar y = model.realVar("y", -4.0, 4.0, PRECISION);
RealVar x = model.realVar("x", -4.0, 4.0, PRECISION);

// y - x^2 = 0
y.sub(x.mul(x)).eq(0).ibex(PRECISION).post(); // It works
// y.sub(x.pow(2)).eq(0).ibex(PRECISION).post(); // It didn't works

// y - x - 1 = 0
y.sub(x).sub(1).eq(0).ibex(PRECISION).post();

model.getSolver().propagate();
System.out.println(model.getSolver().findSolution());
```

Thanks in advance

**Comment by cprudhom** [comment]
Thank you for the bug report, I found out where it comes from and I'm going to patch it right now.

Best, 
CP
