### ISSUE TITLE
[BUG] Error on ibex processing due to new equation API

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#677]
I'm testing the choco-solver version 4.10.3-SNAPSHOT to check out the new equation API for real numbers. I'm really interrested about this new feature.

I have compiled the jar in my own machine, and before start testing the new `equation` API, I found a bug in the current ibex API. Follows the scenario:

```java
public static void main(String[] args) throws Exception {
    Model model = new Model();
    RealVar x = model.realVar(360.0, 360.0, 0.0001);
    RealVar y = model.realVar(0.0, 4.0, 0.0001);
    RealVar z = model.realVar(0.0, 360.0, 0.0001);

    // It's working on version 4.10.2 of choco-sover but not 4.10.3-SNAPSHOT
    y.eq(4.0).ibex(RealProperty.PRECISION).post();
    z.eq(x.div(y)).ibex(RealProperty.PRECISION).post();

    /* It's working on version 4.10.3-SNAPSHOT
    y.eq(4.0).equation().post();
    z.eq(x.div(y)).equation().post();
    */

    model.getSolver().propagate();

    System.out.println(x); // [360.0 .. 360.0]
    System.out.println(y); // [4.0 .. 4.0]
    System.out.println(z); // [90.0 .. 90.0]
}
```

The test is throwing the follows error:
```java
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.chocosolver.util.tools.RealUtils.odiv(RealUtils.java:146)
	at org.chocosolver.util.tools.VariableUtils.boundsForDivision(VariableUtils.java:169)
	at org.chocosolver.solver.expression.continuous.arithmetic.BiCArExpression.realVar(BiCArExpression.java:104)
	at org.chocosolver.solver.expression.continuous.relational.BiCReExpression.ibex(BiCReExpression.java:60)
	at "my test class"
```

Well, even with this bug I continue my tests to check the equation API, at first, it is woking well. However, I have a question related to final bounds computation of real numbers, differently from Ibex, the final bounds are computed considering the precision. It's supposed to be normalized to behave like in Ibex?

```java
Results in ibex:
System.out.println(x); // [360,0000000000000000 .. 360,0000000000000000]
System.out.println(y); // [4,0000000000000000 .. 4,0000000000000000]
System.out.println(z); // [90,0000000000000000 .. 90,0000000000000000]

Results with equation (differently from ibex):
System.out.println(x); // [360,0000000000000000 .. 360,0000000000000000]
System.out.println(y); // [3,9999999999999996 .. 4,0000000000000000]
System.out.println(z); // [89,9999999999999700 .. 90,0000000000000400]
```

Thanks

**Comment by cprudhom** [comment]
Thank you for the bug report, I'll fix in few minutes.
About the bounds: even if `equation` filters thanks to HC4 Newton algorithm, we cannot manage the precision like Ibex. We have to make a choice about when a variable is considered as instantiated. In the case you exhibit, we consider that `y` and `z` are instantiated.
There is nothing more we can do.
If you think there is a better way to do this, we are open to patches.

Best regards,
CP
