### ISSUE TITLE
Protobuf version conflict

### ISSUE THREAD

**Issue by fahrenheit9** [chocoteam/choco-solver#679]
Hello,

We are trying to integrate your great application into our project. However, we are encountering some problem with the Protobuf version.

We are using Protobuf 3.6.1 and your application is using the version 2.6.1.

It is impossible to use your solution because of this version conflict.

Do you have any plan to upgrade to a newer version of Protobuf ? 

Thanks,

Adrien

**Comment by cprudhom** [comment]
Dear Adrien,

First thank you for interest in choco-solver.

I suppose you try to integrate v4.10.2 ?
If so, I encourage you to have a look at the current snapshot version, 4.10.3-SNAPSHOT.
In this future release, the number of dependencies have been reduced and if I'm correct Protobuf was part of removed ones.

Besides this, can you tell me more about your project (here or privately on gitter)?

Hope that helps, 

CP

**Comment by fahrenheit9** [comment]
Thank you for your answer. The version 4.10.3-SNAPSHOT resolves our problem.

We'll get in touch with you to tell you more about our project.

Have a nice day,

Adrien
