### ISSUE TITLE
Exclude "test" dependencies embedded in the choco-solver Maven artifact

### ISSUE THREAD

**Issue by thetric** [chocoteam/choco-solver#680]
## Expected behavior
The Maven artifact `choco-solver` does not include dependencies from this project's `test` scope.

## Actual behavior
Currently the `test` dependencies and their transitive dependencies are included in the `choco-solver` JAR:

![image](https://user-images.githubusercontent.com/19861998/78353193-f34c2d00-75a9-11ea-9d8a-1278896f8057.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Environment

* Choco-solver version: 4.10.2
* Java version: AdoptOpenJDK 11.0.6
* Link to your project:

**Comment by cprudhom** [comment]
@thetric in the master branch (4.10.3-SNAPSHOT), each `test` dependencies are tagged `<scope>test</scope>` in `pom.xml`s.

See for instance:
[pom.xml (choco-solver)](https://github.com/chocoteam/choco-solver/blob/190afa195d6a4faf1b7a6ab112dfd65ca32e88dc/solver/pom.xml#L49)

Can you try with the master branch ?
Hope that helps,
CP

**Comment by thetric** [comment]
Thank you for your help! The current snapshot version works as expected. Is a new release in sight that includes this fix?

**Comment by cprudhom** [comment]
Well, due to the current situation, I'm not able to make a release right now.
But in the near future, sure.
