### ISSUE TITLE
Docs: Table constraints

### ISSUE THREAD

**Issue by thetric** [chocoteam/choco-solver#688]
## Expected behavior
The user guide should provide a description and an example on how to define table constraints (`model.table()`).

A [notebook example](https://github.com/chocoteam/notebooks/blob/master/Conditionnal_constraint.ipynb) mentions table constraints in context of expressions. It would be nice if the user guide showed an equivalent solution using expressions.

## Actual behavior
The user guide doesn't even mention table constraints. 

## Context

I searched for a way to create table constraints. 

## Environment

* Choco-solver version: `master`
* Java version: AdoptOpenJDK (build 14.0.1+7)
* Link to your project:

**Comment by cprudhom** [comment]
I added a tutorial for the TSP, wherein I use table constraints to get distances between cities.
Have a look, and tell if that helps (I know, I should update the documentation too...)

https://choco-solver.org/tutos/traveling-salesman-problem/

Best,
CP

**Comment by thetric** [comment]
Thank you for the link!
The tutorial describes `element` constraints as a substitution for table constraints. Is there a rule of thumbs when to choose which?

**Comment by cprudhom** [comment]
This is true because the table constraint here is very specific (2-dimension, one variable is an index, etc).
When an element constraint is needed, a table constraint can be considered, the opposite is not always true. For instance, consider a table constraints over 4 variables, the element constraint will introduce additional variables.

**Comment by cprudhom** [comment]
https://choco-solver.org/docs/modeling/intconstraints/#table-constraints
If you have any comments, let me know

**Comment by thetric** [comment]
Thank you for the docs update!
