### ISSUE TITLE
lower bound check in checkRealDomainRange

### ISSUE THREAD

**Issue by zyq8709** [chocoteam/choco-solver#691]
https://github.com/chocoteam/choco-solver/blob/d3dac29b1c1f1d343a52ea4e196ded864f415745/solver/src/main/java/org/chocosolver/solver/variables/IVariableFactory.java#L852
The lower bound check in checkRealDomainRange just compare MIN with Double. MIN_VALUE which is a positive real number. So wonder whether it is intended to be like this or just a mistake.

**Comment by cprudhom** [comment]
That's a mistake, and equalities are too.
The idea is to prevent too big domain, but we should consider a range size instead.
