### ISSUE TITLE
Please publish the parent POM org.choco-solver:choco:4.10.3

### ISSUE THREAD

**Issue by thetric** [chocoteam/choco-solver#699]
## Expected behavior
All choco dependencies can be resolved from Maven Central.

## Actual behavior
Neither Gradle nor Maven are able to download `org.choco-solver:choco-solver:4.10.3` because it `Could not find artifact org.choco-solver:choco:pom:4.10.3 in central (https://repo.maven.apache.org/maven2)`.
Gradle fails with:
```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.choco-solver:choco-solver:4.10.3.
     Required by:
         project :
      > Could not resolve org.choco-solver:choco-solver:4.10.3.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/choco-solver/choco-solver/4.10.3/choco-solver-4.10.3.pom
            > Could not find org.choco-solver:choco:4.10.3.
      > Could not resolve org.choco-solver:choco-solver:4.10.3.
         > Could not parse POM https://jcenter.bintray.com/org/choco-solver/choco-solver/4.10.3/choco-solver-4.10.3.pom
            > Could not find org.choco-solver:choco:4.10.3.
```

The POM of the 4.10.3 release contains an additional `<parent>` element which is not present in the 4.10.2 release:

- POM 4.10.3: https://repo.maven.apache.org/maven2/org/choco-solver/choco-solver/4.10.3/choco-solver-4.10.3.pom
- POM 4.10.2: https://repo.maven.apache.org/maven2/org/choco-solver/choco-solver/4.10.2/choco-solver-4.10.2.pom

## Steps to Reproduce (for bugs)

Maven:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>choco4-10-3-bug</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.choco-solver</groupId>
            <artifactId>choco-solver</artifactId>
            <version>4.10.3</version>
        </dependency>
    </dependencies>
</project>
```

Perhaps you have to remove the choco files from your local `.m2` to reproduce this issue.

## Context
I've tried update from 4.10.2 to 4.10.3.

## Environment

* Choco-solver version: 4.10.3
* Java version: 11.0.8

**Comment by mrattfeldt** [comment]
Bump

**Comment by JiiTee** [comment]
Needed here too. Please and thank you!

**Comment by glelouet** [comment]
I am also affected by this.

Strange thing is, the 4.10.3 is present in https://repo1.maven.org/maven2/org/choco-solver/choco-solver/4.10.3/

So I thought I made a mistake, but it seems I'm not the only one affected.

**Comment by cprudhom** [comment]
I migrated the project to a multi-module one (following those steps: [baeldung.com/maven-multi-module](https://www.baeldung.com/maven-multi-module)).
But, it appears that `org.choco-solver:choco:4.10.3` was not released on MCR.
I'll try to fix that quickly.

**Comment by fbl100** [comment]
Has this been resolved?  We were using a 4.10.3-SNAPSHOT dependency, but sometime in the last 24 hours it disappeared.  I Tried updating to 4.10.3 and got this error.

Updating to 4.10.4-SNAPSHOT worked for me, but I would prefer to depend on the 4.10.3 release.

**Comment by cprudhom** [comment]
I plan to release in a couple of hours, but I'm not sure of the fix.

**Comment by cprudhom** [comment]
I belive the patch does not do the job...

**Comment by glelouet** [comment]
do you know what the problem is ?

**Comment by cprudhom** [comment]
Not really, but as a fisrt step I tried to (lightly) revamp `pom.xml` files wrt to your PR.
It seemed to work but I tried to install choco in a docker image (ie, in a fresh new environment), and I got an error related o JPMS.

**Comment by cprudhom** [comment]
AFAIK, the last commit (e11dabf337784c82f1944d16f440fbc16493faf0) which reverts `pom.xml`, fix the issue I encountered.
I'm still unable to dry-run the release process, so I'm not sure the parent POM will be published...
But I will try now.

**Comment by glelouet** [comment]
you can install in a temp dir to test the creation of the artifacts.

```
# go in temp dir 
cd $(mktemp -d)
# create local repo
mkdir repo
# clone choco. you can add -b <branch> at the end if you want to test a specific branch
git clone https://github.com/chocoteam/choco-solver.git
# go in choco dir
cd choco-solver
# run maven install
mvn install -Dmaven.repo.local=$(pwd)/../repo/ -DskipTests
# go make a coffee, since maven will download half of internet
# check the result 
tree ../repo/org/choco-solver/

```
https://imgur.com/c0kMyEW

**Comment by glelouet** [comment]
personally I stopped using the release goal in maven because it's just a pain.
I manually update the root pom value with
```
version=a.b.c
mvn versions:set -DnewVersion=$version
mvn deploy
git commit -am "v$version"
git tag  "v$version"
git push && git push --tags
```

**Comment by cprudhom** [comment]
The release went well, it is only a matter of time before MVN will be updated.
🤞

**Comment by cprudhom** [comment]
It seems to be ok, the parent POM is available:
https://repo.maven.apache.org/maven2/org/choco-solver/choco/4.10.4/

**Comment by mrattfeldt** [comment]
Did anyone here manage to upgrade to 4.10.4? I get the following exception when Choco kicks in:

`java.lang.IllegalAccessError: class org.chocosolver.solver.constraints.nary.sat.PropSat tried to access field org.chocosolver.sat.SatSolver.ok_ (org.chocosolver.solver.constraints.nary.sat.PropSat and org.chocosolver.sat.SatSolver are in unnamed module of loader 'app')

	at org.chocosolver.solver.constraints.nary.sat.PropSat.propagate(PropSat.java:100)
	at org.chocosolver.solver.propagation.PropagationEngine.execute(PropagationEngine.java:225)
	at org.chocosolver.solver.propagation.PropagationEngine.activatePropagators(PropagationEngine.java:209)
	at org.chocosolver.solver.propagation.PropagationEngine.propagate(PropagationEngine.java:173)
	at org.chocosolver.solver.search.loop.propagate.PropagateBasic.execute(PropagateBasic.java:46)
	at org.chocosolver.solver.Solver.initialize(Solver.java:367)
	at org.chocosolver.solver.Solver.solve(Solver.java:255)`

**Comment by cprudhom** [comment]
This is a JPMS issue, so I suppose you are using Java 9+ ?
To be honest, I don't understand what is going on.
The `ok_` field is public , and `module-info.java` of `org.chocosolver.sat` exports `org.chocosolver.sat` to `org.chocosolver.solver`. 
Jar files are double compiled, as depicted in [Apache Maven Compiler Plugin website](http://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html)

**Comment by mrattfeldt** [comment]
I run Java 11, but I can trigger this also with Java 8. The problem is triggered for example by this model: https://www.cosling.com/choco-solver/pareto

Would you like a stand-alone bug report?

**Comment by cprudhom** [comment]
> Would you like a stand-alone bug report?
Yes, that would be easier, but you can refer  to this issue.
