### ISSUE TITLE
[BUG] Enum for IBS (impact) heuristic

### ISSUE THREAD

**Issue by leezear2019** [chocoteam/choco-solver#700]
https://github.com/chocoteam/choco-solver/blob/ae754654388853bcad74cafb0e5af7ce1ab09fce/solver/src/main/java/org/chocosolver/solver/search/strategy/Search.java#L668

I found a typos on line 668 of "solver/search/strategy/Search.java". Calling this method will cause a recursive call that will not stop.

Choco version is 4.10.3 (03 Jul 2020).

Hope to help you.

**Comment by cprudhom** [comment]
Thank you for the bug reporting.
