### ISSUE TITLE
[BUG] Arithmetic bug with Ibex and power operator

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#702]
I'm having a bug with the following program:

```java
Model model = new Model();
RealVar x = model.realVar("x", -10000, 10000, 0.001);
RealVar y = model.realVar("y", -10000, 10000, 0.001);

y.eq(x.pow(2.0)).ibex(0.001).post();
model.getSolver().propagate();
System.out.println(x); // Domain should be -> [-100 .. 100], but returns -> [0 .. 100]
```
## Expected behavior

The domain of X is not being filtered correctly. It should return the negative part (-100.0 .. 0) as well.

## Context
I'm using this for product configuration, it's very important because influences in the dimensional calculations of engineering products. I found this error during a calculation of physical properties between two different mechanical componentes.

## Environment
* Choco-solver version: 4.10.3
* Java version: 1.8  x32 bits

**Comment by cprudhom** [comment]
Hi,

I suppose, this is related to Ibex:
```java
Ibex ibex = new Ibex(new double[]{0.001, 0.001, 0.001});
        
ibex.add_ctr("{0}={1}^{2}");
ibex.build();
double domains[] = {-16.0, 16.0, -4.0, 4.0, 2.0, 2.0};
System.out.println("Before contract:");
System.out.println("([" + domains[0] + "," + domains[1] + "] ; [" + domains[2] + "," + domains[3] + "])");
        
int result = ibex.contract(0, domains);
        
if (result == Ibex.FAIL) {
    System.out.println("Failed!");
} else if (result == Ibex.CONTRACT) {
    System.out.println("After contract:");
    System.out.println("([" + domains[0] + "," + domains[1] + "] ; [" + domains[2] + "," + domains[3] + "])");
} else {
    System.out.println("Nothing.");
}
ibex.release();
```
Let's check with them.

**Comment by cprudhom** [comment]
Follow [Ibex issue](https://github.com/ibex-team/ibex-lib/issues/471)

**Comment by schmittjoaopedro** [comment]
As commented by @gchabert in the issue [IBEX-LIB-471](https://github.com/ibex-team/ibex-lib/issues/471), the problem is related about how choco-solver sends the power operations to ibex, as ibex can't handle complex numbers (it only work with positive numbers in the domain of power functions), then the expressions should be changed from:
```java
model.realIbexGenericConstraint("{0}={1}^{2}", y, x, k).post();
```
to:
```java
model.realIbexGenericConstraint("{0}={1}^" + k, y, x).post();
```

By this way, the power functions with integer exponents could consider the domain's negative side. 

In my tests it worked really well for huge contractions of the domain (let's say greater than 1%). I'm quoting this because there's still one requirement for a fix in ibex that relies on the contraction ratio, already seen in these issues [IBEX-LIB-435](https://github.com/ibex-team/ibex-lib/issues/435) and #653 . There's already a solution but it's not available to use, it would be really nice if we could create a patch to solve this issue.

**Comment by schmittjoaopedro** [comment]
@cprudhom I've created the pull request #710 to handle this problem, could you take a look?
