### ISSUE TITLE
[4.10.2] [minor] "At least one constraint is free, i.e., neither posted or reified. )." while constraint.getOpposite() is posted.

### ISSUE THREAD

**Issue by glelouet** [chocoteam/choco-solver#705]
The code that generates this is : 

```
		Model choco = new Model();
		IntVar a = choco.intVar(1,2);
		Constraint expr = choco.arithm(a, "<", 2);
		BoolVar f = choco.boolVar(false);
		expr.reifyWith(f);
		choco.getSolver().solve();
```

I diged a bit, it seems to be the constraint.reifyWith(bv) call that generates this warning.

```
		Model choco = new Model();
		Constraint expr = choco.arithm(choco.intVar(1, 2), "<", 2);
		expr.getOpposite().post();
		choco.getSolver().solve();
```

IMO that can be fixed in [Constraint#getStatus(), l313](https://github.com/chocoteam/choco-solver/blob/master/solver/src/main/java/org/chocosolver/solver/constraints/Constraint.java#L313) : 
\- return mStatus;
\+ return (mStatus==FREE && opposite!=null)?opposite.mStatus:mStatus;

unit/noregression test : 
```

		Model choco = new Model();
		Constraint expr = choco.arithm(choco.intVar(1, 2), "<", 2);
		expr.getOpposite().post();
		assert expr.getStatus() == Status.POSTED;

```

**Comment by cprudhom** [comment]
I bet this is already fixed in 4.10.3 (see 640461ec)

**Comment by glelouet** [comment]
That fix is bad. c.getOpposite() will always enforce the opposite is not null.
I checked if there was a test possible and there was none, that's why I propose to modify the getStatus() instead.

**Comment by glelouet** [comment]
@cprudhom please reopen. The fix is bad.

**Comment by cprudhom** [comment]
My bad, your test should not thrown the message.
The `getStatus()` should consider the opposite too.
