### ISSUE TITLE
Precision lost when combining `div` and `ge` constraints.

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#725]
Hello,

I'm trying to execute some simple calculations using the new equation API. I've seen that in the last release of choco (4.10.4) the following issue #692 fixed the division for bounds with zero (that's great).

Now when I execute the following program:

```java
Model model = new Model();
//RealVar x = model.realVar("x", 0.0, 8.0, 1e-6); // With this domain, y returns [0,125 .. 100,000] (CORRECT)
RealVar x = model.realVar("x", -100.0, 8.0, 1e-6); // With this domain, y returns [0,000 .. 100,000] (INCORRECT)
RealVar y = model.realVar("y", -100.0, 100.0, 1e-6);
RealVar c = model.realVar("c", 1.0, 1.0, 1e-6);
x.ge(0.0).equation().post();
y.eq(c.div(x)).equation().post();
model.getSolver().propagate();
System.out.println(y);
```

I'm getting `y = [0,000 .. 100,000]` , but I expect it to be `[0,125 .. 100,000]`. It looks like some problem with the rounding of bounds. I will need this operation to work with negative power operation, where `x^-3 <-> 1/x^3`.

## Environment
* Choco-solver version: 4.10.4
* Java version: AdoptJDK 11

I will post more comments in this issue if I gather more information about the cause.

Thanks

**Comment by cprudhom** [comment]
Actually, `x.ge(0.0)` updates the bounds of `x` to `[-0.0, 8.0]`.
Indeed, it computes previous (and next) float of the lower (upper) bound to not loose solutions.
And, since `x` contains `0` the `RealUtils.odiv` states that the domain of `c/x` is `(-inf,+inf)`.

`0` is a special case in continuous. 
If you add `x.ge(RealUtils.nextFloat(0.0)).equation().post();` instead, that problem is fixed.

**Comment by schmittjoaopedro** [comment]
I see, do you think it's a good idea to handle this internally in the `ge` and `le` operator for the next version of choco? 
It's a little hacky to require from the user to know about that.

**Comment by cprudhom** [comment]
Actually, I suppose the following fixes will do the job.
```java 
   /**
     * @param y a double
     * @return return the expression "x >= y" where this is "x"
     * @implNote if {@literal y} is equal to {@literal 0.}, then {@literal y} is updated to {@code RealUtils.nextFloat(0)}.
     * Indeed, {@literal 0.} is a special case in continuous.
     */
    default CReExpression ge(double y) {
        if(y == 0.){
            y = RealUtils.nextFloat(0);
        }
        return new BiCReExpression(CReExpression.Operator.GE, this, this.getModel().realVar(y));
    }
```
And 
```java
    /**
     * @param y a double
     * @return return the expression "x <= y" where this is "x"
     * @implNote if {@literal y} is equal to {@literal 0.}, then {@literal y} is updated to {@code RealUtils.prevFloat(0)}.
     * Indeed, {@literal 0.} is a special case in continuous.
     */
    default CReExpression le(double y) {
        if(y == 0.){
            y = RealUtils.prevFloat(0);
        }
        return new BiCReExpression(CReExpression.Operator.LE, this, this.getModel().realVar(y));
    }
```
