### ISSUE TITLE
[BUG] Ibex constraint combined with logical operations does not seem to work

### ISSUE THREAD

**Issue by JiiTee** [chocoteam/choco-solver#731]
##Actual behavior
Produces the following ouput
[33mwarning: Certification not implemented for over-constrained systems [0m
No search strategies defined.
Set to default ones.
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] :wgt_2 = 1373
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] :wgt_2 = 1374
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] :wgt_2 = 1375

## Expected behavior
Output should also include:
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] :wgt_2 = 1373
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] :wgt_2 = 1374
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] :wgt_2 = 1375
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] :wgt_2 = 1376
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] :wgt_2 = 1377

## Environment

Choco-solver version: 4.10.4
Ibex-version: 2.8.7
Java version: 1.8.0_102

**Comment by JiiTee** [comment]
``public class ChocoIbexTest {

    public static void main(String[] args) {
        
        Model m = new Model();
        
        RealVar dutycycle = m.realVar(":dutycycle_2", 40, 60, 0.000001);
        
        //simulate enumerated float dutycycle: 40.0 or 60.0
        Constraint r40 = m.realIbexGenericConstraint("( {0} = 40.0)", dutycycle);
        Constraint r60 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle);
        BoolVar r40Reif= r40.reify(); 
        BoolVar r60Reif= r60.reify();
        BoolVar[] oneR = new BoolVar[2];
        oneR[0] = r40Reif;
        oneR[1] = r60Reif;
        m.sum(oneR, "=", 1).post();

        IntVar wgt_2 = m.intVar(":wgt_2", 1373, 1377);
        
        // dutycycle = 60.0 implies  wgt <= 1375
        // automatic translation generates the following kind of translation, here reimplemented in JAVA  

        Constraint wgt_2_LE_1375 = m.arithm(wgt_2, "<=", 1375);
        Constraint r60_2 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle);
        Constraint req60_max1375 =
            m.or (
                    m.not(r60_2),
                    wgt_2_LE_1375
                    );
        
        req60_max1375.post();;
        
        //No solutions with r40_2 if uncommented
        //Not even if  section to simulate enumerated float dutycycle: 40.0 or 60.0 is removed
        //Constraint r40_2 = m.realIbexGenericConstraint("( {0} = 40.0)", dutycycle);
        //r40_2.post();
        
        m.getSettings().setWarnUser(true);
        m.getSettings().setPrintAllUndeclaredConstraints(true);
        m.getSettings().setCheckDeclaredConstraints(true);

        while (m.getSolver().solve()) {
               System.out.print(dutycycle + " " + wgt_2);
            System.out.println();
        }
        
    }
}

**Comment by cprudhom** [comment]
There is a bug. I can tell you how to avoid it:
```java
Constraint wgt_2_LE_1375 = m.arithm(wgt_2, "<=", 1375);
    Constraint r60_2 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle);
    Constraint req60_max1375 =
        m.or (
                m.not(r60_2),
                wgt_2_LE_1375
                );
```

replaced by:
```java
BoolVar wgt_2_LE_1375 = m.arithm(wgt_2, "<=", 1375).reify();
        BoolVar r60_2 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle).reify();
        Constraint req60_max1375 =
                m.or(
                        r60_2.not(),
                        wgt_2_LE_1375
                );
```

But from now, I cannot see any patch.

**Comment by JiiTee** [comment]
Thank you for the proposal! Unfortunately I cannot produce the desired effect.
The modified code:
`  public static void suggested() {

        Model m = new Model();

        RealVar dutycycle = m.realVar(":dutycycle_2", 40, 60, 0.000001);

        //simulate enumerated float dutycycle: 40.0 or 60.0
        Constraint r40 = m.realIbexGenericConstraint("( {0} = 40.0)", dutycycle);
        Constraint r60 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle);
        BoolVar r40Reif= r40.reify(); 
        BoolVar r60Reif= r60.reify();
        BoolVar[] oneR = new BoolVar[2];
        oneR[0] = r40Reif;
        oneR[1] = r60Reif;
        m.sum(oneR, "=", 1).post();

        IntVar wgt_2 = m.intVar(":wgt_2", 1373, 1377);

        // dutycycle = 60.0 implies  wgt <= 1375
        // automatic translation generates the following kind of translation, here reimplemented in JAVA  

        //Constraint wgt_2_LE_1375 = m.arithm(wgt_2, "<=", 1375);
        
        BoolVar wgt_2_LE_1375 = m.arithm(wgt_2, "<=", 1375).reify();
        BoolVar r60_2 = m.realIbexGenericConstraint("( {0} = 60.0)", dutycycle).reify();
        Constraint req60_max1375 =
                m.or(
                        r60_2.not(),
                        wgt_2_LE_1375
                );

        req60_max1375.post();;


        //m.getSettings().setWarnUser(true);
        //m.getSettings().setPrintAllUndeclaredConstraints(true);
        //m.getSettings().setCheckDeclaredConstraints(true);
        System.out.println(m.getSettings().getWelcomeMessage());

        System.out.println(m);
        while (m.getSolver().solve()) {
            for (Variable v: m.getVars())
                System.out.print(v + " ,");
            System.out.println ( "");
        }
    }`

The output is `** Choco 4.10.4 (2020-09) : Constraint Programming Solver, Copyright (c) 2010-2020

 Model[Model-0]

[ 10 vars -- 7 cstrs ]
satisfaction  : undefined
== variables ==
:dutycycle_2 = [40,0000000000000000 .. 60,0000000000000000]
REIF_1 = [0,1]
REIF_2 = [0,1]
cste -- 1 = 1
:wgt_2 = {1373..1377}
REIF_3 = [0,1]
not(REIF_3 = [0,1])
REIF_4 = [0,1]
not(REIF_4 = [0,1])
IV_5 = [0,2]
== constraints ==
REALCONSTRAINT ([RealPropagator(:dutycycle_2, REIF_1) ->("( {0} = 40.0)")])
REALCONSTRAINT ([RealPropagator(:dutycycle_2, REIF_2) ->("( {0} = 60.0)")])
ARITHM ([REIF_1 = [0,1] + REIF_2 = [0,1] = 1])
REIF_3 = [0,1]=>ARITHM ([:wgt_2 <= 1375]), !REIF_3 = [0,1]=>ARITHM ([:wgt_2 >= 1376])
REALCONSTRAINT ([RealPropagator(:dutycycle_2, REIF_4) ->("( {0} = 60.0)")])
SUM ([PropXplusYeqZ(not(REIF_4), REIF_3, IV_5)])
ARITHM ([IV_5 >= 1])

[33mwarning: Certification not implemented for over-constrained systems [0m
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1373 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 1 ,not(REIF_4 = 1) ,IV_5 = 1 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1374 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 1 ,not(REIF_4 = 1) ,IV_5 = 1 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1375 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 1 ,not(REIF_4 = 1) ,IV_5 = 1 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1373 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1374 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1375 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] ,REIF_1 = 1 ,REIF_2 = 0 ,cste -- 1 = 1 ,:wgt_2 = 1373 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] ,REIF_1 = 1 ,REIF_2 = 0 ,cste -- 1 = 1 ,:wgt_2 = 1374 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] ,REIF_1 = 1 ,REIF_2 = 0 ,cste -- 1 = 1 ,:wgt_2 = 1375 ,REIF_3 = 1 ,not(REIF_3 = 1) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 2 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1376 ,REIF_3 = 0 ,not(REIF_3 = 0) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 1 ,
:dutycycle_2 = [60,0000000000000000 .. 60,0000000000000000] ,REIF_1 = 0 ,REIF_2 = 1 ,cste -- 1 = 1 ,:wgt_2 = 1377 ,REIF_3 = 0 ,not(REIF_3 = 0) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 1 ,
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] ,REIF_1 = 1 ,REIF_2 = 0 ,cste -- 1 = 1 ,:wgt_2 = 1376 ,REIF_3 = 0 ,not(REIF_3 = 0) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 1 ,
:dutycycle_2 = [40,0000000000000000 .. 40,0000000000000000] ,REIF_1 = 1 ,REIF_2 = 0 ,cste -- 1 = 1 ,:wgt_2 = 1377 ,REIF_3 = 0 ,not(REIF_3 = 0) ,REIF_4 = 0 ,not(REIF_4 = 0) ,IV_5 = 1 ,
`

**Comment by cprudhom** [comment]
After investigating for a while, I open an issue on [ibex-team/ibex-java](https://github.com/ibex-team/ibex-java).
You can have a look at it: [Issue#2](https://github.com/ibex-team/ibex-java/issues/2)

**Comment by JiiTee** [comment]
Thank you @cprudhom!

**Comment by cprudhom** [comment]
There is an [answer from Gilles Chabert](https://github.com/ibex-team/ibex-java/issues/2#issuecomment-696684934) (Ibex's project leader). Strictly speaking, there is no bug, it is related to continuous world. Those specific cases could be directly managed by Choco but IMHO that goes out the scope of the library.
