### ISSUE TITLE
[BUG] Bug in simple implication and equality

### ISSUE THREAD

**Issue by schmittjoaopedro** [chocoteam/choco-solver#737]
Hello,

I'm getting wrong results when executing the following source code:
```java
        Model model = new Model();
        IntVar qtdActive = model.intVar("qtdActive", 0, 2, true);
        BoolVar active = model.boolVar("active");
        IntVar qtd = model.intVar("qtd", 0, 2, true);

        qtdActive.ge(1).post();
        active.eq(1).post();
        active.eq(1).imp(qtd.eq(qtdActive)).post();

        model.getSolver().propagate();
        System.out.println(active); // prints active = 1
        System.out.println(qtd); // prints qtd = [0,2] (wrong, should be [1,2])
        System.out.println(qtdActive); // prints qtdActive = [1,2]
```

I expect qtd to print [1,2].
If I change the constraint `active.eq(1).imp(qtd.eq(qtdActive)).post();` to `active.eq(1).imp(qtd.eq(2)).post();`, then it works fine.

Additionaly, I've seen that if I use the following constraint it works.
```java
active.eq(1).imp(qtd.sub(qtdActive).eq(0)).post();
```
I've seen that this approach uses a different propagator, but its very difficult to be aware of this tricks. Is it possible to fix this in the choco-solver API?

For not bounded variables that is a little strange behavior as well:
```java
        Model model = new Model();
        BoolVar x = model.boolVar("x");
        IntVar y = model.intVar("y", new int[]{0, 1, 2});
        IntVar z = model.intVar("z", new int[]{0, 1, 2});

        z.ne(1).post();
        //x.eq(1).imp(y.eq(z)).post(); // wrong -> y = {0..2}
        //x.eq(1).imp(y.sub(z).eq(0)).post(); // wrong -> y = {0..2}
        //y.eq(z).post(); // right -> y = {0,2}
        y.sub(z).eq(0).post(); // right -> y = {0,2}
        x.eq(1).post();

        model.getSolver().propagate();
        System.out.println(x);
        System.out.println(y);
        System.out.println(z);
```

## Environment
* Choco-solver version: 4.10.4
* Java version: 13

**Comment by schmittjoaopedro** [comment]
Additionaly, I've seen that if I use the following constraint it works.
```java
active.eq(1).imp(qtd.sub(qtdActive).eq(0)).post();
```
I've seen that this approch uses a different propagator, but its very difficult to be aware about this tricks. Is it possible to fix this in the choco-solver API?

**Comment by cprudhom** [comment]
I just detected and fixed a bug in `imp` operator.
I suppose your issue is related to this one. 
I let you know.

**Comment by cprudhom** [comment]
Well, this is not related to `imp` but to `PropXeqYCReif`.
Actually, `qtd.eq(qtdActive)` part is turned in `PropXeqYCReif` whose algorithm could be improved when `b` is set to true.
