### ISSUE TITLE
[BUG] DomOverWDeg omits non-instantiated variables.

### ISSUE THREAD

**Issue by fhermeni** [chocoteam/choco-solver#824]
**Describe the bug**

While testing choco-solver 4.10.7, I faced a regression in a test that now finds more solutions than before.
It seems that there is an issue in DomOverWDeg#getVariable() that returns null despite some variables being not instantiated.

**To Reproduce**

- Get this code: https://github.com/btrplace/scheduler/tree/test-choco-4.10.7
- Run VectorPackingTest.test2DLoadSup()

**Expected behavior**
A passing test :D
Setting another search strategy fixes the problem.

**Environment (please complete the following information):**
- Choco-solver version: 4.10.7-SNAPSHOT
- JRE : 8

**Additional context**
Good luck, thanks for your help.

**Comment by cprudhom** [comment]
Fix by 0f1e2964ed1f1cf1ea0726c4f17018b984090928
