### ISSUE TITLE
[BUG] Issue with PropXplusYeqZ

### ISSUE THREAD

**Issue by mrattfeldt** [chocoteam/choco-solver#841]
**Describe the bug**

The following test fails with a contradiction:

```
  @Test
  public void testPropXplusYeqZFailure() {
    final Model model = new Model("XplusYeqZFailure");

    final IntVar x = model.intVar(0, 1).mul(2).intVar();
    final IntVar y = model.intVar(0, 1).mul(2).intVar();
    final IntVar z = model.intVar(0, 4);

    // It is likely that b118dd192bc5e15d228d2b7d25dd5dc93a2781e1 is the culprit.
    // There seems to be a problem with IntScaleView.nextValueOut().
    Assertions.assertDoesNotThrow(
        () -> new PropXplusYeqZ(x, y, z).propagate(PropagatorEventType.FULL_PROPAGATION.getMask())
    );
  }
```

**To Reproduce**

See failing unit test above.

**Expected behavior**

The test should not fail.

**Possible solution**
It is likely that b118dd192bc5e15d228d2b7d25dd5dc93a2781e1 is the culprit.
There seems to be a problem with IntScaleView.nextValueOut().

**Environment (please complete the following information):**
- Choco-solver version: 4.10.7 (or current `master`)
- JRE : 11

**Comment by cprudhom** [comment]
Thank you, that is, actually, related to a bug in `IntScaleView`
