### ISSUE TITLE
[BUG] Simple Arithmetic Expression without solution

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/choco-solver#848]
**Describe the bug**
There is a regression where a simple arithmetic (feasible) model does not have solution in the latest release (4.10.7).

**To Reproduce**
Add the junit test below.
```java
@Test
public void testArithmRegression() {
	Model m = new Model();
	IntVar a = m.intVar("a", 0, 9);
	IntVar b = m.intVar("b", 0, 9);
	IntVar c = m.intVar("c", 0, 9);
	// 100a + 10b + c >= a * b * c
	a.mul(100).add(b.mul(10)).add(c).ge(a.mul(b).mul(c)).post();
	m.allDifferent(a, b, c).post();
	boolean answer = m.getSolver().solve();
	m.getSolver().printStatistics();
	assertTrue(answer);		
}
```

**Expected behavior**
The version finds a solution 4.10.6 whereas the version 4.10.7 does not.
Clearly, the problem is feasible because a*b*c is always lower than 100a  

**Possible solution**
Optionally, suggest a fix/reason for the bug or ideas how to implement the addition or change.

**Environment (please complete the following information):**
- Choco-solver version: 4.10.6 -> 4.10.7
- JRE : openjdk 11.0.13 2021-10-19

**Additional context**

The solver output has also changed and apparently embeds unicode characters.
```
[1m[34m** Choco 4.10.7 (2021-10) : Constraint Programming Solver, Copyright (c) 2010-2021
```

**Comment by cprudhom** [comment]
Hi there,
This is related to #841 and fix in the master.
