### ISSUE TITLE
Regression (solution not found anymore with 4.10.7)

### ISSUE THREAD

**Issue by clo-vis** [chocoteam/choco-solver#855]
This used to work until version 4.10.6:
```
var model = new Model();
var a = model.intVar("a", 0, 1);
a.mul(2).add(a).intVar();
System.out.println(model.getSolver().findSolution());
```
and the output was  _Solution: a=0, mul_exp_1=0, sum_exp_2=0_

With 4.10.7, the output is _null_.

**Comment by cprudhom** [comment]
Hi there,
Thank you for the bug report.
This is related to #841 and fix in the master.

I will release 4.10.8 asap.

Best regards
CP
