### ISSUE TITLE
Misleading wrong upper / lower bound message ?

### ISSUE THREAD

**Issue by dimitri-justeau** [chocoteam/choco-solver#861]
When the upper bound (resp. lower bound) of an integer variable is modified through `updateUpperBound` (resp. `updateLowerBound`), if this modification introduces a contradiction, the displayed message is `new lower bound is greater than upper bound` (resp. `new upper bound is lesser than lower bound`). However, what is "new" is the upper bound (resp. lower bound), not the opposite.

I believe that this message is misleading because it lets the user think that the contradiction is due to a lower bound (resp. upper bound) modification, whereas it is the opposite. Should these message be changed ?

https://github.com/chocoteam/choco-solver/blob/3894c5db33c205c5652e2ad0115e781db8cb285c/solver/src/main/java/org/chocosolver/solver/variables/impl/AbstractVariable.java#L55

https://github.com/chocoteam/choco-solver/blob/3894c5db33c205c5652e2ad0115e781db8cb285c/solver/src/main/java/org/chocosolver/solver/variables/impl/AbstractVariable.java#L60

**Comment by dimitri-justeau** [comment]
EDIT: or maybe have one message for `updateUpperBound`, one message form `updateLowerBound`, and keep these two message for `updateBounds`, where they are relevant ?

**Comment by cprudhom** [comment]
You are right, the messages were mixed up, I will correct this.
However, they were not relevant for `updateBounds` as well.
