### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emman91** [chocoteam/choco-solver#884]
### Discussed in https://github.com/chocoteam/choco-solver/discussions/883

<div type='discussions-op-text'>

<sup>Originally posted by **emman91** March  1, 2022</sup>
Hi,

I'm not an expert on licensing  so i would like to know more about the BSD license used for choco-solver.

If i use choco-solver instructions inside a commercial code i develop, do i need to make my code accessible by anyone or i can keep my code only for me ?

Thanks in advance

Emmanuel</div>

**Comment by cprudhom** [comment]
Hi Emmanuel

You can redistribute and use the source and jar files of choco with or without modifications  provided that the following conditions are met:
1. Redistributions of source code must retain the copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software must display the following acknowledgement:
   This product includes software developed by the IMT Atlantique.
4. Neither the name of the IMT Atlantique nor the names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

Best regards,
CP
