### ISSUE TITLE
[BUG] Element constraint for reals returns an array exception

### ISSUE THREAD

**Issue by gjasper** [chocoteam/choco-solver#913]
Element constraint for reals return an array exception when the variable has its bounds out of the range supported by the elements in the array.

**To Reproduce**

        Model model = new Model();
        RealVar x = model.realVar("V", 0., 2., 1.e-4);
        IntVar y = model.intVar("I", 0, 1);
        model.element(x, new double[]{3.0, 7.0}, y).post();
        model.getSolver().findSolution();

**Expected behavior**
The equivalent problem for integers returns a ContradictionException. I guess the behavior should be the same in this case.

**Possible solution**
Check the bounds against the element array and return ContradictionException if the intervals do not overlap.

**Screenshots**
![image](https://user-images.githubusercontent.com/18621972/173898506-774d1d19-6351-41ec-9ada-5968ee98b079.png)

**Environment**
- Choco-solver version: 4.10.9-SNAPSHOT
- JRE : 11

**Comment by gjasper** [comment]
I added some tests and created a simple solution. Available in pull request #914

**Comment by gjasper** [comment]
Hi Charles. Thank for your answer.
In my report I forgot to mention that there is the mirror case as well. The variable can be either below or above the elements in the array. The following model returns a array exception as well.

        Model model = new Model();
        RealVar x = model.realVar("V", 8., 10., 1.e-4);
        IntVar y = model.intVar("I", 0, 1);
        model.element(x, new double[]{3.0, 7.0}, y).post();
        model.getSolver().findSolution();

I noticed your solution covers one case but not the other.

**Comment by cprudhom** [comment]
You are right, I fixed the issue without thinking of the lower case.
