### ISSUE TITLE
Reduce assets (jar files) attached to a release

### ISSUE THREAD

**Issue by cprudhom** [chocoteam/choco-solver#955]
Since now, [releases available on GitHub](https://github.com/chocoteam/choco-solver/releases) list 6 assets. 
For instance, `4.10.10`'s assets are:

- [choco-parsers-4.10.10-light.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-parsers-4.10.10-light.jar) 5.63 MB
- [choco-parsers-4.10.10-sources.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-parsers-4.10.10-sources.jar) 177 KB 
- [choco-parsers-4.10.10.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-parsers-4.10.10.jar) 400 KB
- [choco-solver-4.10.10-jar-with-dependencies.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-solver-4.10.10-jar-with-dependencies.jar) 10.3 MB
- [choco-solver-4.10.10-sources.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-solver-4.10.10-sources.jar) 1.28 MB
- [choco-solver-4.10.10.jar](https://github.com/chocoteam/choco-solver/releases/download/v4.10.10/choco-solver-4.10.10.jar) 1.92 MB

And for users, it is not obvious which jar should be selected.
I think we can limit assets to `choco-parsers-4.10.10-light.jar`, probably with simpler name, like `choco-4.10.10.jar`.
If someone does not want dependencies or parser, then he/she should use maven commands to build the right jar, or even better, use a project build tool like Maven or Gradle.

**Comment by dimitri-justeau** [comment]
Do you plan to just limit the assets in Github releases (with no changes over the Maven structure), or change what is produced by Maven?

**Comment by cprudhom** [comment]
I plan to only limit the assets in GitHub and encourage users to base their projects on maven/gradle

**Comment by dimitri-justeau** [comment]
Okay, I think it is a good idea indeed !
